### ISSUE TITLE
memory related issue

### ISSUE THREAD

**Issue by mongsilcho** [eProsima/Fast-RTPS#10]
Hi 
Great to see this lean and nice RTPS implementation in source code. 
Unfortunately we found  the issue of memory leaked when we run RTSPTest_as_socket example
Could you let me know how to fix it? 
We are planned to test and evaluate your fastRTPS .

I want to get a great time to evaluate and performance test  Fast-RTPS. 
Thank you. 
Best Regards. steven.

**Comment by JaimeMartin** [comment]
Solved.
