### ISSUE TITLE
Participant removing discovery (DROPPED_RTPSPARTICIPANT)

### ISSUE THREAD

**Issue by alekseymt74** [eProsima/Fast-RTPS#100]
In `RemoteParticipantLeaseDuration::event(<..>)` `mp_participantProxyData->m_guid` is copied to `RTPSParticipantDiscoveryInfo info` after it's removal. So `m_guid `value is broken.

**Comment by JavierIH** [comment]
Thank you, fixed in c9c4285fd175aceab67ef84cc037e9f6593fb62c
