### ISSUE TITLE
1.9.x branch is failing after #918 [7595]

### ISSUE THREAD

**Issue by ivanpauno** [eProsima/Fast-RTPS#1007]
## Expected Behavior

It should build.

## Current Behavior

It's broken since https://github.com/eProsima/Fast-RTPS/commit/d1d7605f84c6b91f89bb0245f3770bed2d2bab36.
Here the linker failures: https://ci.ros2.org/job/ci_linux/9315/console#console-section-31.

## Steps to Reproduce

Build ros2, using `master` repos.

## System information

- Fast-RTPS version: 1.9.x
- OS: Ubuntu 18.04
- Network interfaces: 
                      
- ROS2:  Foxy (master)
        

## Additional context

Seems that #918 triggered the problem.

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by MiguelCompany** [comment]
It seems the compiler is inlining the template method `EDPSimple::serialize_proxy_data` when built on release. Our CI builds are rel-with-deb-info, and thus didn't fail. I have checked that adding ` __attribute__((noinline))` to the said method fixes the issue. Even though, I would like to have a compiler agnostic solution

**Comment by MiguelCompany** [comment]
@ivanpauno I have just created PR #1009 that fixes this

**Comment by MiguelCompany** [comment]
@ivanpauno PR #1009 has just been merged. I have checked locally that building following the same steps as on https://ci.ros2.org/job/ci_linux/9315/console#console-section-31 with `--packages-up-to fastrtps` yields no error.

**Comment by ivanpauno** [comment]
Thanks for fixing the issue @MiguelCompany !

**Comment by mjcarroll** [comment]
Test build through our CI to verify.

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9326)](http://ci.ros2.org/job/ci_linux/9326/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5016)](http://ci.ros2.org/job/ci_linux-aarch64/5016/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7636)](http://ci.ros2.org/job/ci_osx/7636/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9249)](http://ci.ros2.org/job/ci_windows/9249/)
* Windows-container [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows-container&build=123)](http://ci.ros2.org/job/ci_windows-container/123/)
