### ISSUE TITLE
Fast cdr doesn't get installed.

### ISSUE THREAD

**Issue by ufechner7** [eProsima/Fast-RTPS#101]
Hello,
I followed the instructions how to build from source, but 
sudo make install
does not install the the fast cdr library and headers.
This should be fixed (probably in the makefile).

**Comment by ufechner7** [comment]
Added pull request for the manual:
https://github.com/eProsima/Fast-RTPS-docs/pull/1/commits

**Comment by richiware** [comment]
#107 was solved. I will close this issue. Thanks for the reporting
