### ISSUE TITLE
ROS 2 Fast-RTPS <-> Connext test_communication tests not completing properly [7610]

### ISSUE THREAD

**Issue by clalancette** [eProsima/Fast-RTPS#1014]
On February 10th, all of the ROS 2 jobs completed the test_communication tests properly: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1455/ (ignore the other errors, they are bugs elsewhere in ROS 2).  On February 11th, the test_communication tests between RTI Connext and Fast-RTPS started failing: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1456/

If I take the ROS 2 code as of February 10th, and just update Fast-RTPS to the latest commit on the 1.9.x branch (https://github.com/eProsima/Fast-RTPS/commit/2577261bb140f595ce9ba50e32163f866669aee4), the tests fail: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/1460/ .  Similarly if I take all of the latest ROS 2 code and pin Fast-RTPS to https://github.com/eProsima/Fast-RTPS/commit/c7b6d9361c48e61d2c7117ef3fbc44812b1b6139 , the tests succeed: https://ci.ros2.org/job/ci_linux/9339

There are 7 commits in the range between c7b6d9361c48e61d2c7117ef3fbc44812b1b6139 and 2577261bb140f595ce9ba50e32163f866669aee4 , but unfortunately two of them are huge.  So a bisection isn't going to tell us much here.

## Expected Behavior
Interoperability between Fast-RTPS and RTI Connext should succeed

## Current Behavior
The Fast-RTPS <-> RTI Connext tests time out.

## Steps to Reproduce
It's a bit difficult to provide a standalone reproducer.  The tests that are failing launch a publisher and subscriber, and let them both run for a finite amount of time (typically 10 seconds).  If the subscriber receives all of the messages it expects to before the timeout, that's a success.

## System information

- Fast-RTPS version: commit 2577261bb140f595ce9ba50e32163f866669aee4
- OS: Ubuntu 18.04, all architectures (may also happen on other OSs, I haven't looked)
- Network interfaces: localhost
- ROS2:  master

**Comment by clalancette** [comment]
Just as another data point, https://ci.ros2.org/job/ci_linux/9340 is bumped up to https://github.com/eProsima/Fast-RTPS/commit/c3131012337ea3939cae9cb2be4931a641558477 , and this fails tests.

**Comment by dirk-thomas** [comment]
Bisecting the changes shows that #1003 introduced this regression.

**Comment by IkerLuengo** [comment]
Should be solved once #1015 is merged.

Thanks @clalancette  and @dirk-thomas for rising the issue and the analysis.

**Comment by MiguelCompany** [comment]
@clalancette Since #1015 has been merged, and @dirk-thomas confirmed [here](https://github.com/eProsima/Fast-RTPS/pull/1015#issuecomment-586374219) that it fixes the problem, I suppose that this issue can be closed.

**Comment by clalancette** [comment]
> @clalancette Since #1015 has been merged, and @dirk-thomas confirmed [here](https://github.com/eProsima/Fast-RTPS/pull/1015#issuecomment-586374219) that it fixes the problem, I suppose that this issue can be closed.

I'm running another test on the ROS 2 infrastructure with the latest 1.9.x branch to test.  We can close this for now, if it turns out that there is still a problem, I will reopen.
