### ISSUE TITLE
msg field exceeds the maximum length

### ISSUE THREAD

**Issue by ufechner7** [eProsima/Fast-RTPS#103]
I try to publish a message of 720 bytes and get an error message.

The max. message size is not documented in the documentation. Furthermore, it is not documented how to increase it.

**Comment by ufechner7** [comment]
Perhaps the field size is the problem, and not the total message size?

**Comment by richiprosima** [comment]
Are you using the low-level RTPS layer (RTPSWriter, RTPSReader...) or the high-level Publisher/Subscribe layer? If you are using the second one, did you generated type support source code with fastrtpsgen application or didn't?

**Comment by ufechner7** [comment]
I am using the following definition:
`// LogString.idl
struct LogString
{
	long long msg_id; // sequence number, can be used to detect missing log messages    
	string msg;       // the ASCII log message
};`
and the high level publisher subscriber.
I used the code, generated by fastrtpsgen as starting point.

**Comment by ufechner7** [comment]
Ok, I found where the exceptions is coming from:
```
void LogString::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_msg_id;

    if(m_msg.length() <= 255)
    scdr << m_msg;
    else
        throw eprosima::fastcdr::exception::BadParamException("msg field exceeds the maximum length");
}
```
This is autogenerated code, and the number 255 is hardcoded in the file LogString.cxx . Is it safe to increase it? Where else but in this file is it used?

**Comment by ufechner7** [comment]
Ok, I defined a constant `MAX_SIZE = 1023` and changed the following two lines in the file LogString.cxx (the name depends on the message name) to make use of this constant:
```
	current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + MAX_SIZE + 1;
```
and
```
	if(m_msg.length() <= MAX_SIZE)
```
and recompiled the publisher and the subscriber.

Now everything works fine.

What should be done:

- modify the code generator to use a constant
- document, how this constant is calculated
- document, how where it can be changed

**Comment by richiprosima** [comment]
By default Fast RTPS uses preallocated memory for user data and for this reason user data has to have a maximum length. Some dynamic types, as string or sequences, are generated by ```fastrtpsgen``` with a maximum length, if the user doesn't define a maximum. We will  document this better.

OMG IDL supports to set a maximum length to strings:
```
    string<1024> msg;
```

**Comment by ufechner7** [comment]
Good to know!

**Comment by richiware** [comment]
@ufechner7 I will close this issue. If you still have questions, you can reopen it. Thanks
