### ISSUE TITLE
EDP ReaderListener not notified about some cache changes

### ISSUE THREAD

**Issue by wtsnyder** [eProsima/Fast-RTPS#105]
When attaching a user listener to a participants EDP readers the user listener is only notified of EDP cache changes if ```change->kind == ALIVE``` .  This appears to be caused by the '''attached_listener->onNewCacheChangeAdded''' method only being called when that condition is true in '''cpp/rtps/builtin/discovery/endpoint/EDPSimpleListeners.cpp" both in the '''EDPSimplePUBListener" and "EDPSimpleSUBListener".

Without the other types of EDP messages, user listeners can tell when new reader or writer endpoints are found but not when they are destroyed.

**Comment by richiprosima** [comment]
I've fixed it in 6322cb9e875f685e9f68619143ded9374765ecb9. You have an example how to use it in our [tests](https://github.com/eProsima/Fast-RTPS/blob/6322cb9e875f685e9f68619143ded9374765ecb9/test/blackbox/PubSubWriter.hpp#L93-L181)
