### ISSUE TITLE
Compiler warning TemplateDataQosPolicy deprecated copy [7877]

### ISSUE THREAD

**Issue by dirk-thomas** [eProsima/Fast-RTPS#1053]
This happens with newer gcc on Ubuntu Focal: see e.g. http://build.ros2.org/view/Fci/job/Fci__nightly-fastrtps_ubuntu_focal_amd64/51/warningsResult/

`ReaderQos.h:35`:

```
implicitly-declared  ‘eprosima::fastrtps::TemplateDataQosPolicy&  eprosima::fastrtps::TemplateDataQosPolicy::operator=(const  eprosima::fastrtps::TemplateDataQosPolicy&)’ is deprecated  [-Wdeprecated-copy]
```

**Comment by MiguelCompany** [comment]
@dirk-thomas After testing on my brand-new Ubuntu Focal virtual machine, #1056 should fix this.

**Comment by dirk-thomas** [comment]
Thank you for the quick fix.

**Comment by MiguelCompany** [comment]
Closing after #1056 has been merged
