### ISSUE TITLE
[Security] publisher / subscriber within same participant not matched when using security

### ISSUE THREAD

**Issue by mikaelarguedas** [eProsima/Fast-RTPS#106]
[
This call](https://github.com/eProsima/Fast-RTPS/blob/6322cb9e875f685e9f68619143ded9374765ecb9/src/cpp/rtps/builtin/discovery/endpoint/EDP.cpp#L624) to `discovered_reader()` returns false if the Publisher and Subscriber are in the same participant preventing them to communicate.

Given that security plugins run at the participant level, would it make sense that a participant automatically consider itself authenticated / validated? If not, how would you suggest a participant to perform handshake with itself?

Thanks!

**Comment by mikaelarguedas** [comment]
@richiprosima Any feedback/advice on this ?

**Comment by richiware** [comment]
[release/1.5.0](https://github.com/eProsima/Fast-RTPS/tree/release/1.5.0) is being testing. It contains the solution to your problem. Related commit is 254f0a7f57ab513d4e6552632fd2fa097344980a

**Comment by richiware** [comment]
@mikaelarguedas Did release 1.5.0 solve the issue?

**Comment by mikaelarguedas** [comment]
Didn't have time to try it since the official release, I'll give it a shot today and report here with the result

**Comment by mikaelarguedas** [comment]
@richiware Just tested this and it is indeed fix with the current state of master. Thanks!
