### ISSUE TITLE
nested structs on .idl file

### ISSUE THREAD

**Issue by Marcocaster** [eProsima/Fast-RTPS#109]
Hello, how can I use Nested structs in he idl file? at the moment the only way i could get it to work is to create a different participant for every struct i want to use ( so not using nested structs). 
I tried several possibility but , as an example:

1) If I declare the nested struct as follows:
struct date
{
   int date;
   int month;
   int year; 
};

struct Employee
   {
   char ename[20];
   int ssn;
   float salary;
   struct date doj;
}emp1;

I get an error from the fastrtpsgen
2) If I decalare as follow:
struct Employee
{
   char ename[20];
   int ssn;
   float salary;
   struct date
       {
       int date;
       int month;
       int year; 
       }doj;
}emp1;

I don't get any error but the nested struct does not appear in the generated file..

AWhat am I missing? Thank you very much,
Marco

**Comment by richiprosima** [comment]
OMG IDL file format has differencies with the way structures are defined in C++. I've found several errores in your first declaration:

* ```int``` type doesn't exist in IDL. On IDL this type is named ```long```
* Declaration of a nested struct doesn't need the word ```struct``` before the name of the type.
* After the closing of a struct, IDL doesn't support define a name of an object as you do with ```emp1```

After correction the result is:

```
struct date
{
    long date;
    long month;
    long year;
};

struct Employee
{
    char ename[20];
    long ssn;
    float salary;
    date dobj;
};
```

**Comment by richiware** [comment]
I will close this issue. Thanks
