### ISSUE TITLE
Application hangs when trying to create a participant

### ISSUE THREAD

**Issue by mtheall** [eProsima/Fast-RTPS#1144]
## Expected Behavior
Participant created

## Current Behavior
Application hangs
Must be some kind of race condition because it only hangs about half of the time.

## Steps to Reproduce
1. Create a participant via eprosima::fastrtps::Domain::createParticipant

## System information
- Fast-RTPS version: 1.10.0 (release tarball)
- OS: Fedora 31, CentOS 7
- Network interfaces: enp0s31f6 (192.168.1.211)
- ROS2: N/A

## Additional context
Thread 1 waiting on eprosima::fastrtps::Domain::m_mutex which is held by thread 2
Thread 2 waiting on  m_send_resources_mutex_ which is held by thread 12
Thread 12 blocking on pthread_cond_broadcast indefinitely, which seems weird

## Additional resources
See attached stack trace
[stacktrace.txt](https://github.com/eProsima/Fast-RTPS/files/4477868/stacktrace.txt)

**Comment by adolfomarver** [comment]
@mtheall 
1.10.0 uses the new shared-memory transport as default, We have detected an issue when the processes don't exit properly (debuggers, SIGTERM, SIGINT). In those cases shared-memory is corrupted and the next execution or already running processes can be affected.

We are working in a fix. By the moment, as a workaround two options are available.
1) You can `rm /dev/shm/* ` before running you apps to clean possible corruptions.
2) You can disable SHM transport:

This can be done in the source code or by XML file:

C++

```
 //Create a descriptor for the new transport.		
 auto udp_transport = std::make_shared<UDPv4TransportDescriptor>();
 //Disable the built-in Transport Layer.
 participant_attr.rtps.useBuiltinTransports = false;
 //Link the Transport Layer to the Participant.
 participant_attr.rtps.userTransports.push_back(udp_transport);

```
XML

```
<transport_descriptors>
    <transport_descriptor>
        <transport_id>udp_transport</transport_id>
        <type>UDPv4</type>
    </transport_descriptor>
</transport_descriptors>

<participant profile_name="Participant">
    <rtps>
        <userTransports>
            <transport_id>udp_transport</transport_id>
        </userTransports>
        <useBuiltinTransports>false</useBuiltinTransports>
    </rtps>
</participant>

```

**Comment by mtheall** [comment]
That fits in with my symptoms because it only seems to happen when I SIGTERM my processes and restart them (our applications never normally exit, so SIGTERM is how we stop them). I have disabled the SHM transport in the meantime and haven't experienced any issues.

However, the main reason for us to upgrade is in fact for the SHM transport. We have a lot of processes using Fast-RTPS and we transmit a lot of data. We get a lot of cpu overhead using the UDP transport that isn't present when the SHM is working. Using jumbo frames alleviates the overhead, but not as much as SHM does.

**Comment by adolfomarver** [comment]
@mtheall #1147 Should fix the problem. Please, check-it out.

**Comment by mtheall** [comment]
SHM_TRANSPORT_DEFAULT doesn't appear to be defined during compile-time (so not a builtin transport) unless I explicitly `cmake .. -DSHM_TRANSPORT_DEFAULT=ON`. Otherwise, seems to be working as expected.

**Comment by adolfomarver** [comment]
@mtheall For #1147 option SHM_TRANSPORT_DEFAULT=ON is the default value in CMakeLists.txt, shouldn't be necessary to set it manually, although this option was not present in v1.10.0. Did you delete the build directory and rebuild cmake from the scrach?

**Comment by mtheall** [comment]
Yes I had deleted the build directory and rebuild cmake in a new directory. Looks like it is because the option is set *after* add_subdirectory. It works without being explicit if I move it before any add_subdirectory (I placed it immediately after SQLITE3_SUPPORT option).

**Comment by adolfomarver** [comment]
Good catch! After review and some more testing we will merge this fix in the next release. Thanks for your feedback.

**Comment by michael13491** [comment]
Hi @adolfomarver, for the workaround suggestion above 

> You can rm /dev/shm/* before running you apps to clean possible corruptions.

What would be the equivalent of that in a windows environment?

Thanks for your help

**Comment by MiguelCompany** [comment]
@michael13491 You could remove all files on `C:\ProgramData\eprosima\fastrtps_interprocess`

**Comment by michael13491** [comment]
> @michael13491 You could remove all files on `C:\ProgramData\eprosima\fastrtps_interprocess`

Thank you @MiguelCompany, that worked like a charm.
