### ISSUE TITLE
CDRMessage_t is hard to use without leaking memory

### ISSUE THREAD

**Issue by clalancette** [eProsima/Fast-RTPS#115]
ROS2 currently uses the CDRMessage_t struct to fill in a ReaderProxyData class, here: https://github.com/ros2/rmw_fastrtps/blob/master/rmw_fastrtps_cpp/src/functions.cpp#L440 .  However, this code is prone to memory-leaks; in particular, if you default construct a CDRMessage_t, it allocates the .buffer member, but then we are immediately replacing it below, leading to a leak.  It also requires us to remember to set the "wraps" member to true so that the data won't be attempted to be freed in the destructor.

It seems to me that this could be made much less error-prone by making this a class with private member variables, and then having constructors/accessor methods to set things up as required.  What do you think of this idea?

**Comment by mikaelarguedas** [comment]
@clalancette the link returns 404 since rmw_fastrtps_cpp has been refactored, can you update it and use a permalink to be future-proof ?

**Comment by MiguelCompany** [comment]
I think this does not apply anymore to the current state of Fast-RTPS. Closing this issue.
