### ISSUE TITLE
Best effort publisher stops sending to local subscribers when remotes connect

### ISSUE THREAD

**Issue by dhood** [eProsima/Fast-RTPS#116]
Since the 1.5.0 fastrtps release the following issue has appeared in ROS 2:

1. There is a best effort publisher talking to best effort subscriber(s) on the same machine.
1. A best effort subscriber connects on the same domain ID but a remote machine.
1. The best effort subscriber connected remotely receives message, but the local subscriber(s) does not.
1. When the remote subscriber is killed, the local subscribers receive messages again.
1. Repeat. Whenever the remote subscriber is connected, the local ones do not receive messages.

Steps to reproduce with the minimal ROS 2 talker/listener examples are at https://github.com/ros2/rmw_fastrtps/issues/125

Before release/1.5.0 was merged into master, switching between the two branches would consistently make the behaviour appear and disappear. Therefore I believe this to be due to a change in the latest release.

Have there been changes to the when multicast/unicast is used for best effort publishers?

**Comment by richiware** [comment]
Thanks for your report. We are testing a solution in branch [hotfix/besteffort](https://github.com/eProsima/Fast-RTPS/tree/hotfix/besteffort)

**Comment by mikaelarguedas** [comment]
thanks @richiware for the quick fix. I tested it and it fixes the talker / listener example provided by @dhood . I'm in the process on trying it on a bigger system and will report here with the results

**Comment by dhood** [comment]
Thanks @richiware, we've tested more complex demos and the hotfix/besteffort branch resolves the issues. We also ran CI using that branch and none of the integration tests have regressions.

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2824)](http://ci.ros2.org/job/ci_linux/2824/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=329)](http://ci.ros2.org/job/ci_linux-aarch64/329/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2281)](http://ci.ros2.org/job/ci_osx/2281/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2961)](http://ci.ros2.org/job/ci_windows/2961/)

So, from our side, that branch looks good and we'll use it for the ROS 2 release (or master if you choose to merge it by then)

**Comment by richiware** [comment]
The branch was merged into master. Thanks for your help.

**Comment by dhood** [comment]
Thanks!
