### ISSUE TITLE
osX build broken in 1.10.x branch

### ISSUE THREAD

**Issue by ivanpauno** [eProsima/Fast-RTPS#1168]
## Expected Behavior

Should build on macOS.

## Current Behavior

Doesn't seem to be building.

## Steps to Reproduce

Here a ROS2 CI job:
https://ci.ros2.org/job/ci_osx/8432/console.

The problem seems to have been introduced in https://github.com/eProsima/Fast-RTPS/pull/1147.

## System information

- Fast-RTPS version: 1.10.x
- OS: osX Mojave.
- Network interfaces: 
                      
- ROS2:  Foxy  (master)
        

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by ivanpauno** [comment]
I see another job passing here: http://ci.ros2.org/job/ci_osx/8433/, so I'm a bit confused.
I will check tomorrow and comment here.

**Comment by Blast545** [comment]
I had that same problem yesterday with these two jobs:

https://ci.ros2.org/job/ci_osx/8427/console
https://ci.ros2.org/job/ci_osx/8431/console

**Comment by ivanpauno** [comment]
@richiprosima It would be good if this can be fixed.

Our results are currently confusing, osX builds are failing on some of our CI machines but not in others.
Details:

- `mini3` successes to build https://ci.ros2.org/job/ci_osx/8452/consoleFull#console-section-18, CLANG v9.0.0.9000039
- `lore` successes to build https://ci.ros2.org/job/ci_osx/8453/consoleFull#console-section-247, CLANG v10.0.1.10010046
- `mini2` fails to build https://ci.ros2.org/job/ci_osx/8454/console#console-section-34, CLANG v10.0.1.10010046

I originally thought there was a mismatch in CLANG version, but that doesn't seem to be the case in the last two machines.
I'm trying to investigate what's the difference in the environments.

From the failure output in the third build, I guess this could be fixed without understanding why the build is failing in some machines and note in others.

**Comment by MiguelCompany** [comment]
@ivanpauno Could you check with #1169?

**Comment by ivanpauno** [comment]
@MiguelCompany It seems to be failing with the same error https://ci.ros2.org/job/ci_osx/8458/consoleFull#console-section-165, I checked and `bug/pr1147_build_fail` was correctly checked out in the job.

**Comment by j-rivero** [comment]
I've looked into the Xcode version on each one:

> * `mini3` successes to build https://ci.ros2.org/job/ci_osx/8452/consoleFull#console-section-18, CLANG v9.0.0.9000039

Xcode 9.2 Build version 9C40b

> * `lore` successes to build https://ci.ros2.org/job/ci_osx/8453/consoleFull#console-section-247, CLANG v10.0.1.10010046

Xcode 10.2.1 Build version 10E1001
 
> * `mini2` fails to build https://ci.ros2.org/job/ci_osx/8454/console#console-section-34, CLANG v10.0.1.10010046

Xcode 10.3. Build version 10G8

A first impression could be that 10.3 is the responsible for breaking the build but the [release notes ](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_3_release_notes)did not help too much to me.

**Comment by MiguelCompany** [comment]
@ivanpauno We have updated PR #1169 with an additional fix

**Comment by ivanpauno** [comment]
I tried again with the last changes in #1169, and now it's working well:
https://ci.ros2.org/job/ci_osx/8478/

Let me know when that PR is merged, thanks!

**Comment by MiguelCompany** [comment]
> Let me know when that PR is merged, thanks!

@ivanpauno done!

**Comment by ivanpauno** [comment]
Thanks @MiguelCompany !!
