### ISSUE TITLE
Docker inter-container communication fails after second try [8372]

### ISSUE THREAD

**Issue by eliasdc** [eProsima/Fast-RTPS#1176]
Running a subscriber and a publisher in a separate container works the first time, but fails afterwards. Changing the network configuration of the restarted container makes it able to run it again once.

Example:
Terminal 1: 
```bash
docker run -it --rm ubuntu-fast-rtps:v1.9.3 /usr/local/examples/C++/HelloWorldExample/bin/HelloWorldExample subscriber
```
Terminal 2: 
```bash
docker run -it --rm ubuntu-fast-rtps:v1.9.3 /usr/local/examples/C++/HelloWorldExample/bin/HelloWorldExample publisher
```
The publisher will finish and the output is correct in the subscriber. Restarting the container does not publish the messages to the subscriber anymore (if it does work keep repeating until it fails with some time in between the runs).

## Expected Behavior
The subscriber should always receive the messages from the publisher no matter how many restarts.

- Fast-RTPS version: docker image v1.9.3
- Network interfaces: default docker bridge network

**Comment by eliasdc** [comment]
Can someone confirm this bug? I just want to know if it's a local issue or it is a bug in fast-rtps. It does work with cyclone dds but I need the security features.

Maybe someone can give me pointers where I should look for a solution or fix as I'm currently blocked by this issue and I have no clue where to look.

**Comment by JaimeMartin** [comment]
Hi @eliasdc , we are not reproducing the issue, maybe you could check the latest docker, corresponding to release 1.10.0 (you can download it from our website)

**Comment by eliasdc** [comment]
Thanks for trying to reproduce it. 
I tested with 1.10.0 and it is working without a problem so this issue can be closed.
With 1.9.3 I can still reproduce it and I have to find a way to update the Fast-RTPS version for our ROS2 docker containers. Thanks a lot to point me to the newer version.

**Comment by MiguelCompany** [comment]
@eliasdc Glad to help!

**Comment by eliasdc** [comment]
Do you know what the specific problem was? As I'm trying to use ROS2 Eloquent which won't update the Fast-RTPS version in this release (I asked), but for the next release they are already using 2.x. Is there a possibility for a patch to be backported to 1.9.3?
