### ISSUE TITLE
Registering two topics of same type fails with [PARTICIPANT Error] Type : HelloWorld Not Registered 

### ISSUE THREAD

**Issue by driftregion** [eProsima/Fast-RTPS#1178]
## Expected Behavior
From what I understand of the DDS spec, several topics may refer to the same data type.
DDS 1.4 - 2.2.1.2.2 Overall Conceptual Model

I expect for a client to be able to create two topics with *different* `name` and `object_id`, but same `dataType`.

## Current Behavior

I find that Micro-XRCE-DDS-Agent raises an error originating in fastrtps when a client tries to register a second topic with the same type as an already registered topic.

## Steps to Reproduce

Starting with this example:
https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/master/examples/PublishHelloWorld/main.c
I inserted the following lines after line 84:
```c
    uxrObjectId topic_id_2 = uxr_object_id(0x02, UXR_TOPIC_ID);
    const char* topic_xml_2 = "<dds>"
                                "<topic>"
                                    "<name>HelloWorldTopic2</name>"
                                    "<dataType>HelloWorld</dataType>"
                                "</topic>"
                            "</dds>";
    uint16_t topic_req_2 = uxr_buffer_create_topic_xml(&session, reliable_out, topic_id_2, participant_id, topic_xml_2, UXR_REPLACE);
```

1. `./MicroXRCEAgent udp -p 2018  -v6`
2. ` ./PublishHelloWorldClient 127.0.0.1 2018 2`
3.  Observe something like the following when attempting to create the second topic:
```
[1587707184.957832] debug   2020-04-24 13:46:24.957  | UDPServerLinux.cpp | recv_message             | [==>> UDP <<==]        | client_key: 0xAAAABBBB, len: 13, data: 
0000: 81 00 00 00 0A 01 05 00 03 00 00 00 80
[PARTICIPANT Error] Type : HelloWorld Not Registered -> Function createPublisher
```

## System information
Linux debian 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

### Micro-XRCE-DDS-Client version
commit c0a00cddb16c5faa4ddcc39fa212fe2d3ac52f29 (HEAD -> master, origin/master, origin/HEAD)
Author: Julián Bermúdez Ortega <julianbermudez@eprosima.com>
Date:   Mon Jan 27 09:47:18 2020 +0100

### Micro-XRCE-DDS-Agent version
commit 60b08dc4f501de8ff2d77220aa64a5169fe88525 (HEAD -> master, tag: v1.1.6, origin/master, origin/HEAD)
Author: Julián Bermúdez Ortega <julianbermudez@eprosima.com>
Date:   Tue Dec 17 08:41:35 2019 +0100

    DataReader closing (#130) (#133)

**Comment by julibert** [comment]
Hi @driftregion,

This error was fixed in `develop` branch. Please, could you try with the following version:

### Micro-XRCE-DDS-Agent version
commit 92b59ea63d61977430dac2b42bbb201e0112d602 (HEAD -> develop, origin/develop, origin/HEAD)

    Static compilation (#148)

**Comment by driftregion** [comment]
Hi @julibert, thanks!  I'd like to try it.
Unfortunately, building that commit fails on my machine with the following traceback:
```
[  6%] Building C object CMakeFiles/microxrcedds_client.dir/src/c/core/session/stream/input_reliable_stream.c.o
/home/njames/repos/Micro-XRCE-DDS-Agent/build/microxrcedds_client/src/microxrcedds_client/src/c/core/session/stream/input_reliable_stream.c: In function ‘on_full_input_buffer’:
/home/njames/repos/Micro-XRCE-DDS-Agent/build/microxrcedds_client/src/microxrcedds_client/src/c/core/session/stream/input_reliable_stream.c:213:5: warning: implicit declaration of function ‘ucdr_init_buffer_origin’; did you mean ‘ucdr_init_buffer_offset’? [-Wimplicit-function-declaration]
     ucdr_init_buffer_origin(
     ^~~~~~~~~~~~~~~~~~~~~~~
     ucdr_init_buffer_offset
/home/njames/repos/Micro-XRCE-DDS-Agent/build/microxrcedds_client/src/microxrcedds_client/src/c/core/session/stream/input_reliable_stream.c:217:11: error: ‘ucdrBuffer’ {aka ‘struct ucdrBuffer’} has no member named ‘offset’
         ub->offset);
           ^~
make[8]: *** [CMakeFiles/microxrcedds_client.dir/build.make:76: CMakeFiles/microxrcedds_client.dir/src/c/core/session/stream/input_reliable_stream.c.o] Error 1
```

**Comment by julibert** [comment]
Please, could you remove your build folder?
It seems that this folder contains a Client version which is not compatible.

**Comment by driftregion** [comment]
I removed the build folder and did an in-tree build
```
git clean -ffxd
cmake .
make
```
but this fails with the same traceback.  Am I correct that the client version is set in `CmakeLists.txt` as follows?
```
if(UAGENT_P2P_PROFILE)
    set(_microxrcedds_client_version 1.2.1)
    set(_microxrcedds_client_tag develop)
    list(APPEND _deps "microxrcedds_client\;${_microxrcedds_client_version}")
endif()
```
cmake seems to be checking out the develop branch:
```
[ 18%] Performing download step (git clone) for 'microxrcedds_client'
Cloning into 'microxrcedds_client'...
Switched to a new branch 'develop'
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
```

**Comment by julibert** [comment]
Sorry @driftregion, but I'm not able to reproduce your error. Please, could you confirm that you are in the following commits?:
* `agent`: 92b59ea63d61977430dac2b42bbb201e0112d602
* `client`: 68385f84a8bbaf64d32ea816731133f497f86271

**Comment by driftregion** [comment]
OK, my mistake.  I traced it back to a different version of `microcdr` I accidentally installed as root.  Rather than downloading the pinned version of `microcdr`, the build for `microxrcedds_client` used the (wrong) local copy in `/usr/local/share/microcdr`.

After fixing that, I see now that the agent is able to register two topics with the same datatype.  Thanks!
