### ISSUE TITLE
provide a syntax to include .idl files

### ISSUE THREAD

**Issue by ufechner7** [eProsima/Fast-RTPS#118]
Hello,
I want to use a set of shared enums and structs for more then one message (.idl file).
This is either currently not supported, or the documentation how to do it is missing.
Any hints appreciated!

Uwe

**Comment by richiware** [comment]
This is supported by ``fastrtpsgen`` application. Here is an example of an IDL file with those elements:

```
enum Enum1
{
    ENUM1_VALUE1,
    ENUM1_VALUE2,
    ENUM1_VALUE3
};

enum Enum2
{
    ENUM2_VALUE1,
    ENUM2_VALUE2,
    ENUM2_VALUE3
};

struct Struct1
{
    long number;
    Enum1 enumerator;
};

struct Struct2
{
    long number;
    Enum2 enumerator;
};

struct Struct3
{
    Enum1 enumerator1;
    Enum2 enumerator2;
    Struct1 struct1;
    Struct2 struct2;
};
```

**Comment by ufechner7** [comment]
I thought I need one .idl file per message. But I found out I can use
```
#include "Common.idl"
```
to include one idl file with common definitions in mutliple messages, if you pass both files as parameter to rtpsgen. This is nowhere documented.

**Comment by richiware** [comment]
I've updated the documentation, adding a [section](http://eprosima-fast-rtps.readthedocs.io/en/latest/genuse.html#including-other-idl-files) talking about it. I will close the issue.
