### ISSUE TITLE
-Wmissing_braces warnings with Clang (2.0.x)

### ISSUE THREAD

**Issue by jacobperron** [eProsima/Fast-RTPS#1192]
Using the 2.0.x branch, we see some Clang warnings on macOS: https://ci.ros2.org/job/ci_osx/8614/clang/

Line numbers:
AESGCMGMAC_Transform.cpp:685
AESGCMGMAC_Transform.cpp:690
AESGCMGMAC_Transform.cpp:1068
AESGCMGMAC_Transform.cpp:1071
AESGCMGMAC_Transform.cpp:1248
AESGCMGMAC_Transform.cpp:1251
AESGCMGMAC_Transform.cpp:1404
AESGCMGMAC_Transform.cpp:1407
AESGCMGMAC_Transform.cpp:2141

**Comment by MiguelCompany** [comment]
This should have been fixed by #1193 

@jacobperron Could you please check and close if appropriate?

**Comment by jacobperron** [comment]
@MiguelCompany thanks, I haven't seen the warnings in any recent builds.
