### ISSUE TITLE
allow participant to inspect remote user publications/subscriptions

### ISSUE THREAD

**Issue by liamstask** [eProsima/Fast-RTPS#12]
Is there an api that allows this? I have only found an api to be notified when a subscription is matched, but would like to be able to inspect the list of user (and possibly builtin) topics that are visible to a participant without the requirement of subscribing to them in advance.

I see these are processed in `EDPSimplePUBListener::onNewCacheChangeAdded()` and `EDPSimpleSUBListener::onNewCacheChangeAdded()` but don't appear to be passed through, external to Fast-RTPS.

Would you be interested in a PR that introduces this functionality?

**Comment by richiprosima** [comment]
Since this commit @c05b251 we have this functionality. It is being used on [ROS2](https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/tree/remaining_functionality).

**Comment by SantiagoMunoz** [comment]
You can do this by writing your own callback method and attaching it to the built-in protocols.

Lets say you implement a callback to inspect topic names and types like the one we use in ROS2:

```cpp
class CustomReaderListener : public ReaderListener {
	public:
	topicnamesandtypesReaderListener(){};
	void onNewCacheChangeAdded(RTPSReader* reader, const CacheChange_t* const change_in){
		CacheChange_t* change = (CacheChange_t*) change_in;
		if(change->kind == ALIVE){
			WriterProxyData proxyData;
			CDRMessage_t tempMsg;
			tempMsg.msg_endian = change->serializedPayload.encapsulation == PL_CDR_BE ? BIGEND:LITTLEEND;
			tempMsg.length = change->serializedPayload.length;
			memcpy(tempMsg.buffer,change->serializedPayload.data,tempMsg.length);
			if(proxyData.readFromCDRMessage(&tempMsg)){
				mapmutex.lock();
				topicNtypes[proxyData.topicName()].insert(proxyData.typeName());		
				mapmutex.unlock();
			}
		}
	}
	std::map<std::string,std::set<std::string>> topicNtypes;
	std::mutex mapmutex;
};
```

You can attach this listener to your participant on run-time:

```cpp
CustomReaderListener *my_readerListenerSub = new(CustomReaderListener); // Custom user ReaderListeners
CustomReaderListener *my_readerListenerPub = new(CustomReaderListener); 
std::pair<StatefulReader*,StatefulReader*> EDPReaders = my_participant->getEDPReaders(); //Get access to the EDP endpoints
EDPReaders.first()->setListener(my_readerListenerSub);  // Perform attachments
EDPReaders.second()->setListener(my_readerListenerPub);
```
