### ISSUE TITLE
Implement PERSISTENT durability

### ISSUE THREAD

**Issue by clalancette** [eProsima/Fast-RTPS#120]
From what I can tell in Fast-RTPS master, PERSISTENT durability isn't yet implemented.  This causes problems, for instance, in something like ros2/geometry2#12, where we have to constantly loop to make sure that the data is always available.  It would be much better if we could use the persistent durability QoS setting.

**Comment by dirk-thomas** [comment]
We don't need `persistent` durability to implement the referenced feature. Therefore I would suggest to close this feature request.

**Comment by richiware** [comment]
As suggested @dirk-thomas , we will close this issue. PERSISTENT durability will be implemented in the future, but isn't scheduled yet. Thanks
