### ISSUE TITLE
Send big data, subscriber not responses [8367]

### ISSUE THREAD

**Issue by EgalYue** [eProsima/Fast-RTPS#1205]
### **Expected Behavior**
I want to send big data(maybe 1 ~ 2 MB) using fastrtps.  
I followed the example code from https://github.com/eProsima/Fast-RTPS/tree/master/examples/C%2B%2B/HelloWorldExample and defined a simple vector message `VecMsg.idl` :
```
struct VecMsg
{   
    unsigned long index;
    sequence<octet> data;
};

```

### **Current Behavior**
If the size of vector larger than 128 (https://github.com/EgalYue/send_big_data_test/blob/d33ee5d7bec3c799108d932af13405f01c2d9a67/VecMsgPublisher.cxx#L44), the subscriber can not receive the message.

I already set  `Wparam.qos.m_publishMode.kind = ASYNCHRONOUS_PUBLISH_MODE;`

### **Steps to Reproduce**

The link of my test code: 
https://github.com/EgalYue/send_big_data_test

### **System information**

- Fast-RTPS version: 1.10.x branch
- OS: Ubuntu 18.04
- Network: Speed: 1000Mb/s Duplex: Full
- Buffer size : sysctl -w net.core.rmem_max = 212992
                      sysctl -w net.core.wmem_max = 212992
                      sysctl -w net.core.rmem_default = 212992
                      sysctl -w net.core.wmem_default = 212992

Im not sure, do I still need to set some options for big data?  

Please let me know if you need any additional information.

**Comment by adolfomarver** [comment]
@EgalYue In order to assure the subscriber is able to receive full samples, you should set-up  `receiveBufferSize` at least to the size of the sample (2MB in your case). This can be set in the participant's transport attributes:

[FastRTPS Transport Documentation](https://fast-rtps.docs.eprosima.com/en/latest/advanced.html#transports)

You should also increase your `net.core.rmem_default` and `net.core.rmem_max` at least to the same size, to assure OS allows that UDP buffer allocation.

**Comment by MiguelCompany** [comment]
@EgalYue Additionally to what @adolfomarver said, the main issue you are having is that your data is unbounded. 

The default behavior of Fast-RTPS is to preallocate data. The preallocated size is taken from `DataType::getMaxCdrSerializedSize`. When there is an unbounded sequence, the generated code assumes 100 elements on that method. See the [generated code on your test](https://github.com/EgalYue/send_big_data_test/blob/d33ee5d7bec3c799108d932af13405f01c2d9a67/VecMsg.cxx#L80). You can either change that method to accommodate your real maximum size or change the [memory policy](https://fast-rtps.docs.eprosima.com/en/latest/xmlprofiles.html#history-memory-policy-configuration) of your history to a dynamic value like `PREALLOCATED_WITH_REALLOC`

**Comment by EgalYue** [comment]
@MiguelCompany @adolfomarver Thanks so much, i modified the preallocated size from `DataType::getMaxCdrSerializedSize` and it works now. Thanks!
I will close this one.
