### ISSUE TITLE
Question: How to customize transport source port of publishers?

### ISSUE THREAD

**Issue by anamud** [eProsima/Fast-RTPS#1208]
Assume a participant P with two publishers A and B. Is it possible to customize the transport ports that the publish from (source port)? For example, port 59001 for A and 59002 for B.

I am using FastRTPS 2.0. I see that all publishers of a participant publish from the same transport source port, which I assume corresponds to a random port assigned by the OS.

**Comment by MiguelCompany** [comment]
You cannot assign a custom output port for each publisher, but you can customize the output port for the whole participant, by using a custom [transport descriptor](https://fast-rtps.docs.eprosima.com/en/latest/advanced.html#transports). You can use field `m_output_udp_socket` if you are using code (`output_port` on XML)

**Comment by anamud** [comment]
Thanks for a useful and fast response! Now I understand that I can create one publisher per participant and customize the transport descriptor  `output_port` for each participant.
