### ISSUE TITLE
Question: Publisher distinction at transport level

### ISSUE THREAD

**Issue by anamud** [eProsima/Fast-RTPS#1212]
Assume a participant with publishers A and B. At the transport level, both these publishers publish from the same port (UDP socket source) and IP address. For example, 192.168.10.1:59001.

Is there any indication in the transport packets of publishers A and B that enables differentiation? In other words, if I examine a UDP or IP packet in 192.168.10.1:59001, can I understand if it came from publisher A or B?

Perhaps this is possible by using publisher-unique transport_priority QoS settings, but I am unsure if transport_priority is visible in a UDP or IP packet in the diffserv field.

**Comment by MiguelCompany** [comment]
The [RTPS protocol](https://www.omg.org/spec/DDSI-RTPS/About-DDSI-RTPS) specifies how this is done. On the same UDP datagram, the protocol allows to have messages from different publishers (writers in the nomenclature of RTPS). It even allows to have messages from different participants. Writers on the same participant are identified by field writerEntityId. Participants are identified by guidPrefix.

**Comment by anamud** [comment]
Thanks! This is relevant and useful. I will go ahead and programmatically index into RTPS message IDs (writerIds, guidPrefixes etc) in packets captured using packet inspection libraries (libpcap or libtins).
