### ISSUE TITLE
Fail to send a large(?) message

### ISSUE THREAD

**Issue by pedro1713** [eProsima/Fast-RTPS#1225]
I'm trying to send a message with a type generated from the following IDL
`
#include Point.idl"

struct Path {
	sequence<Point> points;
	};
`
Where Point.idl is as follows
`
struct Point {
	double x;
	double y;
	double z;
	};
`
I can send Path messages containing up to 100 points. But anything above that fails. Not sure if on sender or receiver side. 

My publisher has the following parameters
`
    PublisherAttributes Pathparam;
    Pathparam.qos.m_publishMode.kind = ASYNCHRONOUS_PUBLISH_MODE;
    Pathparam.historyMemoryPolicy = rtps::PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
    Pathparam.topic.topicKind = NO_KEY;
    Pathparam.topic.topicDataType = PathType.getName();  //This type MUST be registered
    ThroughputControllerDescriptor lowBandWidhtController{300000, 1000};
`
On the subscriber side my participant is set with the following attributes
`
    ParticipantAttributes PParam;
    PParam.rtps.setName("ROS_Subscriber"); //You can put the name you want
    PParam.rtps.sendSocketBufferSize = 1048576;
    PParam.rtps.listenSocketBufferSize = 4194304;
    PParam.rtps.builtin.writerHistoryMemoryPolicy = PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
    PParam.rtps.builtin.readerHistoryMemoryPolicy = PREALLOCATED_WITH_REALLOC_MEMORY_MODE
`
As stated before, if my Path has less than a 100 points I can send and receive with no issue, but more than a 100 fails. I believe my configuration is adequate to sending large files, which a longer Path may qualify as. But even after setting asynchronous publish mode and realloc memory mode, nothing changed.
I have tested my code in 1.8.3 and 1.10.0 on Ubuntu 18.04.
Any guidance would be appreciated.

**Comment by MiguelCompany** [comment]
@pedro1713 You should also set `historyMemoryPolicy = rtps::PREALLOCATED_WITH_REALLOC_MEMORY_MODE` on the `SubscriberAttributes`

**Comment by pedro1713** [comment]
Hi Miguel
I added the suggested line the `SubscriberAttributes`, and I can now transmit larger messages.
Only one more question before closing the issue. The documentation only mentions `qos.m_publishMode.kind = ASYNCHRONOUS_PUBLISH_MODE;` on the publisher to send large data. 
If the line you suggested is required both on publisher and subscriber to send large data, shouldn't this be mentioned on the documentation in (https://fast-rtps.docs.eprosima.com/en/latest/advanced.html#example-sending-a-unique-large-file) ?
If it isn't normally required? Why was it needed in my case?
Thanks a lot.

**Comment by EduPonz** [comment]
Hi @pedro1713 , we are currently in the process of updating our documentation to provide thorougher explanations, more examples, more use-cases, etc. We will make sure these type of cases are better reflected. Thanks for pointing it out!

**Comment by MiguelCompany** [comment]
@pedro1713 The configuration of `PREALLOCATED_WITH_REALLOC_MEMORY_MODE` is necessary for unbounded types. It doesn't matter if they are large or small. I have recently explained it on [this comment](https://github.com/eProsima/Fast-RTPS/issues/1205#issuecomment-626489994)

So if you have a data type with a `char [10 * 1024 * 1024]` field, you will not need to change the `historyMemoryPolicy` attribute, as the size is known beforehand.

**Comment by pedro1713** [comment]
Thanks for the clarification, it will be useful as we continue developing our application.
