### ISSUE TITLE
High rate ReliabilityKind_t::RELIABLE messages invariably end in a sigsegv

### ISSUE THREAD

**Issue by cvilas** [eProsima/Fast-RTPS#125]
While sending messages between RTPSWriter and **multiple** RTPSReader using RELIABLE communication at a high data rate, the writer invariably terminates with a segfault. I have been able to reproduce this issue by slightly modifying the RTPSTest_registered C++ example, which is attached with this report. The stack trace when this happens is as follows:
`
Caught signal 11 (SIGSEGV)
stack trace:
  libfastrtps.so.1 ( eprosima::fastrtps::rtps::MessageReceiver::proc_Submsg_Acknack(eprosima::fastrtps::rtps::CDRMessage_t*, eprosima::fastrtps::rtps::SubmessageHeader_t*, bool*)  + 0xb78 )  [0x7f21e7770fe8]
  libfastrtps.so.1 ( eprosima::fastrtps::rtps::MessageReceiver::processCDRMsg(eprosima::fastrtps::rtps::GuidPrefix_t const&, eprosima::fastrtps::rtps::Locator_t*, eprosima::fastrtps::rtps::CDRMessage_t*)  + 0x100d)  [0x7f21e777b0ad]
  libfastrtps.so.1 ( eprosima::fastrtps::rtps::RTPSParticipantImpl::performListenOperation(eprosima::fastrtps::rtps::ReceiverControlBlock*, eprosima::fastrtps::rtps::Locator_t)  + 0xab  )  [0x7f21e7780d7b]
  libfastrtps.so.1 ( std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (eprosima::fastrtps::rtps::RTPSParticipantImpl::*)(eprosima::fastrtps::rtps::ReceiverControlBlock*, eprosima::fastrtps::rtps::Locator_t)> (eprosima::fastrtps::rtps::RTPSParticipantImpl*, eprosima::fastrtps::rtps::ReceiverControlBlock*, eprosima::fastrtps::rtps::Locator_t)> >::_M_run()  + 0x58  )  [0x7f21e778a1e8]
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (                                           + 0xb8c80)  [0x7f21e71bec80]
  /lib/x86_64-linux-gnu/libpthread.so.0 (                                           + 0x76ba)  [0x7f21e748f6ba]
  /lib/x86_64-linux-gnu/libc.so.6 ( clone                                     + 0x6d  )  [0x7f21e6c2d3dd]
`
I realise the RELIABLE option is not meant for high rate messaging, but I do have the above issue intermittently even if the messages are transmitted at about 1 hz. To reproduce the problem, please compile the attached modified example and test with multiple readers and one writer.

[RTPSTest_registered.zip](https://github.com/eProsima/Fast-RTPS/files/1196632/RTPSTest_registered.zip)

**Comment by richiware** [comment]
Thanks for the reporting and the detailed info. We will work on it.

**Comment by cvilas** [comment]
Hi Ricardo

- Just tried with the latest master branch. I can confirm the problem still exists
- I used three readers to reproduce the problem just now. 
- I am running all the apps on the same machine.

thanks
Vilas

**Comment by cvilas** [comment]
Also, you have a better change of reproducing the error if you start the writer first, then all the readers.

**Comment by richiware** [comment]
I've found the problem. This example uses the low RTPS layer. Using this layer user has to do things in manual way as registers the local reader (to be accessible at discovery time). When you create the reader you set it as reliable. But when you register the reader that is not set.

*TestReaderRegistered.cpp* diff:
```diff
82d81
<     Rqos.m_reliability.kind = RELIABLE_RELIABILITY_QOS;
```
Commit 698ae3a7372db1903e5ff228e5a9cf6d79ea1894 fixes the segmentation fault in case discovery says the reader is best effort but it is reliable.

Thanks for your help.

**Comment by cvilas** [comment]
Thanks very much for the fix. I wouldn't have thought to specify reliability twice! 
Cheers!

**Comment by richiware** [comment]
Pub/sub layer is more friendly. Thanks again.
