### ISSUE TITLE
Reader cannot match writer error

### ISSUE THREAD

**Issue by dhood** [eProsima/Fast-RTPS#128]
Occasionally we get the following error when running ROS 2 tests repeatedly:

```
Writer 1.f.0.2.46.50.0.0.0.0.0.0|0.0.2.3 cannot match reader 1.f.0.2.45.50.0.0.0.0.0.0|0.0.2.4
```
or
```
Reader 1.f.0.2.a1.6f.0.0.0.0.0.0|0.0.2.4 cannot match writer 1.f.0.2.a0.6f.0.0.0.0.0.0|0.0.3.3
```

Example 1: http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/736/testReport/junit/(root)/projectroot/test_showimage_cam2image__rmw_fastrtps_cpp/
Example 2: http://ci.ros2.org/view/nightly/job/nightly_osx_repeated/772/testReport/(root)/projectroot/test_tutorial_add_two_ints_server_add_two_ints_client_async__rmw_fastrtps_cpp/
Example 3: http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/725/testReport/(root)/projectroot/test_tutorial_add_two_ints_server_add_two_ints_client__rmw_fastrtps_cpp/

Is there anything we can do to prevent this from occurring?

**Comment by dhood** [comment]
We are still interested in knowing if it's safe to ignore this error or if we should be making changes to our system to prevent it from occurring

**Comment by richiware** [comment]
Commit 398e0b68592d2ee8fd54fef19667f174f54674a1 removes those messages. There is no error in your case. It shows the reader/writer has been already matched.

**Comment by dhood** [comment]
thanks @richiware
