### ISSUE TITLE
possible to detect remote peers that are no longer active?

### ISSUE THREAD

**Issue by liamstask** [eProsima/Fast-RTPS#13]
after building some tests based on the `HelloWorld` examples included in the Fast-RTPS distribution, I see that when I cleanly exit a process and let all the destructors run, the appropriate `onPublicationMatched()` callbacks are invoked for the `PublisherListener` whose remote peer has shut down.

however, if I simply terminate the process (ctrl-c), the publisher never gets notified that the subscriber is no longer listening.

is there a recommended approach to address this?

**Comment by johnfinley** [comment]
https://github.com/eProsima/Fast-RTPS/issues/35 might be related.

**Comment by richiware** [comment]
Also there is a [test](https://github.com/eProsima/Fast-RTPS/blob/master/test/communication/CMakeLists.txt#L56) that checks this behaviour. I will close this issue. If you continue having problems, you can reopen it.
