### ISSUE TITLE
Feature: create .deb package and submit it to inclusion 

### ISSUE THREAD

**Issue by TSC21** [eProsima/Fast-RTPS#131]
Any plans to create a Fast-RTPS deb package and submit it to be included on OS's package lists?

**Comment by TSC21** [comment]
I believe the same would be useful for fast-CDR. That would help on integrating both packages into `rosdep`.

**Comment by TSC21** [comment]
@LorenzMeier, @bkueng FYI

**Comment by mikaelarguedas** [comment]
@TSC21 If it's of any help, ROS 2 [provides debs](http://repo.ros2.org/ubuntu/main/pool/main/r/) for both fastcdr and fastrtps. Though it doesn't address this issue given that there was no initiative to get these released into upstream ubuntu and thus to add them to the rosdep database. But it should allow you to install these debs, find them through CMake and build ros packages on top without having to build them from source.

**Comment by TSC21** [comment]
> Though it doesn't address this issue given that there was no initiative to get these released into upstream ubuntu and thus to add them to the rosdep database.

That is the problem. There is a need of these packages on other tools and even on ROS1 direct integration.

**Comment by mikaelarguedas** [comment]
>  There is a need of these packages on other tools and even on ROS1 direct integration

Agreed

How users usually do it is that they submit their package for integration into debian (ubuntu will sync on the current state of debian for each new ubuntu distribution) and release the package as a ROS package for any ubuntu distribution before the one that will actually provide the package. Then rosdep will work for both cases given that it looks for released ros packages and then for rosdep rules for the specific OS.

**Comment by TSC21** [comment]
> How users usually do it is that they submit their package for integration into debian

I was hopping someone from the fast-RTPS team would do that. The `rosdep` PR I can do it.

**Comment by JaimeMartin** [comment]
@TSC21 

We are evaluating this for future releases.

**Comment by TSC21** [comment]
Thank you @JaimeMartin
