### ISSUE TITLE
Question: Is there any java implementation planned?

### ISSUE THREAD

**Issue by ecmnet** [eProsima/Fast-RTPS#137]

**Comment by JaimeMartin** [comment]
@ecmnet 

We have an implementation in Java called [KIARA](http://www.eprosima.com/index.php/products-all/r-d-projects/kiara-fiware-advanced-middleware), but this implementation is not so used an maintained and lacks many features of Fast RTPS. Please take a look.

As another option, what you can always do is call Fast RTPS through JNI.

**Comment by jabrena** [comment]
Take a look thus repo: 
https://github.com/esteve/ros2_java
@esteve could help you.

Cheers
