### ISSUE TITLE
Feature: Allow end-user application XML config files to include non-FastRTPS settings

### ISSUE THREAD

**Issue by wtsnyder** [eProsima/Fast-RTPS#138]
It would be useful in some applications to include settings meant for other parts of the code in the same XML config containing the FastRTPS settings so the application only has one configuration file. This is possible with the current implementation but the loadXMLFile routine expects the ```<profiles>``` tag to be the root tag of the XML document.  Other settings can be dumped inside that tag but FastRTPS will warn about unexpected tags in its configuration.

I propose that if the ```<profiles>``` tag is not the root tag, it is searched for as a first level child.  This would allow for the inclusion of FastRTPS configuration alongside user settings with XML files like:
```xml
<?xml version="1.0"?>

<any-root-tag>

    <user-application-configs>
        <setting>7</setting>
    </user-application-configs>

    <profiles>
        <!--FastRTPS configs -->

        <participant profile_name="application">
            <!--Participant details -->
        </participant>

        <publisher profile_name="raw_rx">
            <!--Publisher details -->
        </publisher>
    </profiles>
</any-root-tag>
```

While this is not endlessly flexible, it does allow FastRTPS to play nicely with other content in XML files with the restriction that ```<profiles>``` be a top level child tag.

I could also understand the philosophy of keeping FastRTPS configs separate and expecting any other settings to be in a different file but a single file would be a cleaner solution in our current use case.

**Comment by richiware** [comment]
Currently we don't want to change our XML format because there are users using it. In the future we will change to OMG XML specification. Meanwhile you can use two XML files. Sorry for the inconveniences.
