### ISSUE TITLE
Auto discovery not working between Ubuntu machines

### ISSUE THREAD

**Issue by Apoorv-Goyal** [eProsima/Fast-RTPS#143]
I am using FASTRTPS version 1.5.0.

Using HelloWorld example - i want to setup publisher & subscriber on 2 different ubuntu(14.04) machines. After running publisher & subscriber on separate machines - they can't exchange messages.

Note - No change done in example code.

**Comment by richiware** [comment]
Can you provide us  a Wireshark capture of the communications?

**Comment by Apoorv-Goyal** [comment]
Hi,

Please find attached wireshark logs for Publisher & subscriber - running on 2 different Ubuntu machines.

thanks
Apoorv
________________________________

**Comment by richiware** [comment]
Where can I find the attached file? Replying the github's email didn't send me the attached file. I think you can attach it through this issue's webpage. Thanks

**Comment by Apoorv-Goyal** [comment]
Logs attached for publisher & subscriber

**Comment by Apoorv-Goyal** [comment]
file:///home/apgoyal/qnx660/issues/fastrtps_linux_issue/FASTRTPS_pubisher.cap
file:///home/apgoyal/qnx660/issues/fastrtps_linux_issue/FASTRTPS_subscriber.cap

**Comment by Apoorv-Goyal** [comment]
[FASTRTPS_pubisher.zip](https://github.com/eProsima/Fast-RTPS/files/1325400/FASTRTPS_pubisher.zip)
[FASTRTPS_subscriber.zip](https://github.com/eProsima/Fast-RTPS/files/1325402/FASTRTPS_subscriber.zip)

**Comment by richiware** [comment]
According to the capture files, both machines aren't in same local network. Default UDPv4 transport set TTL to 1. You can disable the default transport and set your own.

```c++
auto customTransport = std::make_shared<UDPv4TransportDescriptor>();
customTransport->TTL = 25;

pattr.userTransports.push_back(customTransport);
pattr.useBuiltinTransports = false;
my_participant = RTPSDomain::createParticipant(pattr);
```

**Comment by richiware** [comment]
Any news? Does it works in your network environment?

**Comment by Apoorv-Goyal** [comment]
Modifying TTL value works in my environment.
Thanks for help.

**Comment by apoorvnitw** [comment]
I am trying to use Fast-RTPS on QNX. 
There are 2 machines 1 & 2.
After adding TTL value = 25, it works only when Machine 1 starts publisher/subscriber first. After this running subscriber/publisher on Machine 2 works fine.

In other scenario if Machine 2 starts publisher/subscriber first, and then on Machine 1 -> no communication in this scenario.

Attaching tcpdump for both scenario.

**Comment by apoorvnitw** [comment]
[Publisher_working.pcap.zip](https://github.com/eProsima/Fast-RTPS/files/1414914/Publisher_working.pcap.zip)
[Subscriber_working.pcap.zip](https://github.com/eProsima/Fast-RTPS/files/1414915/Subscriber_working.pcap.zip)

[Publisher_not_working.pcap.zip](https://github.com/eProsima/Fast-RTPS/files/1414909/Publisher_not_working.pcap.zip)
[Subscriber_not_working.pcap.zip](https://github.com/eProsima/Fast-RTPS/files/1414910/Subscriber_not_working.pcap.zip)

**Comment by Apoorv-Goyal** [comment]
Hello,

I am trying to use Fast-RTPS on QNX.
There are 2 machines 1 & 2.
After adding TTL value = 25, it works only when Machine 1 starts publisher/subscriber first. After this running subscriber/publisher on Machine 2 works fine.
In other scenario if Machine 2 starts publisher/subscriber first, and then on Machine 1 -> no communication in this scenario.
tcpdump for both scenarios attached with issue - 143.
Can you have a quick look.

thanks
apoorv
________________________________

**Comment by darbee** [comment]
> I am trying to use Fast-RTPS on QNX.
> There are 2 machines 1 & 2.
> After adding TTL value = 25, it works only when Machine 1 starts publisher/subscriber first. After this running subscriber/publisher on Machine 2 works fine.
> 
> In other scenario if Machine 2 starts publisher/subscriber first, and then on Machine 1 -> no communication in this scenario.
> 
> Attaching tcpdump for both scenario.

Hi, I wonder how can you install Fast-RTPS on qnx. Can you give me some instructions? thanks a lot
