### ISSUE TITLE
XMLProfile for multicastLocatorList doesn't support address even though it's in docs

### ISSUE THREAD

**Issue by deng02** [eProsima/Fast-RTPS#145]
So I was attempting to configure the multicast locator addresses to use something other than 'any' because we need the locators to bind to a specific interface. I thought I could do so using XML Profiles as it is detailed in the online documents: http://docs.eprosima.com/en/latest/pubsub.html#publisher-and-subscriber-configuration (under Multicast locators).

However when I tried to use an XML profile with the suggested tags I got the following:
`[XMLPROFILEPARSER Error] Tag 'address' do not supported for now -> Function getXMLLocatorList`

and it turns out that it's actually marked as commented out: 
https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/xmlparser/XMLProfileElementParser.cpp#L1290

Is there reason why this is disabled?  Is it possible to get it enabled? If it's as simple as uncommenting the code I can submit a PR.  If it's not so simple, I would recommend removing this from the documentation.

**Comment by richiware** [comment]
Commit 1cfb2301f578fd4eec62f320050770095f220beb fixes it. Thanks for the reporting.

**Comment by deng02** [comment]
Thanks for the quick response, that worked!
