### ISSUE TITLE
Dynamic allocation fails.

### ISSUE THREAD

**Issue by isaacnoble** [eProsima/Fast-RTPS#147]
Strings longer than ~251 characters fail to serialize. Tracking this down, this is related to the 255 max size in the idl generated `getMaxCdrSerializedSize`.

When switching to DYNAMIC_RESERVE_MEMORY_MODE, the `getCdrSerializedSize` only accounts for the fields directly in the idl (plus alignment). Encapsulation space does not seem to be accounted for, as added in `Cdr::serialize_encapsulation`. 

Here is a minimum viable change to the HelloWorldExample that shows the failure (tag: v1.5.0):
```
index f96112e..56f7234 100644
--- a/examples/C++/HelloWorldExample/HelloWorldPublisher.cpp
+++ b/examples/C++/HelloWorldExample/HelloWorldPublisher.cpp
@@ -36,7 +36,7 @@ mp_publisher(nullptr)
 bool HelloWorldPublisher::init()
 {
     m_Hello.index(0);
-    m_Hello.message("HelloWorld");
+    m_Hello.message(std::string(512,'a'));
     ParticipantAttributes PParam;
     PParam.rtps.defaultSendPort = 11511;
     PParam.rtps.use_IP6_to_send = true;
@@ -61,6 +61,7 @@ bool HelloWorldPublisher::init()
     Wparam.topic.topicDataType = "HelloWorld";
     Wparam.topic.topicName = "HelloWorldTopic";
     Wparam.topic.historyQos.kind = KEEP_LAST_HISTORY_QOS;
+    Wparam.historyMemoryPolicy = DYNAMIC_RESERVE_MEMORY_MODE;
     Wparam.topic.historyQos.depth = 30;
     Wparam.topic.resourceLimitsQos.max_samples = 50;
     Wparam.topic.resourceLimitsQos.allocated_samples = 20;
```

**Comment by isaacnoble** [comment]
Following up, I noticed that inside the generated code for getSerializedSizeProvider encapsulation is accounted for by adding +4.

The error is still encountered during serialization, but now the extra bytes are a mystery.

**Comment by richiware** [comment]
In the past ``fastrtpsgen`` generated source code with exceptions when maximum length is exceeded. As now Fast RTPS uses others memory policy in addition preallocated memory, this limitations were removed. But it seems HelloWorld example was not updated. Commit b54682c29a380f3de49e03a769fae0f17044da81 fixed it.

**Comment by richiware** [comment]
That memory policy supports large allocations. I still checked with HelloWorldExample after the change.

**Comment by lshamis** [comment]
I'm not sure I understand. In the HelloWorldExample, can you successfully send large messages by setting `historyMemoryPolicy = DYNAMIC_RESERVE_MEMORY_MODE`?
I cannot.

**Comment by isaacnoble** [comment]
My expectation is that setting `historyMemoryPolicy = DYNAMIC_RESERVE_MEMORY_MODE` would allow for sending messages over 251 characters.

Yet when I run the HelloWorldExample with the `DYNAMIC_RESERVE_MEMORY_MODE` memory policy and a message of length 512, as in my diff above, I get the following exception:

`Starting 
Publisher matched
terminate called after throwing an instance of 'eprosima::fastcdr::exception::BadParamException'
  what():  message field exceeds the maximum length
Aborted (core dumped)`

Given this exception what other changes do I need to make to send a message over 251 characters?

**Comment by isaacnoble** [comment]
My git was mistakenly reporting up-to-date. After a fresh clone the example above is working.

**Comment by richiware** [comment]
I'm glad to hear that. I will close the issue. If you have some trouble, you can reopen it.
