### ISSUE TITLE
[Security] Participants not matched since 3954916f2902e885ec0360d34fc06a99391b4252 has been merged

### ISSUE THREAD

**Issue by mikaelarguedas** [eProsima/Fast-RTPS#149]
All the ROS 2 security tests started failing 5 days ago. After some digging it looks like if I revert only https://github.com/eProsima/Fast-RTPS/commit/3954916f2902e885ec0360d34fc06a99391b4252, things start working as before.

The current behavior of master:
- If the subscriber starts first:

error message on pairing when publisher shows up:
`[RTPS_EDP Error] Security manager returns an error for writer 9a.dd.34.40.e7.49.50.82.23.bf.61.1a|0.0.1.3 -> Function pairingWriter`, after the error message is displayed the participants are matched and can exchange encrypted data

- if the publisher starts first:

The participants are never matched and the publisher hangs without responding to SIGINT

**Comment by richiware** [comment]
I changed the "matching" behaviour when the datawriter and datareader use security. Our tests passed after this change but something is happening. I will check your tests to find the problem. Thanks for the reporting.

**Comment by dhood** [comment]
thanks for the quick fix @richiprosima . Would you please address the two warnings that https://github.com/eProsima/Fast-RTPS/commit/3f238281c5e856e767edf42b5f3037d8edd1a34a introduced? http://ci.ros2.org/job/ci_windows/3319/warnings41Result/new/

**Comment by richiware** [comment]
Commit 70a41d4d315f7ffa978868a9fcdf38b7b6b5f247 fixes them. Thanks @dhood
