### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by isaacnoble** [eProsima/Fast-RTPS#151]
I am attempting to use the Reader/Writer layer and I am following the documentation [here](http://docs.eprosima.com/en/latest/rtps.html#configuring-readers-and-writers).

Specifically when trying to send data the documentation gives this snippet:
```
//Request a change from the history
CacheChange_t* ch = writer->newCacheChange(ALIVE);
//Write serialized data into the change
ch->serializedPayload->length = sprintf(ch->serializedPayload->data, "My String %d", 2);
//Insert change back into the history. The Writer takes care of the rest.
history->add_change(ch);
```

But searching the code base, the function `newCacheChange` is not found.

Writers to have a `new_change` function, but it takes very different arguments and there does not appear to be any documentation on how this function should be used to send data.

**Comment by MiguelCompany** [comment]
Writers now have a `new_change` method that receive a callback function returning the estimated maximum number of bytes of the payload data. 

You can find updated documentation [here](http://eprosima-fast-rtps.readthedocs.io/en/latest/rtps.html#using-the-history-to-send-and-receive-data)
