### ISSUE TITLE
Config to enable communication within same machine OR specified IPs

### ISSUE THREAD

**Issue by Apoorv-Goyal** [eProsima/Fast-RTPS#154]
We are trying FASTRTPS on our embedded systems. We want publisher/subscriber should work with-in same machines ONLY OR to specified IPs. We can see that with Helloworld example, targets can talk to each other. I tried below config to specify IPs manually. It works OK between targets but doesn't work within same target-

        //Uni-cast config
        //Disable multi-cast
        Locator_t default_unicast_locator;
        PParam.rtps.builtin.metatrafficUnicastLocatorList.push_back(default_unicast_locator);
        //Add known Peers IPs
        std::vector<Locator_t>::iterator initial_peer;
        for(initial_peer = peerlist.begin(); initial_peer != peerlist.end(); ++initial_peer)
        {
                PParam.rtps.builtin.initialPeersList.push_back(*initial_peer);
        }

Can you suggest config to work within a same machine & specified IPs only

**Comment by richiware** [comment]
they are localhost interface (127.0.0.1) or local machine ip in your list of peers?

**Comment by Apoorv-Goyal** [comment]
I tried both 127.0.0.1 & local machine IP in peer list. They don't seem to work. Only different target IP works after adding into peer list.

**Comment by richiware** [comment]
Are you setting the ports? When you do:
```c++
Locator_t default_unicast_locator;
PParam.rtps.builtin.metatrafficUnicastLocatorList.push_back(default_unicast_locator);
```
you aren't setting the port. The participant will calculate automatically the port where it will be listening. As you are setting the locators for discovering, the remote participant must know which port it should send the data to. And this is done setting the port in the initial peer.

An example:
```c++
/* PARTICIPANT 1*/
Locator_t loc_initial_peer, loc_default_unicast;
LocatorList_t initial_peers, default_unicast_locator;

loc_initial_peer.set_IP4_address(127, 0, 0, 1);
loc_initial_peer.port = 7610;
PParam.rtps.builtin.initialPeersList.push_back(loc_initial_peer);

default_unicast.port = 7410;
PParam.rtps.builtin.metatrafficUnicastLocatorList.push_back(loc_default_unicast);

```

```c++
/* PARTICIPANT 2*/
Locator_t loc_initial_peer, loc_default_unicast;
LocatorList_t initial_peers, default_unicast_locator;

loc_initial_peer.set_IP4_address(127, 0, 0, 1);
loc_initial_peer.port = 7410;
PParam.rtps.builtin.initialPeersList.push_back(loc_initial_peer);

default_unicast.port = 7610;
PParam.rtps.builtin.metatrafficUnicastLocatorList.push_back(loc_default_unicast);

```

**Comment by richiware** [comment]
@Apoorv-Goyal Did it work for you?

**Comment by sagniknitr** [comment]
Hi @richiware , thanks for this solution. I was having the same problem and this works fine.

**Comment by richiware** [comment]
I'm glad to hear that. I close the issue.
