### ISSUE TITLE
Endpoint re-discovery can fail with un-equal lease times 

### ISSUE THREAD

**Issue by wtsnyder** [eProsima/Fast-RTPS#155]
Re-transmission of endpoint discovery information (DATA(r) and DATA(w) sub-messages in wireshark) on participant re-connects will not occur if the re-connect occurs during the time between the end of the shorter participant lease time and the end of the longer participant lease time.  Because the re-connection causes the participants to resume providing their heartbeat, it appears to one participant that the connection was never lost so the endpoint connections will never recover unless disconnected for the entirety of the longer of the two lease periods.

![image](https://user-images.githubusercontent.com/28737065/31288269-30731e7c-aa92-11e7-851d-0ad368fe5a0f.png)

## Reproduction
Create a publisher participant with a lease time of 60 seconds and a subscriber with a lease time of 10 seconds.  Select appropriate announce periods for each. Run the participants on to separate machines, watch data flow.  Disconnect network cable for 30 seconds then re-connect.  Participants will re-discover each-other within one announce period but EDP information will not be exchanged, no data will flow.  Disconnect network cable for 90 seconds then re-connect.  Participants will re-discover each-other and exchange EDP information, data will flow.

## Workaround
This issue is highly unlikely and potentially impossible to reproduce when all participants have matching lease times.

## Solution
Both local and remote participant lease times must be considered when deciding to send endpoint discovery data on a re-connect.

**Comment by richiware** [comment]
Commit 001cf92fb63d4345763bbd709ed386b0d40cabd9 fixes this. Thanks for reporting. If you continue having problems, be free reopening the issue.
