### ISSUE TITLE
Issue in running secure example

### ISSUE THREAD

**Issue by Apoorv-Goyal** [eProsima/Fast-RTPS#156]
With latest 1.5, i am seeing below errors on running secure examples-
./SecureHelloWorldExample publisher
Starting 
[SECURITY Error] Error validating the local participant -> Function init
[PARTICIPANT Error] Problem creating associated Writer -> Function createPublisher

Compile is OK with SECURITY=ON.
Am i missing something here?

**Comment by richiware** [comment]
Are you using OpenSSL 1.1.0?

**Comment by richiware** [comment]
Commit a1c2a09153cf06292a94c3887e3e831b9fc1d054 changes the certificate files of the example. This new ones also work with OpenSSL 1.1.0.

**Comment by Apoorv-Goyal** [comment]
yes, i am using v 1.1.0
New update fixes the issues.

Now i see there is data loss. After running SecureHelloworld example, i see sometimes just 7 or 4 packets received out of 10.

**Comment by richiware** [comment]
Can you provide a Wireshark capture?

**Comment by MiguelCompany** [comment]
@Apoorv-Goyal Performance and security have been improved on [1.6.0](https://github.com/eProsima/Fast-RTPS/tree/v1.6.0)

Could you test again and tell us if your issue has been solved ?

**Comment by MiguelCompany** [comment]
@Apoorv-Goyal Closing this now. Feel free to reopen it if still an issue
