### ISSUE TITLE
Question Latency of RTPS using Wifi

### ISSUE THREAD

**Issue by ibassa08** [eProsima/Fast-RTPS#157]
I am currently using the publisher subscriber API when sending data readings over Wifi. I send my readings at 10 ms intervals. The mean latency is 2 ms which is acceptable for my application. I sometimes get spikes of latency of above 40-60 ms. This is also acceptable as long as I get the most recent reading. However it appears that all samples come in order of which they were sent and once there is a spike of latency , the following data samples( 3-4 samples) have a high latency as well. I have set the QoS to best effort and set history samples to 1. Is there anything I can set to to allow for the most recent readings to come as soon as possible. Do I maybe use the writer reader API instead.
Kind Regards

**Comment by richiware** [comment]
Can you copy here which subscriber's attributes are you setting?

**Comment by ibassa08** [comment]
Rparam.qos.m_reliability.kind = BEST_EFFORT_RELIABILITY_QOS;
    Rparam.topic.historyQos.kind = KEEP_LAST_HISTORY_QOS;
    Rparam.topic.historyQos.depth = 1;

**Comment by MiguelCompany** [comment]
Hi @ibassa08 
Fast-RTPS has seen a lot of performance improvements during the last months. 
Can you test again and report back?

**Comment by MiguelCompany** [comment]
@ibassa08 Closing this now. Feel free to reopen it if still an issue.

**Comment by SauravDharwadkar** [comment]
I'm facing same issues high latency 40-50 ms and even higher sometime, I'm using same settings with 35+ nodes.  Also i noticed that when i start adding new nodes in system the bandwidth or data consumption of existing node is also increased.( Measure using access point monitoring)
