### ISSUE TITLE
Question: How can I get Fast-RTPS to work if a network alias is set?

### ISSUE THREAD

**Issue by maxlein** [eProsima/Fast-RTPS#158]
Hi,,

in my setup I have an eth0 device, but also an eth0:0 network alias, which I cannot remove!
So my question is, how can I use Fast-RTPS here?

With the alias I always get "system_error: set_option: Address already in use".
Without it works, but this is no option for me.

My system is ubuntu 16.04,
eth0:    192.168.x.x
eth0:0: 10.42.x.x

**Comment by richiware** [comment]
Commit a7101e3353af3cc405c19cfd21de9ba5028e9929 should resolve your problem with network aliases.
