### ISSUE TITLE
RTPSTest_registered fails if sleep time is reduced

### ISSUE THREAD

**Issue by lshamis** [eProsima/Fast-RTPS#159]
TestWriterRegistered::run waits until n_matched > 0 before sending messages. The loop is:

     while (m_listener.n_matched == 0) {
         eClock::my_sleep(250);
     }

The messages do not make it to the reader if the time is reduced to 1 (or the while loop is replaced by a conditional variable notify).

**Comment by richiware** [comment]
I've tested with next [release](https://github.com/eProsima/Fast-RTPS/tree/release/1.7.0) and it's working following your steps. I will close the issue. If you still have problems you can reopen it.
