### ISSUE TITLE
Question: Ownership of message pointer in publisher write() function

### ISSUE THREAD

**Issue by scott-eddy** [eProsima/Fast-RTPS#161]
When generating example code with the HelloWorld.idl the message that is sent in the `run()` function is allocated on the stack and continually send, e.g.
```
	HelloWorld st;
	
	/* Initialize your structure here */
	
	int msgsent = 0;
	char ch = 'y';
	do
	{
		if(ch == 'y')
		{
			mp_publisher->write(&st);  ++msgsent; //<-- Write called with pointer to st
...

```

I am curious what the ownership semantics are for the pointer passed to the `write()` function, specifically when publishing in ASYNCHRONOUS_PUBLISH_MODE.  For example can a pointer to a data type be "reused" between calls to `write()`?  For example

```
// Suppose data to write has the following .idl
// struct DataToWrite{
// octet data;
// };
DataToWrite* message = new DataToWrite();

for(int i = 0; i < 5 < i++){
  message->data(i);
  publisher->write(message);
}
```

In this example I would expect 5 messages to be written, with the data member of the message increasing from 0-4.  Is that what would happen, or is there a race condition between the publisher writing the data and the main loop altering the data member?

If this is the wrong forum to ask such questions please let me know and I will ask somewhere else.  Thank you.

**Comment by richiware** [comment]
Sorry for the delay answering. It is totally safe to do what your are saying. ``write()`` function serializes internally the data and stores it in the History. After returning, you are able to reuse the data.

**Comment by scott-eddy** [comment]
@richiprosima thanks for the info.  I'll close this issue
