### ISSUE TITLE
Generated xxxPubSubType.h pollutes including namespace

### ISSUE THREAD

**Issue by wtsnyder** [eProsima/Fast-RTPS#163]
Auto-generated PubSubType headers include the line `using namespace eprosima::fastrtps;` which includes all the names from this namespace in any header indirectly or directly including this file.

All type names in the auto-generated headers should be fully qualified without using `using namespace` calls to prevent unexpected name collisions.

**Comment by richiware** [comment]
We will take note and make a future task, but we need time. I keep this issue open until fix this. Thanks for your suggestions.

**Comment by MiguelCompany** [comment]
This was solved by commit 86f0450ebcbbc36f4d749eaca5db821538e96d84.

If @wtsnyder verifies it, we may close this issue

**Comment by wtsnyder** [comment]
Looks good, thanks for cleaning this up.
