### ISSUE TITLE
declared but not defined methods

### ISSUE THREAD

**Issue by dirk-thomas** [eProsima/Fast-RTPS#164]
The method `eprosima::fastrtps::SubscriberHistory::isUnreadCache` is being declared in [this](https://github.com/eProsima/Fast-RTPS/blob/bec4a979c088a1f978af3dfdea2a72ae2a78b52a/include/fastrtps/subscriber/SubscriberHistory.h#L85) line but not defined or used anywhere.

**Comment by dirk-thomas** [comment]
Same for `eprosima::fastrtps::PublisherImpl::getHistoryElementsNumber`.

**Comment by MiguelCompany** [comment]
This has been solved on commit e4f0db61653ca2bb7ee2d419a30485269f4ae51f

**Comment by dirk-thomas** [comment]
> This has been solved on commit e4f0db6

I don't see the method name `isUnreadCache` anywhere in that patch?

**Comment by MiguelCompany** [comment]
> I don't see the method name isUnreadCache anywhere in that patch?

It was removed on commit dcd5e916d6a7e7658cc0d61cf39a8331bfca65ab
