### ISSUE TITLE
make API const correct

### ISSUE THREAD

**Issue by dirk-thomas** [eProsima/Fast-RTPS#165]
Many APIs could / should be `const` but are not declared as such. E.g. [SubscriberHistory::getUnreadCount()](https://github.com/eProsima/Fast-RTPS/blob/bec4a979c088a1f978af3dfdea2a72ae2a78b52a/include/fastrtps/subscriber/SubscriberHistory.h#L111) which simply returns the value of a member could be declared `const`.

But this applies to a lot of functions in the API. Is there a reason why those are not declared as `const`?

**Comment by richiware** [comment]
First developer of FastRTPS doesn't have the habit of use ``const``. Now, as we keep modifying the code, we try to use it. Thanks for your suggestions.

**Comment by dirk-thomas** [comment]
It might be an option to add `const` functions beside the current non-const versions so that users can start using those. That would allow to deprecate and at some point remove the non-const ones sometime in the future.

Are you interested in doing this and/or would you accept pull requests towards this direction?

**Comment by richiware** [comment]
At this moment we have no time to do this. We appreciate any PR. Thanks
