### ISSUE TITLE
How to use  eProsima transfer image   

### ISSUE THREAD

**Issue by faciler** [eProsima/Fast-RTPS#168]
I am trying to transfer image with eProsima/Fast-RTPS.I use OpenCV to serialize image , but when sending data, eProsima will serialize again, it result in  subscriber can only recive four characters. Can I continue to use OpenCV to serialize image, or  eProsima can send image without extra serialize?

**Comment by richiware** [comment]
How is your type's definition used in FastRTPS? Is it a sequence of octets?

**Comment by faciler** [comment]
[HelloWorldExample.zip](https://github.com/eProsima/Fast-RTPS/files/1561340/HelloWorldExample.zip)


A string data type, 

I modfied the HelloWorldExample program that provided by you, an example program is attached, it might be clearly.

**Comment by richiware** [comment]
[HelloWorldExample.zip](https://github.com/eProsima/Fast-RTPS/files/1570668/HelloWorldExample.zip)

Main problem is string type ends at first '\0'. Data returned by OpenCV is binary data and contains '\0'. I've created a ``OpenCVBufferType`` that receives directly the ``std::vector<uchar>``. I've changed your example to use it. I hope it helps you.

**Comment by faciler** [comment]
It does work! and I get it, Thank you for your help!
