### ISSUE TITLE
Compiler warnings on Windows

### ISSUE THREAD

**Issue by gerkey** [eProsima/Fast-RTPS#17]
Our CI jobs have noted a handful of compiler warnings on Windows. Here's a representative build:

http://ci.ros2.org/job/ci_windows/1012/warnings34Result/

It would be great if you could find time to address the warnings, as it would allow us in the future to make sure that we're avoiding potential problems.

**Comment by richiprosima** [comment]
Now we support officially VS 2015 and we can detect new compile warnings comming on this version of VS. We removed the four C4457 warnings in EDPStatic.cpp file.
