### ISSUE TITLE
Docs list incorrect library attribute: defaultUnicastLocatorList

### ISSUE THREAD

**Issue by syncharny** [eProsima/Fast-RTPS#171]
According to http://eprosima-fast-rtps.readthedocs.io/en/latest/pubsub.html#listening-locators you should be able to set the deafultUnicastLocator:

```
eprosima::fastrtps::ParticipantAttributes part_attr;

// This locator will open a socket to listen network messages on UDPv4 port 22225 over network interface 192.168.0.1
eprosima::fastrtps::rtps::Locator_t locator.set_IP4_address(192, 168, 0 , 1);
locator.port = 22225;

part_attr.rtps.builtin.defaultUnicastLocatorList.push_back(locator);
```

However, when I try this I get the following error:

>error: ‘class eprosima::fastrtps::rtps::BuiltinAttributes’ has no member named ‘defaultUnicastLocatorList’

**Comment by richiware** [comment]
The documentation is incorrect. This attribute is located in ``RTPSParticipantAttributes``. You should write:

```c++
part_attr.rtps.defaultUnicastLocatorList.push_back(locator);
```
I will update the documentation. Thanks

**Comment by MiguelCompany** [comment]
Documentation has already been updated. This issue can be closed
