### ISSUE TITLE
Issue: eProsima Fast-RTPS on Multi-hop network

### ISSUE THREAD

**Issue by faciler** [eProsima/Fast-RTPS#172]
I implement a linear multi-hop network, the topology is as simple as 
Node_A <--> Node_B <--> Node_C 
where Node_A and Node_C are blocked by iptable rules.

The wireshark @A and @C can capture the INFO_DST, HeartBeat and Data(p). So that I presume the pub-sub relationship has been successfully established.
Also, A can ping C successfully.

However, when A publishes images to the subscriber at C, C cannot receive the image from A.

Any clues on whether the RTPS Qos Settings forbid multi-hop transmission or there are other issues?

**Comment by faciler** [comment]
I use olsr to transpond data, and I found the problem is my olsr don't transpond multicast data. so I download the OLSR Multicast Forwarding Plugin, then got this error:
terminate called after throwing an instance of 'std::system_error'
  what():  set_option: Address already in use

**Comment by faciler** [comment]
I have tried some different ways to find out.  A simple UDP demo,a RTI Connext DDS demo, both of them are work well. So I am thinking eProsima Fast-RTPS's underlying implementations cause the error. I sincerely request you can help me @richiware

**Comment by richiware** [comment]
What node is failing with an instance of ``std::system_error``? Can you copy the output of ``ifconfig`` in that machine?

**Comment by faciler** [comment]
eth0      Link encap:Ethernet  HWaddr 20:1a:06:bc:ec:bc  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:16 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:243 errors:0 dropped:0 overruns:0 frame:0
          TX packets:243 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:17697 (17.6 KB)  TX bytes:17697 (17.6 KB)

teredo    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet6 addr: 2001:0:53aa:64c:1c76:f7bb:8a77:a69d/32 Scope:Global
          inet6 addr: fe80::ffff:ffff:ffff/64 Scope:Link
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1280  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:0 (0.0 B)  TX bytes:144 (144.0 B)

wlan0     Link encap:Ethernet  HWaddr 34:23:87:ee:05:89  
          inet addr:192.168.100.111  Bcast:192.168.100.255  Mask:255.255.255.0
          inet6 addr: fe80::3623:87ff:feee:589/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:44 errors:0 dropped:0 overruns:0 frame:909
          TX packets:138 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:4821 (4.8 KB)  TX bytes:18952 (18.9 KB)
          Interrupt:17

**Comment by faciler** [comment]
Raspberry PI 3(ubuntu 16.04mate) ,laptop and desktop(ubuntu14.04). All of this have the same error while I  `sudo ./olsrd` on these machines.  
The virtual network card ' teredo' was created by the OLSR Multicast Forwarding Plugin.

**Comment by faciler** [comment]
It should be a socket bind  @error richiware ,and I have found it in the .cpp file `UDPv4Transport.cpp`, line 472, but I don't know how to modify it correctly..

**Comment by richiware** [comment]
Last commit a7101e3353af3cc405c19cfd21de9ba5028e9929 solves a similar problem using network aliases. Can you check it solves yours?

**Comment by faciler** [comment]
Yeah! It does work ,thank you very much !
