### ISSUE TITLE
TCP Transport for Fast-RTPS

### ISSUE THREAD

**Issue by glkhobragade** [eProsima/Fast-RTPS#174]
I wanted to remove the default  UDPv4 transport implementation from ROS2 and replace it with custom TCP transport.  But as the discovery of participants is possible only using multicast address and TCP does not support sending multicast messages,  is  it valid to use TCP as transport completely?

**Comment by glkhobragade** [comment]
any update please, just need some suggestions here.

**Comment by richiware** [comment]
This [link](http://eprosima-fast-rtps.readthedocs.io/en/latest/pubsub.html#tips) explains how disable completely multicast traffic.

**Comment by richiware** [comment]
Did the link help you?

**Comment by MiguelCompany** [comment]
Since @glkhobragade didn't answer for more than six months, we are closing this issue
