### ISSUE TITLE
introduced compiler warning on Windows 

### ISSUE THREAD

**Issue by dirk-thomas** [eProsima/Fast-RTPS#176]
In the recent commit 845dec34b9d8a9c74ae2066ac67434e5d2522d6b a compiler warning was introduced on Windows (see http://ci.ros2.org/view/nightly/job/nightly_win_deb/742/warnings41Result/new/):

* SecurityManager.cpp:201, MSBuild, Priority: Normal
   declaration of 'exception' hides previous local declaration
* SecurityManager.cpp:215, MSBuild, Priority: Normal
   declaration of 'exception' hides previous local declaration

**Comment by richiware** [comment]
Thanks for the reporting. I will remove the warnings.

**Comment by richiware** [comment]
#175
