### ISSUE TITLE
Restrict all (multicast) exchange only to selected network interface(s)

### ISSUE THREAD

**Issue by alekseymt74** [eProsima/Fast-RTPS#179]
I have multiple network cards on each computer in our system and want to organize RTPS communication only via selected one. And also split different domains to unique multicast groups.
Is it possible?
I tried to play with ParticipantAttributes.rtps.defaultOutLocatorList to restrict communication to one interface, but publisher/subscriber linkage failed. 

In **version 1.4** I managed to forward all communication to selected interface in following way (without clear undestanding, by brute force):

```
      eprosima::fastrtps::rtps::Locator_t mcast_locator;
      mcast_locator.set_IP4_address( 236, 0, 0, 1 );
      mcast_locator.port = 22224;
      part_attrs.rtps.builtin.metatrafficMulticastLocatorList.push_back( mcast_locator );

      eprosima::fastrtps::rtps::Locator_t out_locator;
      //out_locator.set_IP4_address( 169, 254, 66, 68 );
      //out_locator.set_IP4_address( 192, 168, 2, 78 );
      out_locator.set_IP4_address( 192, 168, 56, 1 );
      part_attrs.rtps.defaultUnicastLocatorList.push_back( out_locator );
      part_attrs.rtps.builtin.metatrafficUnicastLocatorList.push_back( out_locator );
      part_attrs.rtps.defaultOutLocatorList.push_back( out_locator );
```
As I see in Wireshark this approach gives desired result. But attemps to split metatraffic & data into different interfaces failed.

**In version 1.5 this approach doesn't works**

Thanks!

**Comment by MiguelCompany** [comment]
Hi @alekseymt74 

On the latest release (v1.7.0) you can achieve this by setting [Whitelist Interfaces](https://eprosima-fast-rtps.readthedocs.io/en/latest/advanced.html#whitelist-interfaces)
