### ISSUE TITLE
A small question about alignment calculation in DH exchange information.

### ISSUE THREAD

**Issue by davidhuziji** [eProsima/Fast-RTPS#180]
Hi,

I'm studying Fast-RTPS Security Plugins.

Here is a small question about calculating the alignment inside DH exchange information in PKIDH.cpp. Please help take a look at it.

In [https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/security/authentication/PKIDH.cpp#L716](url),
I guess it might be
```
len += BN_serialized_size(g, len);
len += BN_serialized_size(pub_key, len);
```
In my very own opinion, according to the implementation of `BN_serialized_size()` in [https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/security/authentication/PKIDH.cpp#L54](url), the current alignment got from last data chunk should be added to calculate new alignment of current data chunk.

I guess because the parameters in current DH algorithm are all 4-byte aligned, the current code work normally.

Please help correct me if there is anything wrong in above.

Thank you.

**Comment by MiguelCompany** [comment]
> I guess because the parameters in current DH algorithm are all 4-byte aligned, the current code work normally.

I guess you're right. Even though, DH parameters will almost always hava a length multiple of 4.

Anyways, we take note of this.

**Comment by davidhuziji** [comment]
@MiguelCompany Thanks a lot for your reply.
