### ISSUE TITLE
[solved e90e4b7] eProsima Fast-RTPS Segmentation Fault 

### ISSUE THREAD

**Issue by andrew-konecki-apexai** [eProsima/Fast-RTPS#181]
[sROS2]: https://github.com/ros2/sros2/blob/master/SROS2_Linux.md

[PublisherImpl cpp to frag or not to frag]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/src/cpp/publisher/PublisherImpl.cpp#L144-L160
[CacheChange h]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/include/fastrtps/rtps/common/CacheChange.h#L62-L194
[CacheChange vector clear]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/include/fastrtps/rtps/common/CacheChange.h#L175
[CacheChange dataFragment assignment]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/include/fastrtps/rtps/common/CacheChange.h#L149-L150
[CacheChange Setting Size]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/include/fastrtps/rtps/common/CacheChange.h#L181-L182

[Stateful Writer send any unsent changes]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/src/cpp/rtps/writer/StatefulWriter.cpp#L211-L380
[Loop through data to send]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/src/cpp/rtps/writer/StatefulWriter.cpp#L260-L352
[To add data frag or just data]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/src/cpp/rtps/writer/StatefulWriter.cpp#L280

[RTPSMessageGroup add_data_frag]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/src/cpp/rtps/messages/RTPSMessageGroup.cpp#L420-L498
[Frag Start Frag Size]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/src/cpp/rtps/messages/RTPSMessageGroup.cpp#L444-L447
[Scope CacheChange Assignment]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/src/cpp/rtps/messages/RTPSMessageGroup.cpp#L450-L453
[CacheChange Constructor Scoped]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/src/cpp/rtps/messages/RTPSMessageGroup.cpp#L450-L451

[copy_not_memcpy]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/include/fastrtps/rtps/common/CacheChange.h#L137-L153
[getFragmentCount]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/include/fastrtps/rtps/common/CacheChange.h#L161-L164
[setFragmentSize]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/include/fastrtps/rtps/common/CacheChange.h#L170-L184

[vector construct from taint violation 1]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/src/cpp/rtps/security/SecurityManager.cpp#L2339
[vector construct from taint violation 2]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/src/cpp/rtps/security/SecurityManager.cpp#L2399
[vector construct from taint violation 3]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/src/cpp/rtps/security/SecurityManager.cpp#L2519
[vector construct from taint violation 4]: https://github.com/eProsima/Fast-RTPS/blob/1f135d478dd9dcde98ed96c9aeef4f229e3a1450/src/cpp/rtps/security/SecurityManager.cpp#L2565

# eProsima Segmentation Fault Summary
## Description
This is a summary of the occurrence of a segmentation fault within the Fast-RTPS DDS library specifically providing information for commit e90e4b7b2c438d9fe5bdc97d94c5ec6318328e1d.

## Background
Currently using eProsima's Fast-RTPS commit `1f135d478dd9dcde98ed96c9aeef4f229e3a1450` that matches the release for ROS2 Ardent release.  During execution, using both security and the non-security compilation options, our specific target system experiences a segmentation fault.

Trace of segmentation fault with security option
```
#0  __memmove_ssse3_back ()
    at ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:1574
#1  0x00007fb563b84075 in std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<unsigned char> (
    __first=0x2b1bc70 "=\236\322\300\224\002\356>\246딿\261\260\060=", 
    __last=0x102a47e71 <error: Cannot access memory at address 0x102a47e71>, 
    __result=0x7fb4280d3010 "") at /usr/include/c++/5/bits/stl_algobase.h:384
#2  0x00007fb563844414 in std::__copy_move_a<false, unsigned char*, unsigned char*> (__first=0x2b1bc70 "=\236\322\300\224\002\356>\246딿\261\260\060=", 
    __last=0x102a47e71 <error: Cannot access memory at address 0x102a47e71>, 
    __result=0x7fb4280d3010 "") at /usr/include/c++/5/bits/stl_algobase.h:402
#3  0x00007fb5638414e4 in std::__copy_move_a2<false, unsigned char*, unsigned char*> (__first=0x2b1bc70 "=\236\322\300\224\002\356>\246딿\261\260\060=", 
    __last=0x102a47e71 <error: Cannot access memory at address 0x102a47e71>, 
    __result=0x7fb4280d3010 "") at /usr/include/c++/5/bits/stl_algobase.h:440
#4  0x00007fb56383debd in std::copy<unsigned char*, unsigned char*> (
    __first=0x2b1bc70 "=\236\322\300\224\002\356>\246딿\261\260\060=", 
    __last=0x102a47e71 <error: Cannot access memory at address 0x102a47e71>, 
    __result=0x7fb4280d3010 "") at /usr/include/c++/5/bits/stl_algobase.h:472
#5  0x00007fb563844441 in std::__uninitialized_copy<true>::__uninit_copy<unsigned char*, unsigned char*> (
    __first=0x2b1bc70 "=\236\322\300\224\002\356>\246딿\261\260\060=", 
    __last=0x102a47e71 <error: Cannot access memory at address 0x102a47e71>, 
---Type <return> to continue, or q <return> to quit---
    esult=0x7fb4280d3010 "") at /usr/include/c++/5/bits/stl_uninitialized.h:93
#6  0x00007fb56384151c in std::uninitialized_copy<unsigned char*, unsigned char*> (
    __first=0x2b1bc70 "=\236\322\300\224\002\356>\246딿\261\260\060=", 
    __last=0x102a47e71 <error: Cannot access memory at address 0x102a47e71>, __result=0x7fb4280d3010 "")
    at /usr/include/c++/5/bits/stl_uninitialized.h:126
#7  0x00007fb56383def3 in std::__uninitialized_copy_a<unsigned char*, unsigned char*, unsigned char> (
    __first=0x2b1bc70 "=\236\322\300\224\002\356>\246딿\261\260\060=", 
    __last=0x102a47e71 <error: Cannot access memory at address 0x102a47e71>, __result=0x7fb4280d3010 "")
    at /usr/include/c++/5/bits/stl_uninitialized.h:281
#8  0x00007fb5601c2348 in std::vector<unsigned char, std::allocator<unsigned char> >::_M_range_initialize<unsigned char*> (
    this=0x7fb55c955360, __first=0x2b1bc70 "=\236\322\300\224\002\356>\246딿\261\260\060=", 
    __last=0x102a47e71 <error: Cannot access memory at address 0x102a47e71>) at /usr/include/c++/5/bits/stl_vector.h:1290
#9  0x00007fb5601bf51a in std::vector<unsigned char, std::allocator<unsigned char> >::_M_initialize_dispatch<unsigned char*> (
    this=0x7fb55c955360, __first=0x2b1bc70 "=\236\322\300\224\002\356>\246딿\261\260\060=", 
    __last=0x102a47e71 <error: Cannot access memory at address 0x102a47e71>) at /usr/include/c++/5/bits/stl_vector.h:1263
#10 0x00007fb5601bcd35 in std::vector<unsigned char, std::allocator<unsigned char> >::vector<unsigned char*, void> (this=0x7fb55c955360, 
    __first=0x2b1bc70 "=\236\322\300\224\002\356>\246딿\261\260\060=", 
    __last=0x102a47e71 <error: Cannot access memory at address 0x102a47e71>, __a=...) at /usr/include/c++/5/bits/stl_vector.h:404
#11 0x00007fb5601b63e8 in eprosima::fastrtps::rtps::security::SecurityManager::encode_serialized_payload (this=0x2157328, payload=..., 
    output_message=..., writer_guid=...)
    at /home/nebo/527_apexai_sec_normal/apex_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/security/SecurityManager.cpp:2429
#12 0x00007fb5600f8011 in eprosima::fastrtps::rtps::RTPSMessageGroup::add_data_frag (this=0x7fb55c955bb0, change=..., fragment_number=15, 
    remote_readers=std::vector of length 1, capacity 1 = {...}, locators=..., expectsInlineQos=false)
    at /home/nebo/527_apexai_sec_normal/apex_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/messages/RTPSMessageGroup.cpp:460
#13 0x00007fb5600aaf1e in eprosima::fastrtps::rtps::StatefulWriter::send_any_unsent_changes (this=0x29dd600)
    at /home/nebo/527_apexai_sec_normal/apex_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/writer/StatefulWriter.cpp:269
#14 0x00007fb5600a1b2c in eprosima::fastrtps::rtps::AsyncWriterThread::run ()
    at /home/nebo/527_apexai_sec_normal/apex_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/resources/AsyncWriterThread.cpp:127
#15 0x00007fb56008cf7b in std::_Bind_simple<void (*())()>::_M_invoke<>(std::_Index_tuple<>) (this=0x21badc8)
    at /usr/include/c++/5/functional:1531
```

Trace of segmentation fault in absence of security 
```
#0  memcpy () at ../sysdeps/aarch64/memcpy.S:156
#1  0x0000007fb6f611b0 in eprosima::fastrtps::rtps::CDRMessage::addData (msg=0x7fa00008c0, data=0x1583488 "83\263>", length=4294967273)
    at /tmp/ros2_ws/src/eProsima/Fast-RTPS/include/fastrtps/rtps/messages/CDRMessage.hpp:325
#2  0x0000007fb6f5f5f4 in eprosima::fastrtps::rtps::RTPSMessageCreator::addSubmessageDataFrag (msg=0x13b4208, change=0x7fa7ffe208, fragment_number=2, 
    sample_size=65393, topicKind=eprosima::fastrtps::rtps::NO_KEY, readerId=..., expectsInlineQos=false, inlineQos=0x0)
    at /tmp/ros2_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/messages/submessages/DataMsg.hpp:357
#3  0x0000007fb6f635d8 in eprosima::fastrtps::rtps::RTPSMessageGroup::add_data_frag (this=0x7fa7ffe698, change=..., fragment_number=2, 
    remote_readers=std::vector of length 1, capacity 1 = {...}, locators=..., expectsInlineQos=false)
    at /tmp/ros2_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/messages/RTPSMessageGroup.cpp:472
#4  0x0000007fb6f14414 in eprosima::fastrtps::rtps::StatefulWriter::send_any_unsent_changes (this=0x13b4140)
    at /tmp/ros2_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/writer/StatefulWriter.cpp:269
#5  0x0000007fb6f0a9b0 in eprosima::fastrtps::rtps::AsyncWriterThread::run ()
    at /tmp/ros2_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/resources/AsyncWriterThread.cpp:127
#6  0x0000007fb6ef1d6c in std::_Bind_simple<void (*())()>::_M_invoke<>(std::_Index_tuple<>) (this=0xcec088) at /usr/include/c++/5/functional:1531
#7  0x0000007fb6ef1ca4 in std::_Bind_simple<void (*())()>::operator()() (this=0xcec088) at /usr/include/c++/5/functional:1520
#8  0x0000007fb6ef1c2c in std::thread::_Impl<std::_Bind_simple<void (*())()> >::_M_run() (this=0xcec070) at /usr/include/c++/5/thread:115
#9  0x0000007fb78d8280 in ?? () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#10 0x0000007fb7f25fc4 in start_thread (arg=0x7fb78d8260) at pthread_create.c:335
#11 0x0000007fb76d1290 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89
```

The current system is capable of publishing payloads of varying length; therefore there is a possibility of total number of UDP messages ranging from 1 to N where the Nth payload would contain the last pertinent data associated with the message.  The segmentation fault in the absence of security is possible but is tied more into specific usage but appears to be the same root cause (referenced payload length of message is incorrect between single / multiple UDP message state).

### Fast-RTPS Details
There are two execution states in which data is published using a stateful writer in eProsima's Fast-RTPS.  The two states of interest in particular are:
1. send_data : execution in which a total publication event that can fit within a single UDP length packet.
1. send_data_frag : execution in which publication event does not fit within a single UDP length packet.

During execution it is assumed that the execution state should reflect either state depending on the total length of the message payload and adjusts as necessary regardless of topic.

The violation of this assumption can be triggered when attempting to transition between these two operational states specifically on the transition from `send_data_frag` to `send_data`.  When attempting to transition between the two states, the transition does not actually occur and `send_data_frag` state ends up operating on a message that is destined for the `send_data` state.  When this occurs setting of the [fragment size][Frag Start Frag Size] ends up being incorrect; in turn later is used as parameters for serialization of the publication of the message.

### Re-Creation
For guaranteed generation of the segmentation fault it is best to compile Fast-RTPS with the security options and provide the necessary security information to exercise the `SecurityManager` code.  The example below takes advantage of the ROS2 platform to easily create publishing and subscribing nodes.  ROS2 is also be used to provide the necessary security information to the Fast-RTPS communication layer.  this step is omitted in this summary.  Please refer to [Security ROS github][sROS2] for this information.

Publisher
```CPP
#include <iostream>
#include <iomanip>
#include <chrono>
#include <string>
#include "std_msgs/msg/string.hpp"
#include "rclcpp/rclcpp.hpp"

using namespace std::chrono;

class ros2_pub_cpp : public rclcpp::Node
{
public:
  ros2_pub_cpp(bool start_large_data=false, std::string default_topic="test")
  : Node("ros2_pub"),
  m_large_data(start_large_data)
  {
    std::string message1 = std::string(1,'a');
    std::string message2 = std::string(1000000, 'a');

    m_string_pub = this->create_publisher<std_msgs::msg::String>( \
      default_topic);

    m_timer = this->create_wall_timer( \
      1000ms, \
      std::bind(&ros2_pub_cpp::pub_callback, this));

    m_small_msg.data = message1;
    m_large_msg.data = message2;
  }

private:
  void pub_callback() {

    if (m_large_data) {
      m_large_data = false;
      m_string_pub->publish(m_large_msg);

    } else {
      m_large_data = true;
      m_string_pub->publish(m_small_msg);
    }
  }

  std_msgs::msg::String m_large_msg;
  std_msgs::msg::String m_small_msg;
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr m_string_pub;
  rclcpp::TimerBase::SharedPtr m_timer;
  bool m_large_data;
};


// this file is simply a main file to create a ros1 style standalone node
int32_t main(int32_t argc, char * argv[])
{
  // ros2 initialization
  rclcpp::init(argc, argv);

  // setup executor for processing pub callbacks
  rclcpp::executors::SingleThreadedExecutor exec;
  auto vptr = std::make_shared<ros2_pub_cpp>();
  exec.add_node(vptr);

  // run endlessly
  exec.spin();

  rclcpp::shutdown();

  return 0;
}
```

Subscriber 
```CPP
#include <memory>
#include <iostream>
#include <iomanip>
#include <chrono>
#include <string>
#include "std_msgs/msg/string.hpp"

#include "rclcpp/rclcpp.hpp"

using std::placeholders::_1;

class ros2_sub_cpp : public rclcpp::Node
{
public:
  ros2_sub_cpp(std::string default_topic="test")
  : Node("ros2_sub"),
  m_counter(0)
  {
    m_string_sub = \
      create_subscription<std_msgs::msg::String>(default_topic, \
        std::bind(&ros2_sub_cpp::sub_callback, this, _1));
  }

private:
  void sub_callback(const typename std_msgs::msg::String::SharedPtr msg)
  {
    fprintf(stdout, "[%u] Received the string %s\n", m_counter, msg->data.c_str());
  }

  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr m_string_sub;
  uint32_t m_counter;
};

int32_t main(int32_t argc, char * argv[])
{
  // ros2 initialization
  rclcpp::init(argc, argv);

  // setup executor for processing sub callbacks
  rclcpp::executors::SingleThreadedExecutor exec;
  auto vptr = std::make_shared<ros2_sub_cpp>();
  exec.add_node(vptr);

  // run endlessly
  exec.spin();

  rclcpp::shutdown();

  return 0;
}
```

The publisher just switches between the two states by publishing data that would fit into a single UDP packet; later publishing data that would fit into more than one UDP packet (please note that this is compiled with C++ 14 in mind due to the `ms` usage in the publisher).

When executing without the usage of the security features Fast-RTPS will report the error and may cause a segmentation fault at specific points during execution (though not guaranteed) depending on usage.
```
[RTPS_WRITER Error] Cannot add DATA_FRAG submsg to the CDRMessage. Buffer too small -> Function add_data_frag
[RTPS_WRITER Error] Error sending fragment (35, 16) -> Function send_any_unsent_changes
```

### Reasoning Quick Summary 
One would need to examine `CacheChange` and `CacheChangePool` and how the objects between these two classes / data structures operate.  If the provided reserved buffer is not in the correct state, then `CacheChange` has the capability of setting the incorrect [fragment size][setFragmentSize] which rolls over into impacting [add_data_frag function][RTPSMessageGroup add_data_frag] which is later used to reference the length of the payload in question.  

During execution what happens is the previous `add_data_frag` fragment size is used instead of the desired fragment size of 1, and the conditional does not consider operating in the incorrect state (there are no bounds checks on the actual payload length).

### Other Areas of Interest 
- [PublisherImpl][PublisherImpl cpp to frag or not to frag]
- [CacheChange][CacheChange h]
- [Stateful Writer][Stateful Writer send any unsent changes]
- [add_data_frag][RTPSMessageGroup add_data_frag]
- [Security Manager Unbounded Check 1][vector construct from taint violation 1]
- [Security Manager Unbounded Check 2][vector construct from taint violation 2]
- [Security Manager Unbounded Check 3][vector construct from taint violation 3]
- [Security Manager Unbounded Check 4][vector construct from taint violation 4]

**Comment by andrew-konecki-apexai** [comment]
Please see [commit e90e4b7](https://github.com/eProsima/Fast-RTPS/commit/e90e4b7b2c438d9fe5bdc97d94c5ec6318328e1d) for resolution of this issue.

**Comment by dejanpan** [comment]
@richiware I think that you can close this issue, no?
