### ISSUE TITLE
Mutex lock inside constructor of class CacheChangePool (Fast-RTPS/src/cpp/rtps/history/CacheChangePool.cpp)

### ISSUE THREAD

**Issue by sagniknitr** [eProsima/Fast-RTPS#185]
I went through the FAST RTPS code found that rtps/history/CacheChangePool.cpp has a mutex defined inside the parameterized constructor. 

`CacheChangePool::CacheChangePool(int32_t pool_size, uint32_t payload_size, int32_t max_pool_size, MemoryManagementPolicy_t memoryPolicy) : mp_mutex(new std::mutex()), memoryMode(memoryPolicy)`
`{`
`    std::lock_guard<std::mutex> guard(*this->mp_mutex);`

    `//Common for all modes: Set the payload size (maximum allowed), size and size limit`
 `   ++pool_size; `

Can anyone explain the reason behind the use of mutex lock here ?

**Comment by MiguelCompany** [comment]
No reason. Has been removed on commit e4f0db61653ca2bb7ee2d419a30485269f4ae51f

**Comment by sagniknitr** [comment]
Thanks  @MiguelCompany
