### ISSUE TITLE
[question] How should I configure Fast-RTPS for use without a network connection?

### ISSUE THREAD

**Issue by barulicm** [eProsima/Fast-RTPS#187]
Is there a recommended way to configure Fast-RTPS to work without a network connection? (Ie. using the local loopback device to communicate between processes on one host)

I have followed the workaround in #63 (specifically, enabling multicasting on the lo network interface). With this step, the HelloWorld example participants seem to successfully discover each other, but the subscriber does not report any messages received. 

I see mentions of the various LocatorList variables in suggested solutions to seemingly related issues, but I'm unsure of how to use these lists while still using dynamic participant discovery.

No warnings get logged by Fast-RTPS, so I set the library to print all _Info_ level log entries. When the computer has an internet connection, I see data getting sent to endpoints like localhost (127.0.0.1) and the host's external IP address (192.168.x.x). Without a network connection, the Info logs only show attempts to send to the multicast address (239.255.0.1).

I've wandered a bit deeper into networking technologies than I usually go, so hopefully I've just missed something about Fast-RTPS configuration or the network setup of the host computer. Any help would be appreciated.

**Comment by barulicm** [comment]
After some more experimentation, I found that [`RTPSParticipantAttributes::defaultUnicastLocatorList`](https://github.com/eProsima/Fast-RTPS/blob/master/include/fastrtps/rtps/attributes/RTPSParticipantAttributes.h#L206) is my answer.

For completeness, here are the steps I had to take to get the HelloWorldExample running without an active network connection:

1. Enable multicasting on the host's loopback network interface:
   ```
   sudo ifconfig lo multicast
   sudo route add -net 224.0.0.0 netmask 240.0.0.0 dev lo
   ```
   For convenience, I added variants of these two commands to `/etc/rc.local` so multicasting would be enabled on every boot.

2. Add localhost to `defaultUnicastLocatorList`. This was done with this code:
   ```
   Locator_t loopbackLocator;
   loopbackLocator.set_IP4_address("127.0.0.1");
   PParam.rtps.defaultUnicastLocatorList.push_back(loopbackLocator);
   ```
   This has to be added to all participants that need to work via the loopback device.
   For HelloWorldExample, I added this block before [HelloWorldPublisher.cpp:50](https://github.com/eProsima/Fast-RTPS/blob/master/examples/C%2B%2B/HelloWorldExample/HelloWorldPublisher.cpp#L50) and [HelloWorldSubscriber.cpp:45](https://github.com/eProsima/Fast-RTPS/blob/master/examples/C%2B%2B/HelloWorldExample/HelloWorldSubscriber.cpp#L45).

As I believe this is correct, and definitely seems to work, I'm closing this question.

**Comment by EduPonz** [comment]
Hi @aditya2592 ,

It is needed if you are using the default transports and discovery mechanism, since in that case the PDP packets use multicast over UDPv4. If you are either using Discovery Server or limiting the transports to SHM only, then you don't need to enable multicast on the loopback interface.

**Comment by aditya2592** [comment]
Thanks @EduPonz, my idea is to use only SHM for processes on same PC but UDV4 for some process on another machine. I have setup the config like below where I am whitelisted the corresponding IPs for the right transports. Based on your comment above, would this fine for not having to use discovery server or enabling multicast on loopback?:

```
<?xml version="1.0" encoding="UTF-8" ?>
<dds>
    <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
        <transport_descriptors>
            <!-- Create a descriptor for the new transport -->
            <transport_descriptor>
                <transport_id>shm_transport</transport_id>
                <type>SHM</type>
                <interfaceWhiteList>
                    <address>127.0.0.1</address>
                </interfaceWhiteList>
            </transport_descriptor>
        </transport_descriptors>
        <transport_descriptors>
            <!-- Create a descriptor for the new transport -->
            <transport_descriptor>
                <transport_id>udp_transport</transport_id>
                <type>UDPv4</type>
                <sendSocketBufferSize>1048576</sendSocketBufferSize>
                <listenSocketBufferSize>4194304</listenSocketBufferSize>
                <interfaceWhiteList>
                    <address>x.x.x.x</address>
                </interfaceWhiteList>
            </transport_descriptor>
        </transport_descriptors>

        <participant profile_name="super_client_profile" is_default_profile="true">
            <rtps>
                <!-- Link the Transport Layer to the Participant -->
                <userTransports>
                    <transport_id>udp_transport</transport_id>
                    <transport_id>shm_transport</transport_id>
                </userTransports>
                <useBuiltinTransports>false</useBuiltinTransports>
                <builtin>
                <initialPeersList>
                    <locator>
                        <udpv4>
                            <address>127.0.0.1</address>
                        </udpv4>
                    </locator>
                    <locator>
                        <udpv4>
                            <address>x.x.x..x</address>
                        </udpv4>
                    </locator>
                </initialPeersList>
            </builtin>
            </rtps>
        </participant>
    </profiles>
</dds>
```

**Comment by EduPonz** [comment]
Hi @aditya2592 , 

Yes, your approach should suffice to avoid discovery server and multicast on loopback. You could actually take it one step further and disable multicast completely (see [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/wifi/disable_multicast.html)).
