### ISSUE TITLE
TimerEventImpl objects gets deleted within its callback. [4771]

### ISSUE THREAD

**Issue by guillaumeautran** [eProsima/Fast-RTPS#193]
When the `RemoteParticipantLeaseDuration` expires on a participant, the timer event callback gets called and deletes the instance of the timer itself (here: https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/rtps/builtin/discovery/participant/timedevent/RemoteParticipantLeaseDuration.cpp#L73). This actually causes the event callback to return on an invalid object (which was already deleted) here: https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/rtps/resources/TimedEventImpl.cpp#L196

This then leads to a deadlock of the timer thread when trying to access the condition variable member variable here: https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/rtps/resources/TimedEventImpl.cpp#L213

**Comment by MiguelCompany** [comment]
Not sure if commit 458f42a7f32634140cf5e6da082fd9dd29268ab3 is addressing this issue. Could you please check on your side?

**Comment by richiware** [comment]
@guillaumeautran ping

**Comment by guillaumeautran** [comment]
This issue is no longer a concern and can be closed.
