### ISSUE TITLE
Message duplicated on DISCOVERED_RTPSPARTICIPANT after DROPPED_RTPSPARTICIPANT

### ISSUE THREAD

**Issue by cvilas** [eProsima/Fast-RTPS#194]
I am using the RTPS reader/writer layer in my application. My issue is that after an RTPS participant drops out and gets rediscovered, an avalanche of past messages from the participant get reposted on the network. These messages have been actioned already by other participants in the network. Given the nature of our application, duplicates are causing us severe problems. Unfortunately, I don't have a simple example code handy that replicates the issue. I hope the following description of settings of various attributes of RTPS entities helps. 

To improve the response of our system consisting of multiple participants across a local wireless network, I set my participant attributes as follows (identical for all participants):

```
RTPSParticipantAttributes partParams ;
partParams.builtin.leaseDuration_announcementperiod.seconds = 10;
partParams.builtin.leaseDuration.seconds = 20;
```
These are significantly lower than the default settings, and on a flaky network, participant drops can happen quite easily. 

All RTPS readers and writers are configured identically. For instance, for the reader, they are

```
ReaderAttributes readerAttr_;
readerAttr_.endpoint.reliabilityKind = ReliabilityKind_t::RELIABLE;
readerAttr_.endpoint.durabilityKind = VOLATILE;

ReaderQos readerQos_;
readerQos_.m_reliability.kind = RELIABLE_RELIABILITY_QOS;
readerQos_.m_durability.kind = VOLATILE_DURABILITY_QOS;

HistoryAttributes historyAttr_;
historyAttr_.memoryPolicy = PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
historyAttr_.payloadMaxSize = 384;
historyAttr_.initialReservedCaches = 500;
historyAttr_.maximumReservedCaches = 0;

TopicAttributes topicAttr_;
topicAttr_.topicKind = TopicKind_t::NO_KEY;
topicAttr_.historyQos.depth = 1;
topicAttr_.historyQos.kind = KEEP_LAST_HISTORY_QOS;

topicAttr_.resourceLimitsQos.max_samples = 0;
topicAttr_.resourceLimitsQos.max_instances = 500;
topicAttr_.resourceLimitsQos.max_samples_per_instance = 0;
topicAttr_.resourceLimitsQos.allocated_samples = 0;
```

The corresponding writer attributes are exactly the same, except that it is also set to be synchronous:

```
WriterAttributes writerAttr_;
writerAttr_.mode = SYNCHRONOUS_WRITER;
WriterQos writerQos_;
writerQos_.m_publishMode.kind = SYNCHRONOUS_PUBLISH_MODE;
```

I assumed that with these settings (especially `KEEP_LAST_HISTORY_QOS` with a depth of 1 and `VOLATILE_DURABILITY_QOS`), a rediscovery of a dropped participant should not cause old messages to be resent again. What am I missing? How do I ensure that old messages are not published again?

Thanks very much for your help, in advance.

**Comment by cvilas** [comment]
I suspect what I was missing was setting the liveliness QoS parameters for the reader and writer. Based on  a sample of one 40 min long test, it looks like my issue with stale messages has gone away.

**Comment by cvilas** [comment]
Not gone away. Old messages still get posted after a participant rediscovery

**Comment by cvilas** [comment]
@richiware - Would appreciate your advice on this one please.

**Comment by JaimeMartin** [comment]
HI @cvilas.

We will answer you soon.

**Comment by MiguelCompany** [comment]
Hi @cvilas,

Commit 4a08da5 should solve this issue. Please check on your side and report back here so we can close this issue

**Comment by cvilas** [comment]
Hi @MiguelCompany - this seems to work, although a couple of stale messages do get through every once in a while after rediscovery. This is probably unavoidable given the nature of the underlying protocol. We can perhaps get rid of that with some sort of filtering mechanism at the application level. It's a vast improvement nevertheless. Thanks for the fix.

**Comment by MiguelCompany** [comment]
Hi @cvilas, 

Please bear in mind that historyQos is not managed by the reader/writer layer. In RELIABLE-VOLATILE mode, messages are only removed from the writer's history after they've been ack'ed by all the associated readers. This means that if acknack messages are lost, some messages may be resent after rediscovery.

You can force the "keep only 1" behaviour by setting both initialReservedCaches  and maximumReservedCaches to 1 on your writer's history attributes, and removing old changes before adding a new one. This way, at most one message will be resent after rediscovery.

**Comment by cvilas** [comment]
Agreed and understood! Thanks @MiguelCompany
