### ISSUE TITLE
Generated include guards do not honor module/namespace

### ISSUE THREAD

**Issue by raykraft** [eProsima/Fast-RTPS#195]
The header file include guards generated by fastrtpsgen (version 1.5) do not provide module/namespace consideration. Thus, two different IDL files, defining messages in different namespaces, but with the same base filename, will use the same header file include guard. This has the potential for causing issues when both files are included within the same compilation instance.

**Comment by MiguelCompany** [comment]
Hi @raykraft

Just to let you know we plan to fix this as part of a bunch of fixes to fastrtpsgen

**Comment by MiguelCompany** [comment]
This was solved by commits f058a036d51357b3419e72312ff48834df82af5f and eProsima/Fast-CDR@119c4aab926bd4d02cba12251e7b76906596500e
