### ISSUE TITLE
Fastrtpsgen 1.5 produces trailing include guard comment with inconsistent naming

### ISSUE THREAD

**Issue by raykraft** [eProsima/Fast-RTPS#196]
For file XXX.idl, the generated file XXX.h defines the include guard "_XXX_H_", which is fine.

However, the corresponding generated XXXPubSubTypes.h defines an opening guard of "_XXX_PUBSUBTYPES_H_", and a closing guard comment of " _Xxx_PUBSUBTYPE_H". The inconsistency here is:
1. The use of all caps for the opening and leading caps only for the closing.
2. The use of plural form for the opeing and singular for the closing.

**Comment by MiguelCompany** [comment]
This was fixed on commit 4d5f197385b716fe6249003f141174b95c01e7ed
