### ISSUE TITLE
Generated code for constants with negative values is incorrect

### ISSUE THREAD

**Issue by raykraft** [eProsima/Fast-RTPS#197]
Using fastrtpsgen version 1.5, the code generated for:

> const char CHAR_CONSTANT_NEGATIVE = -120;

is 

> const char CHAR_CONSTANT_NEGATIVE = null-120;

The source of this issue appears to be in thirdparty/idl/src/main/antlr4/omg/IDL.g4:
```
@init{
    String aux = null;
}
    :   
        {$literalStr += _input.LT(1).getText();}
        ( MINUS | PLUS | TILDE )
        primary_expr
        { aux=$primary_expr.literalStr; $literalStr += aux;}
    |   primary_expr { $literalStr = $primary_expr.literalStr; }
    ;
```

**Comment by raykraft** [comment]
Just checking whether or not this issue list is actively monitored -- could someone please confirm?

**Comment by richiware** [comment]
I had not time to test the issue. I will try next week.

**Comment by raykraft** [comment]
Thanks for the confirmation!

**Comment by richiware** [comment]
Commit ede928724f8f670d5c83acec0d5eddd45aa76e48 updates the idl-parser thirdparty. It should resolve your problem.

**Comment by raykraft** [comment]
@richiware, thank you! I pulled code and verified that your fix does the trick. Much appreciated.

-Ray
