### ISSUE TITLE
Serialization issue with arrays of enumerations

### ISSUE THREAD

**Issue by raykraft** [eProsima/Fast-RTPS#198]
Code generated using fastrtpsgen version 1.5 for an IDL definition defining an array of enumerations fails to build due to an issue with fastcdr attempting to invoke the 'serialize' method on a non-class object:

fastcdr/Cdr.h:1166:29: error: request for member 'serialize' in '*(type_t + ((sizetype)(count * 4ul)))', which is of non-class type 'const foo::message::test::enums::MyThirdEnum'
                             type_t[count].serialize(*this);

The IDL code producing this error is:
```
module foo {
module message {
struct DDSEnumFields {
  foo::message::test::enums::MyThirdEnum field[10];
};
};
};
```

**Comment by raykraft** [comment]
I accidentally omitted a definition of the enumeration "MyThirdEnum" mentioned above. Here is a reference example:

`module foo {
module message {
module test {
module enums {

enum MyThirdEnum {
    A,
    B,
    C,
    D,
    E
};
};
};
};
};`

**Comment by raykraft** [comment]
Just curious if this bug is on anyone's radar. In short, compiling code generated from IDL definitions with arrays of enumerations fails.

**Comment by MiguelCompany** [comment]
Hi @raykraft 

Just to let you know we plan to fix this as part of a bunch of fixes to fastrtpsgen

**Comment by MiguelCompany** [comment]
This has been fixed on commit eProsima/Fast-CDR@8b6b7f4d212eac9fe518fc7404ffc2e74022aa0c

**Comment by human-gnomon** [comment]
So this fix has caused another problem if you rely on multiple enums.
Example:
top_level.idl
```  
  module foo {
  module message {
  module test {
  module enums {

  struct ConfigurationMsg {
      foo::message::test::enums::EnumOne enumOne;
      foo::message::test::enums::EnumTwo enumTwo;
  };

  }; };  };  }; 
```
enum_one.idl
```
  module foo {
  module message {
  module test {
  module enums {

  enum EnumOne {
      CLOCKWISE,
      COUNTERCLOCKWISE
  };

  }; };  };  }; 
```
enum_two.idl
```
  module foo {
  module message {
  module test {
  module enums {

  enum EnumTwo {
      UP,
      DOWN
  };

  }; };  };  }; 
```

This results in the following autogenerated snippet:
```
 void foo::message::test::enums::ConfigurationMsg::deserialize(eprosima::fastcdr::Cdr &dcdr)
  {
      uint32_t enum_value = 0;
      dcdr >> enum_value;
      m_enumOne = (foo::message::test::enums::EnumOne)enum_value;
      uint32_t enum_value = 0;
      dcdr >> enum_value;
      m_enumTwo = (foo::message::test::enums::EnumTwo)enum_value;
      dcdr >> m_enumOne;
      dcdr >> m_enumTwo;
  }
```

Which fails to compile
```
 error: redeclaration of 'uint32_t enum_value'
     uint32_t enum_value = 0;
```

Do we have unit tests for FastCDR that can be updated with this fix?

**Comment by richiware** [comment]
Commit eProsima/Fast-CDR@c690b15e6670de46104ebacad7a2cb067b996c6c should solve this. Thanks for your feedback.
