### ISSUE TITLE
Question: Network Configuration

### ISSUE THREAD

**Issue by e55k4y** [eProsima/Fast-RTPS#203]
I want to implement Fast-RTPS with all communication over UDP Multicast but having problems with the network configuration.
My multicast group address is 224.0.0.1
I set metatrafficMulticastLocator and defaultMulticastLocator with 224.0.0.1 and ports 22222 and 22224 respectively.
Though I am able to subscribe to Discovery Topics and get Discovery messages, I am not able to receive the data messages sent by publishers on the topic.
I think I am missing something in the network configuration.
Any help would be appreciated.

**Comment by MiguelCompany** [comment]
As stated [here](http://eprosima-fast-rtps.readthedocs.io/en/latest/pubsub.html#setting-up-network-configuration), you use `defaultMulticastLocatorList` to set-up listening locators, but you also need to set-up sending locators with `defaultOutLocatorList` in order for the comunication to work

**Comment by MiguelCompany** [comment]
This was answered long ago. Closing issue.
