### ISSUE TITLE
Question: How can I add package larger than 16384 bytes in default performance test bundled with repo

### ISSUE THREAD

**Issue by foodtooth** [eProsima/Fast-RTPS#204]
I tried to add 65536 bytes test of latency, by mimicking other parts of the code (like 16384 bytes). But I got the RTPS_HISTORY Error complaining GUID UNKNOWN:

```
Printing round-trip times in us, statistics for 1000 samples
   Bytes, Samples,   stdev,    mean,     min,     50%,     90%,     99%,  99.99%,     max
--------,--------,--------,--------,--------,--------,--------,--------,--------,--------,
      16,    1000,    5.00,  120.28,  113.97,  120.16,  122.81,  130.87,  180.21,  226.80
      64,    1000,    3.00,  119.29,  115.79,  118.85,  121.69,  128.82,  135.35,  157.16
     256,    1000,    2.00,  120.76,  117.31,  120.29,  122.58,  129.34,  136.26,  154.43
    1024,    1000,    2.00,  123.39,  120.71,  123.08,  124.49,  130.81,  138.31,  151.80
    4096,    1000,    2.00,  128.61,  125.28,  128.14,  130.45,  135.97,  147.00,  174.24
   16384,    1000,    4.00,  156.92,  151.22,  156.66,  158.94,  164.73,  167.96,  252.55
[RTPS_HISTORY Error] Change writerGUID 1.f.30.17.3.2d.0.0.0.0.0.0|0.0.1.3 different than Writer GUID |GUID UNKNOWN| -> Function add_change
Segmentation fault (core dumped)
```

How can I fix this?

**Comment by richiware** [comment]
Since bc351b43d4486e4f01190e033ef68dcd1073d8c9 (already in master branch) latency_test application contains the option `--large`. With this option it will test two sizes, 64kb and 130kb.

**Comment by foodtooth** [comment]
Thanks a lot! I can add other package sizes now, and testing is ok

**Comment by foodtooth** [comment]
Hi @richiware , can I ask a question here?
When I tested with package larger than ~300K, the process is blocked. Some cout show that function `void LatencyTestPublisher::DataSubListener::onNewDataMessage()` is not triggered. How can I fix it?
