### ISSUE TITLE
Error: Reference to Module is ambiguous

### ISSUE THREAD

**Issue by flemic** [eProsima/Fast-RTPS#206]
Hi,

I'm trying to install Fast-RTPS on Mac OS X (High Sierra). I am following the instructions:

git clone --recurse-submodules https://github.com/eProsima/Fast-RTPS.git
cd Fast-RTPS && mkdir build && cd build
cmake -DTHIRDPARTY=ON -DBUILD_JAVA=ON ..
make 

After make I get the following error:

Scanning dependencies of target git_submodule_update_fastcdr
[  1%] Updating Git module fastcdr
[  1%] Built target git_submodule_update_fastcdr
Scanning dependencies of target git_submodule_update_idl
[  2%] Updating Git module idl
[  2%] Built target git_submodule_update_idl
Scanning dependencies of target java
[  3%] Generating Java application

> Task :idl:compileJava FAILED
warning: [options] source value 6 is obsolete and will be removed in a future release
warning: [options] target value 1.6 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
/Users/flemic/Fast-RTPS/thirdparty/idl/build/generated-src/IDLParser.java:544: error: reference to Module is ambiguous
                public Pair<Module, TemplateGroup> returnPair = null;
                            ^
  both class com.eprosima.idl.parser.tree.Module in com.eprosima.idl.parser.tree and class java.lang.Module in java.lang match
1 error
3 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':idl:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
1 actionable task: 1 executed
make[2]: *** [CMakeFiles/java] Error 1
make[1]: *** [CMakeFiles/java.dir/all] Error 2
make: *** [all] Error 2 

Can you please help me? Cheers!

**Comment by BorjaOuterelo** [comment]
Hi @flemic 

Which JDK version are you using?
If you are using any other than JDK8, could you try with JDK8?
It seems that they added "java.lang.Module" in JDK9 and it is causing some issues.

Best.

**Comment by flemic** [comment]
Hi @BorjaOuterelo ,

My version was indeed not JDK8. But even now, I get the same error.

flemic$ javac -version
javac 1.8.0_172

Best,
Filip

**Comment by flemic** [comment]
For future reference, the problem was most probably with Gradle taking the latest version of JDK, although the Java environment was set to JDK8. The solution was to remove all other versions of JDK, except for JDK8. 

As a side note, the installation worked only with sudo make && sudo make install.

Thanks @BorjaOuterelo  for your assistance, the issue can be closed. Cheers!

**Comment by BorjaOuterelo** [comment]
You are welcome.

**Comment by MiguelCompany** [comment]
Just for your information, this was fixed on eProsima/Fast-CDR@2c101be43a8717f8eeb577d294e37c29e8edbb76
