### ISSUE TITLE
ld: library not found for -lnsl

### ISSUE THREAD

**Issue by flemic** [eProsima/Fast-RTPS#208]
Hi,

I have a problem when compiling the makefile_i86Linux2.6gcc on Mac OS X (Sierra). I'm starting from HelloWorld.idl, then invoking _fastrtpsgen -example i86Linux2.6gcc HelloWorld.idl_ to create an example application, which seems to be working fine, but when I try _make -f makefile_i86Linux2.6gcc_ I get the following error:

FastRTPS example flemic$ make -f makefile_i86Linux2.6gcc 
Checking directory output
Checking directory output/i86Linux2.6gcc
Checking directory lib
Checking directory lib/i86Linux2.6gcc
Checking directory bin
Checking directory bin/i86Linux2.6gcc
g++ -m32 -shared -o lib/i86Linux2.6gcc/libHelloWorld.so output/i86Linux2.6gcc/HelloWorld.o  -lfastcdr -lfastrtps -ldl -lnsl -lm -lpthread -lrt -Llib/i86Linux2.6gcc 
ld: library not found for -lnsl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lib/i86Linux2.6gcc/libHelloWorld.so] Error 1

Can you please help me?
Cheers,
Filip

**Comment by BorjaOuterelo** [comment]
Hi @flemic 

That is the linker not finding "nsl" library (That's a Linux library).
At the moment fastrtpsgen does not support solution generation for MacOSX. However, the code generated should work on MacOSX without problems.
If you take the code generated(.cxx and .h) and ignore de makefile(makefile_i86Linux2.6gcc) creating your own makefile the example should compile, link and run out of the box.
One suggestion would be to look into the makefile_i86Linux2.6gcc file and adapt it to your platform.

Anyhow, we will look at this in detail in future versions.
Let us know if you found any other incompatibilities, that will help a lot.

best,
Borja.

**Comment by MiguelCompany** [comment]
Since commit f058a036d51357b3419e72312ff48834df82af5f, the generator has the ability of creating CMakeLists.txt files
