### ISSUE TITLE
serialization questions

### ISSUE THREAD

**Issue by liamstask** [eProsima/Fast-RTPS#21]
A couple observations/questions about the serialization interface.

It is currently required to specify a static max size for all messages on a topic. However, many serialization formats allow for variable length messages (ie, support variable length arrays in a message type). Is it possible to relax this requirement?

What is the requirement to register types via `Domain::registerType()`? I don't immediately see why this is needed.

Currently, the serialization/deserialization of data is not type safe, as data is passed through a `void*`, which is not ideal.

I wonder if it could be simpler for publishers/subscribers to only operate on raw payload bytes, such that serialization would happen before publishing and deserialization would happen after bytes had been received. 

With this approach, the `void*` interface could be avoided, and I think it would also be possible to remove the requirement to register types, since Fast-RTPS would not need to know anything about user data types.

Thoughts?

**Comment by richiprosima** [comment]
We are working on adding a dynamic behaviour in memory management #59

**Comment by MiguelCompany** [comment]
> It is currently required to specify a static max size for all messages on a topic. However, many serialization formats allow for variable length messages (ie, support variable length arrays in a message type). Is it possible to relax this requirement?

Since commit 956cc060bf7d2c72d68379fc729f756adde85df0, max size is not required

> What is the requirement to register types via Domain::registerType()? I don't immediately see why this is needed.
>
>Currently, the serialization/deserialization of data is not type safe, as data is passed through a void*, which is not ideal.
>
>I wonder if it could be simpler for publishers/subscribers to only operate on raw payload bytes, such that serialization would happen before publishing and deserialization would happen after bytes had been received.
>
>With this approach, the void* interface could be avoided, and I think it would also be possible to remove the requirement to register types, since Fast-RTPS would not need to know anything about user data types.

You can always use the [Writer-Reader layer](http://eprosima-fast-rtps.readthedocs.io/en/latest/rtps.html#writer-reader-layer) to operate directly on the raw payload.

You could base your code on the [RTPSTest_registered example](https://github.com/eProsima/Fast-RTPS/tree/master/examples/C%2B%2B/RTPSTest_registered)

**Comment by MiguelCompany** [comment]
Closing this now. Please reopen if still an issue.
