### ISSUE TITLE
Linter (clang-tidy) generates lots of 'suggestions'

### ISSUE THREAD

**Issue by cvilas** [eProsima/Fast-RTPS#210]
I recently added fastrtps as a third party `git submodule` in one of our projects. Our top level CMakeLists.txt integrates clang-tidy and clang-format to lint our code, and found the build process to generate quite a large number of suggested style and code changes within fastrtps [attached here](https://github.com/eProsima/Fast-RTPS/files/1969983/tidy_output.txt). While arguably many of these can be ignored (eg: readability-inconsistent-declaration-parameter-name or even cppcoreguidelines-pro-bounds-array-to-pointer-decay), there are a few others that might be 'nice' to fix, such as use of const references and smart pointers. 

I have created a [repo here](https://github.com/cvilas/experimental_fastrtps) that is a stripped out version of our repo with just the fastrtps submodule and top level build files, to reproduce the above report, in case it is useful.

**Comment by MiguelCompany** [comment]
Hey! Thanks!

This will be quite useful!

**Comment by LuisGP** [comment]
Hi @cvilas 
We created a [branch](https://github.com/eProsima/Fast-RTPS/commits/feature/cmake_clang_tools) to start adding static code analysis using clang-tidy to our code using your experimental repo. We want gradually add clang-format and cppcheck too and define our coding style guides to check against.
I'm closing the issue because it was addressed.
Thank you very much.

**Comment by cvilas** [comment]
Nice. Just a note that in clang format/tidy versions are manually specified in [FindClangTools.cmake](https://github.com/eProsima/Fast-RTPS/commit/d50fb6de67a4f0e77a602675f79b4834f3139546#diff-451360927d397a95a3a2504628c11c7c). You might want to modify it to find the latest available version on the host or just default to default names `clang-tidy` and `clang-format`.

**Comment by cvilas** [comment]
Created a separate HowTo guide as a tiny project, if it helps at all: https://github.com/cvilas/clang_tools_howto
