### ISSUE TITLE
[RTPS_HISTORY Error] history payload size of '5000' bytes is too small

### ISSUE THREAD

**Issue by sloretz** [eProsima/Fast-RTPS#213]
The memory policy used by [`HistoryAttributes` is `PREALLOCATED_MEMORY_MODE`](https://github.com/eProsima/Fast-RTPS/blob/095d657e117381fd7f6b611a0db216b7df942354/include/fastrtps/rtps/attributes/HistoryAttributes.h#L42). Would it be possible to expose this to users? The preallocated size is too small for FastRTPS to communicate successfully with RTI connext in some situations.

Connext by default sends `TypeObject` information as part of the `DDS-XTYPES`. As far as I can tell the maximum size of a `TypeObject` is unbounded. This can result in failure to match and a lot of console spam if a message type is big enough.

```
[RTPS_HISTORY Error] Change payload size of '5100' bytes is larger than the history payload size of '5000' bytes [...]
```

See also ros2/rmw_connext#288 and ros2/rmw_fastrtps#194 and [this comment](https://github.com/ros2/rmw_connext/pull/288#issuecomment-387789780).

**Comment by MiguelCompany** [comment]
Guess we could add reader and writer history attributes to the BuiltinAttributes class, and also provide support for them in the XML parser. 

Would that be enough?

**Comment by sloretz** [comment]
As in it would allow something like the following? I think that would do it.

```c++
ParticipantAttributes participantAttrs;
// ...
participantAttrs.rtps.builtin.readerHistoryMemoryPolicy = PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
participantAttrs.rtps.builtin.writerHistoryMemoryPolicy = PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
```

**Comment by mikaelarguedas** [comment]
@MiguelCompany friendly :bellhop_bell: , any update on this ?

**Comment by richiware** [comment]
We applied your suggestion on commit bf1715de. Thanks.
↪ 2018-07-19 jue 20:11, Mikael Arguedas <notifications@github.com>:

**Comment by mikaelarguedas** [comment]
Thanks @richiware!

We implemented the change on our side as well, feel free to close this issue :+1:  (I cannot close it myself as I'm not the original poster)

**Comment by Aposhian** [comment]
I'm getting this issue with the Nav2 lifecycle manger on ROS2 Humble:
```
[RTPS_READER_HISTORY Error] Change payload size of '24' bytes is larger than the history payload size of '11' bytes and cannot be resized. -> Function can_change_be_added_nts
```

This is with the default FastDDS config for ROS2, which should include `PREALLOCATED_WITH_REALLOC`, but then `DYNAMIC` for services? This error message doesn't give a GUID, so I'm having trouble narrowing it down further, but I'm guessing this is coming form a service.
