### ISSUE TITLE
A typo in method name.

### ISSUE THREAD

**Issue by jm3lee** [eProsima/Fast-RTPS#215]
https://github.com/eProsima/Fast-RTPS/blob/095d657e117381fd7f6b611a0db216b7df942354/test/performance/LatencyTestPublisher.cpp#L587

I highly recommend `s/analizeTime/analyzeTime/g`. Please see http://www.dictionary.com/browse/anal

**Comment by MiguelCompany** [comment]
This has been solved on commit e4f0db61653ca2bb7ee2d419a30485269f4ae51f
