### ISSUE TITLE
Question: thread blocked when sending large data 

### ISSUE THREAD

**Issue by hitzac** [eProsima/Fast-RTPS#219]
Context: when I do the performance tests of large data, adding two cases(200K, 1M ), such as this in the file of LatencyTestSubscriber.cpp and LatencyTestPublisher.cpp : `uint32_t  datassub_large[] = {63996, 131068, 200000, 1024000}`; but thread blocking is appear at this time till the end of test after an hour, as the same time, the memory of LatencyTest publisher and subscriber is 8M or so  when the blocking. 
         Have you ever seen this happen? what should I do ?

**Comment by richiware** [comment]
I don't see that behaviour. I will try myself to reproduce it.

**Comment by hitzac** [comment]
@richiware thanks, I have solve the problem. when large data tested,  ParticipantAttributes of send and listen buffer size be should more large.

**Comment by MiguelCompany** [comment]
>  I have solve the problem

Glad to hear that! 
Closing this then.
