### ISSUE TITLE
tags for release?

### ISSUE THREAD

**Issue by liamstask** [eProsima/Fast-RTPS#22]
It would be very helpful to have git tags to identify the revisions that correspond to releases. For instance, 22f8b8ddc0e773356f285f2d2df8911eb5651e8f bumps the version number but there is no tag associated with it.

This would mainly be helpful for external projects, such that a specific release of fast-rtps could be included as a dependency more easily.

**Comment by richiprosima** [comment]
We make tags in our internal git repository. But from this time I will try to
push them in Github repository. [v1.0.6](https://github.com/eProsima/Fast-RTPS/tree/v1.0.6) was pushed.

**Comment by liamstask** [comment]
great - thanks!
