### ISSUE TITLE
Question: Remote publisher-subscriber

### ISSUE THREAD

**Issue by sriramster** [eProsima/Fast-RTPS#220]
Hi, 

I'm trying to understand how to setup a remote publisher-subscriber pair communication msgs over UDP. Tried to search for examples and documents could'nt find something for quick start. Is there any links that is available which would help? 

Thanks.

**Comment by richiware** [comment]
You have documentation [here](http://eprosima-fast-rtps.readthedocs.io/en/latest/). Also you have an example [here](https://github.com/eProsima/Fast-RTPS/tree/master/examples/C%2B%2B/HelloWorldExample). I hope this help you.

**Comment by sriramster** [comment]
@richiware  Thanks for the links. But, I'm trying to setup a remote pub-sub model. i.e nodes running on two different machines. Could you point me to the respective docs or links?

**Comment by MiguelCompany** [comment]
You don't need any special action to setup a remote pub-sub model. The [example](https://github.com/eProsima/Fast-RTPS/tree/master/examples/C%2B%2B/HelloWorldExample) referenced will work when run on two machines on the same local network

**Comment by sriramster** [comment]
Thanks. It worked.

**Comment by MiguelCompany** [comment]
You're welcome
