### ISSUE TITLE
The fast rtps will NOT work when Domain id value is from 0xc16c to 0xc16f ?

### ISSUE THREAD

**Issue by xiaoniuguohe** [eProsima/Fast-RTPS#223]
Hi, we discovered by accident that the subscriber will not receive the data if domain id setting as 0xc16c - 0xc16f. So is there any restrictive condition to set domain id, or any bug when handle domain id? Thanks!

**Comment by MiguelCompany** [comment]
RTPS uses UDP to send and receive data. The port number used is related with the domain_id and the participant_id. Section 9.6.1 of [the RTPS standard](https://www.omg.org/spec/DDSI-RTPS/2.2/) specifies the default way in which the ports are calculated to allow interoperability. As UDP has a port number limit of 65535, the maximum domain_id value to create a valid port number is about 230.

**Comment by MiguelCompany** [comment]
Closing this, as the question has been answered long ago.
