### ISSUE TITLE
MinGW build

### ISSUE THREAD

**Issue by BigTony** [eProsima/Fast-RTPS#225]
Hi,

I needed compile this project with mingw (MinGW64-x86_64-7.2.0-posix-seh-rt_v5-rev1) and I was nicely surprised, that it is possible, even there is no support for that in docs. (Unlike other DDS implementation...)

Ofc, I've had to fix few CMake lines, and one ifdef, but nothing big. 

Is there some reason for not support build under MinGW? If no, can I try to create merge request with these changes?

**Comment by MiguelCompany** [comment]
Please go ahead and create a pull request, but bear in mind that they will have to pass our internal CI tests,  and that we are not going to mantain those changes.

**Comment by MiguelCompany** [comment]
@BigTony Closing this now. Feel free to open the mentioned pull request.

**Comment by mxg1984** [comment]
@BigTony  dear sir, I want to compile fastdds with mingw, but many errors occurred, can you kindly enough send the modified code to me?
mxg_gxm@sina.com

Thank you.
