### ISSUE TITLE
fastrtpsgen on IDL file with empty struct fails

### ISSUE THREAD

**Issue by raykraft** [eProsima/Fast-RTPS#226]
It is currently not possible to generate code via fastrtpsgen from an IDL file where the defined struct has no fields. The resulting error message is also not helpful.

This is a useful capability to have in cases where the IDL needs to define other entities (e.g., enums).

**Comment by MiguelCompany** [comment]
This has been solved on eProsima/IDL-parser@5933918cf9ad9c29aa6b00c3f669195bc9e6cf8d
