### ISSUE TITLE
Unknown CMake command for Android build

### ISSUE THREAD

**Issue by Theosakamg** [eProsima/Fast-RTPS#227]
When i build Fast-RTPS for Android :
```
CMake Error at CMakeLists.txt:209 (find_eprosima_thirdparty):
  Unknown CMake command "find_eprosima_thirdparty".
```
Connected to #207 and https://github.com/eProsima/Fast-RTPS/commit/1317424db90edf3d7bea7eb331d2bd0326e354d9

**Comment by Theosakamg** [comment]
Connected to #229

**Comment by MiguelCompany** [comment]
@Theosakamg As #229 has been merged, can you confirm this is solved and close the issue?
Thanks!
