### ISSUE TITLE
BestEffort communication doesn't work with ROS 2 since REF3020

### ISSUE THREAD

**Issue by mikaelarguedas** [eProsima/Fast-RTPS#230]
Since the removal of the samples for volatile publishers, best-effort communication doesnt work anymore.
Reliable communication still works. Note that in ROS2 both reliable and best_effort publishers use VOLATILE durabitility by default.

Commenting out https://github.com/eProsima/Fast-RTPS/commit/f8e3abf1c2790457c3e995a18b28a029c3d19793#diff-36c4b31ccdbe8d22a765182dad3a19a8R181 fixes it for me.

This can be easily reproduced by running:
`ros2 run demo_nodes_py talker_qos` in one terminal
and `ros2 run demo_nodes_py listener_qos` in another terminal.

With the current master they don't connect. With https://github.com/eProsima/Fast-RTPS/blob/9d4e3a19de57ac8d1afad85ab11d88251cefdec0/src/cpp/publisher/PublisherImpl.cpp#L181-L185 commented out they exchange messages successfully.

@richiware FYI

**Comment by richiware** [comment]
Thanks for the feedback. I will check it.
↪ 2018-06-21 jue 13:58, Mikael Arguedas <notifications@github.com>:

**Comment by richiware** [comment]
I've found the problem. It's easy to solve. But i want to make a regression test. Tomorrow morning I will push the solution.

**Comment by richiware** [comment]
Commit bb42407a0d304d01057b80b20cf0fcbd9e6e8a5d solves this issue. Thanks

**Comment by mikaelarguedas** [comment]
thanks @richiware I confirmed that it fixes the issue for us.

Will this change be integrated in the release/1.6.0 branch ?

**Comment by richiware** [comment]
Already done. Branch release/1.6.0 updated.
↪ 2018-06-22 vie 12:09, Mikael Arguedas <notifications@github.com>:

**Comment by mikaelarguedas** [comment]
Great, thanks for updating it.

Closing this issue then
