### ISSUE TITLE
[Question] ros2 node name to topic name mapping

### ISSUE THREAD

**Issue by sriramster** [eProsima/Fast-RTPS#234]
Hi, 

How do we get something similar to ros1 with ros2 where a rqt_graph shows a map of node_name and topics (pubs/subs) within the node. 

I tried experimenting this from rmw_fastrps & fast-rtps but was'nt successful. Please advice.

**Comment by wjwwood** [comment]
This is not really a Fast-RTPS related question, you've already asked this here:

https://answers.ros.org/question/294437/ros2-node-name-to-topic-name-mapping/

That was the right place to ask, and we'll answer it when we get some time do so (I'll try to answer sometime next week).

**Comment by MiguelCompany** [comment]
Thanks @wjwwood for your answer. Closing this as not related to Fast-RTPS
