### ISSUE TITLE
`fastrtpsgen` does not properly handle IDL annotations

### ISSUE THREAD

**Issue by deeplearningrobotics** [eProsima/Fast-RTPS#236]
Unknown IDL anotations should be ignored by the IDL compiler. This is not the case with `fastrtpsges`. This causes it to not be able to compile IDL files with annotations supported by other DDS implementations.

Please compare https://www.omg.org/spec/IDL/4.2/PDF Chapter 7.4.15 Building Block Annotations

**Comment by MiguelCompany** [comment]
This has been solved on eProsima/IDL-parser@5933918cf9ad9c29aa6b00c3f669195bc9e6cf8d
