### ISSUE TITLE
support publisher side time-based filtering

### ISSUE THREAD

**Issue by liamstask** [eProsima/Fast-RTPS#24]
the [current manual](http://www.eprosima.com/docs/fast-rtps/1.0.5/pdf/User-Manual.pdf) (section 6.6.1) suggests implementing time-based filtering at the subscriber side.

filtering at the publisher side would be preferable, since that data doesn't need to be put on air at all (which is one of the main benefits of using time-based filtering in the first place).

**Comment by JaimeMartin** [comment]
That's true. But when you are in a radio environment, you are really using "multicast" even if you are sending using ip unicast. So you are always filtering in the subscriber side.

**Comment by johnfinley** [comment]
Good point; if all communications is via radio, it does not matter (for medium load) where the filtering happens.

However, in our system, what we have is (for example) a publisher on the vehicle that publishes messages at a high rate. A subscriber, also on the vehicle, wants those messages at the high rate (and gets them, via loopback network). A subscriber on the ground (over the radio link) wants the messages at a low rate, so in this case we can save downlink bandwidth by filtering at the publisher.

Does that make sense?

**Comment by JaimeMartin** [comment]
There is a mechanism you could use already: The partitions. A Publisher and a subscriber just match if they have a common partition. You could have a partition for high rate, and other for low rate, and two pairs of pub/sub for the same topic.

Another option is to use two different topics.

And last one is two implement published side filtering on the product. We will consider this in our roadmap.

**Comment by johnfinley** [comment]
Thanks Jaime, good ideas!

**Comment by liamstask** [comment]
Sounds good - I think different topics can work for simple cases (which covers ours in the short term).

The downside is that this implies that the publisher must know which rates to publish, whereas the subscriber is the entity that should really be responsible for that info. In any event, not urgent as we can deal with this, but would be a nice feature :)
