### ISSUE TITLE
Qurries about defaultSendPort settings

### ISSUE THREAD

**Issue by zb14zb14** [eProsima/Fast-RTPS#240]
At the publisher side, the PParam.rtps.defaultSendPort = 11511;
while @the subscriber side, the PParam.rtps.defaultSendPort = 10043;  

may I know why the ports are different and what are the rules to set the defaultSendPort?

thx

**Comment by LuisGP** [comment]
Hi @zb14zb14 
The default port at publisher side refers to the port from where the publisher will sent its data.
The same logic applies for the subscriber side.
If you use the same port for both sides on the same machine, you will try to open the same local port twice, and you will fail to open it if you use TCP, for example.
In any case, defaultSendPort parameter will be removed soon, as we are working on TCP support and some changes on the transport layer.

**Comment by richiware** [comment]
If you set defaultSendPort to zero (default value), system will get you a random port to send data (as if you call bind 
with port number to zero).
↪ 2018-07-09 lun 16:18, Luis <notifications@github.com>:

**Comment by MiguelCompany** [comment]
Closing this, as the question has been answered long ago.
