### ISSUE TITLE
fastrtpsgen throws exception on IDL file with union

### ISSUE THREAD

**Issue by anfrox** [eProsima/Fast-RTPS#243]
Hello,
to reproduce the behavior write a IDL file with the content of the documentation and use the tool fastrtpsgen to generate the related C++ code. 
I build used the source code from Github to build Fast-RTPS. The version of fastrtpsgen is 1.6.0.

union Union switch(long)
{
  case 1:
    octet octet_value;
  case 2:
    long long_value;
  case 3:
    string string_value;
};

The console output of the tool fastrtpsgen on my installation look like this:

Loading templates...
Processing the file ... test.idl...
ERROR<Exception>: Can't find template deserializeCasting.st; group hierarchy is [FastCdrCommon]

Kind regards

**Comment by richiware** [comment]
I was able to reproduce your error. I've updated eProsima/Fast-CDR@15f46e820780bd92eaa2d10675b744b67a9ad70e and 
eProsima/Fast-RTPS@30d9bbd7936ee82c762e88180e7b8f609513ddd0 fixing this error. Thanks for the reporting.
↪ 2018-07-25 mié 09:35, anfrox <notifications@github.com>:

**Comment by anfrox** [comment]
Thank you for your prompt reply. The generation of a union-class works fine.

But now it looks link that I need to use option -ppDisable otherwise the tool fastrtpsgen complies about missing preprocessor even if I do not use '#include' statement, see console output below. I use Win7 x64, MSVC 2013 and Java 8.

ERROR<callPreprocessor>: Cannot execute the preprocessor. Reason: Cannot run program "cl.exe": CreateProcess error=2, The system cannot find the file specified.
