### ISSUE TITLE
Symbols in generated xxxPubSubTypes.h files are not exported (on Windows) [4485]

### ISSUE THREAD

**Issue by kannode** [eProsima/Fast-RTPS#244]
Thanks for the nice work on fastrtps. In the below minimal example, the generated PubSubType class has no export macros. Without the relevant export macros, I am unable compile all the fastrtpsgen generated files into a dll. The EPROSIMA_USER_DLL_EXPORT only has an effect when compiling the generated .h and .cxx files and those symbols seem to be exported.  Would it be possible for the generater to add eProsima_user_DllExport  macros to the PubSubTypes as well ?

If this is by design, it would be useful to know the driving arguments. For now I am now resorting to compiling all fastrtpsgen generated files along with multiple executables.

IDL
```
    struct ddschar{
        char val;
    };
```

Generated PubSubtype has no export macros (bad):
```
    class ddscharPubSubType : public eprosima::fastrtps::TopicDataType {
    public:
            typedef ddschar type;

    	ddscharPubSubType();
...
...
    };
```

Generated PubSubtype has eProsima_user_DllExport macros (good):
```
    class ddschar
    {
    public:

        /*!
         * @brief Default constructor.
         */
        eProsima_user_DllExport ddschar();
````

**Comment by LuisGP** [comment]
Hi @kannode 
From #460 these symbols are exported.
