### ISSUE TITLE
ROS2 C++ Re-Created Subscriber Not Listening

### ISSUE THREAD

**Issue by Ipiano** [eProsima/Fast-RTPS#246]
Linked from https://answers.ros.org/question/300339/ros2-c-re-created-subscriber-not-listening/.

I'm seeing the following behavior:
* Start an application 1 that publishes to topic X
* Start an application 2 that subscribes to topic X
* Application 2 destroys the subscription to X
* Application 2 subscribes to X again
* Application 1 dies
* Application 1 starts again
* Application 2 is no longer receiving the data published by Application 1

I expect that when Application 1 starts again and publishes data, it is received by Application 2. If Application 2 never destroys and re-creates its subscription, the test behaves as expected.

The code below is my minimal test case of this behavior using ROS2. The application can be started with any command line arguments to cause it to randomly destroy and re-create its subscriber. 

Switching to the AdLink OpenSplice messaging layer appears to resolve the issue, so it was suggested that this is an issue with FastRTPS, not ROS.

System Details:
* Ubuntu 16.04 Kernel 4.15.0-30-generic
* ROS2 Ardent binaries installed through apt-get

```
int main(int argc, char** argv)
 {
    bool doResets = argc > 1;

    rclcpp::init(argc, argv);
    shared_ptr<rclcpp::Node> node = make_shared<rclcpp::Node>("pub1");

    auto publisher = node->create_publisher<std_msgs::msg::String>("world", 10);
    auto msg = make_shared<std_msgs::msg::String>();

    auto subFunc =
    [](std_msgs::msg::String::ConstSharedPtr str)
    {
        cout << "I heard: " << str->data << endl;
    };

    auto subscriber = node->create_subscription<std_msgs::msg::String>("hello", subFunc);

    auto timer = node->create_wall_timer(1000ms,
    [&]()
    {
        cout << "Publish!" << endl;
        msg->data = "Hello World Pub3";
        publisher->publish(msg);

        if(doResets && rand() % 100 > 80)
        {
            cout << "Rebuild subscriber" << endl;
            subscriber.reset();
            subscriber = node->create_subscription<std_msgs::msg::String>("hello", subFunc);
        }
    });

    rclcpp::spin(node);
    rclcpp::shutdown();
}
```

**Comment by dirk-thomas** [comment]
Please try the same with the latest release - ROS 2 Bouncy - to confirm the problem still exists.

**Comment by Ipiano** [comment]
This appears to be fixed in ROS 2 Bouncy

**Comment by 21coolkarni** [comment]
I am still having this issue with ros2 foxy with fastrtps how can I solve it
