### ISSUE TITLE
support max_blocking_time

### ISSUE THREAD

**Issue by liamstask** [eProsima/Fast-RTPS#25]
`ReliabilityQosPolicy` has a `max_blocking_time` member, but it is marked as 'Not Used in this version'.

This feature would help ensure stale data is not delivered, and reduce bandwidth spent on air trying to deliver retries.

**Comment by JaimeMartin** [comment]
Hi Liam, 

Actually, when the history buffer is full of unacked samples in reliable mode, then the write operation returns false. So no bandwidth use, neither stale data. Max blocking time specifies the time the write operation will block your thread waiting for room in the history cache of the writer when is full. Then, if max_blocking_time elapses the operation fails returning a time out code.

The user can implement a similar behavior just waiting a little bit if the write operation fails and trying again.

**Comment by liamstask** [comment]
I see - sounds like I misunderstood the purpose of `max_blocking_time` :)

The functionality that we're most interested is the following: once a sample has been added to a reliable DataWriter, we'd like to specify the duration of time that the DataWriter should attempt to deliver that sample. (As I understand it, the existing mechanisms to specify the lifetime of that sample are via `History` and `ResourceLimit` qos settings, but nothing specifically time-based.)

How would you recommend we implement such a feature?

**Comment by JaimeMartin** [comment]
There are two ways:

1.- Adding to your data type a field specifying lifespan of the data. The datawriter will try to send the sample, but you can discard the data in the datareader.

2.- Adding this feature to the product. We will consider this in our roadmap.

**Comment by liamstask** [comment]
ok, got it - thanks!
