### ISSUE TITLE
Follow-up of #245: [XMLPARSER] Governance Parser fails on id_range if 'max' tag present but not 'min' tag

### ISSUE THREAD

**Issue by mikaelarguedas** [eProsima/Fast-RTPS#255]
The governance XSD file provide by OMG allows `id_range` to either have:
1. a `min` and a `max` tag
1. a `min` tag only
1. a `max` tag only

```xml
<xs:complexType name="DomainIdRange">
 <!--  DDSSEC-130  -->
  <xs:choice>
    <xs:sequence>
      <xs:element name="min" type="DomainId"/>
      <xs:element name="max" type="DomainId" minOccurs="0"/>
    </xs:sequence>
    <xs:element name="max" type="DomainId"/>
  </xs:choice>
</xs:complexType>
```

Before FastRTPS was supporting only 1) #245. 
With https://github.com/eProsima/Fast-RTPS/pull/252 2) is now supported
3) is still failing ATM

In other words, the following should work:
```xml
            <domains>
              <id_range>
                <max>230</max>
              </id_range>
            </domains>
```

**Comment by MiguelCompany** [comment]
Commit ee8c0a12c0709bf0b6869dbb136ccfd1f9d513e1 should have fixed this.
