### ISSUE TITLE
Latest version of FastRTPS changes some behavior on requests

### ISSUE THREAD

**Issue by clalancette** [eProsima/Fast-RTPS#257]
Commit https://github.com/eProsima/Fast-RTPS/commit/7b2c5b90ce626604b5f8a80b16c946b8d07552f8 broke some of the automated tests on ROS2: https://github.com/ros2/rmw_fastrtps/issues/226 .  There's a full trace of the problem in https://github.com/ros2/rmw_fastrtps/issues/226#issuecomment-420275514, but essentially the test in https://github.com/ros2/rcl/blob/master/rcl/test/rcl/test_client.cpp#L87 is expecting the sequence number to be increased after a call to `Publisher::write`, but that is not happening anymore.  I'm not sure if this is a problem with what the test is expecting, or with the recent change to Fast-RTPS.  @richiprosima , @richiware , @MiguelCompany , can you take a look?  Thanks.

**Comment by richiware** [comment]
PR #258 was opened to solve this issue.

**Comment by clalancette** [comment]
Fixed now with #258, closing.  Thanks!
