### ISSUE TITLE
fastrtpsgen generates inconsistent representation of IDL type 'char' [4483]

### ISSUE THREAD

**Issue by anfrox** [eProsima/Fast-RTPS#260]
As far as the IDL type 'char' should be related to an 8-bit signed integer in C++, then the generated code could be incorrect. On some compilers a char will be interpreted as signed int or as a unsigned type.
To be consistent it would be helpful to use standard integer types, so IDL char gets typedef-ed as std::int8_t.

**Comment by LuisGP** [comment]
Hi @anfrox 

In the [C++11 Language Mapping](https://www.omg.org/spec/CPP11/1.3/PDF) document from the OMG the IDL type `char` must be mapped to the C++ type `char`.
