### ISSUE TITLE
Setting security properties from profile XML file [4075]

### ISSUE THREAD

**Issue by ruffsl** [eProsima/Fast-RTPS#263]
I'd like to set some properties using the `DEFAULT_FASTRTPS_PROFILES.xml` file. Specifically I'd like to set some security properties to configure Secure DDS without doing so programatickly. For example, in FastRTPS how does one set file path for this attribute from the profile xml file:

`dds.sec.auth.plugin`, `builtin.PKI-DH`
`dds.sec.crypto.plugin`, `builtin.AES-GCM-GMAC`
`dds.sec.access.plugin`, `builtin.Access-Permissions`
`dds.sec.auth.builtin.PKI-DH.identity_ca`
`dds.sec.auth.builtin.PKI-DH.identity_certificate`
`dds.sec.auth.builtin.PKI-DH.private_key`
`dds.sec.access.builtin.Access-Permissions.permissions_ca`
`dds.sec.access.builtin.Access-Permissions.governance`
`dds.sec.access.builtin.Access-Permissions.permissions`

http://docs.eprosima.com/en/latest/security.html#example-configuring-the-participant

In RTI Connext, this can be done using the name value syntax under the property tag.  
What is the analog equivalent in FastRTPS for this:

``` xml
<?xml version="1.0"?>
<dds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://community.rti.com/schema/5.3.1/rti_dds_qos_profiles.xsd"
    version="5.3.1">
    <qos_library name="SecurityExampleProfiles">
        <qos_profile name="A" base_name="BuiltinQosLib::Generic.Security" is_default_qos="true">
          <participant_qos>
            <property>
              <value>
                <element>
                  <name>com.rti.serv.secure.authentication.ca_file</name>
                  <value>../../../dds_security/cert/cacertECdsa.pem</value>
                </element>
                <element>
                  <name>com.rti.serv.secure.authentication.certificate_file</name>
                  <value>../../../dds_security/cert/peer1ECdsa.pem</value>
                </element>
                <element>
                  <name>com.rti.serv.secure.authentication.private_key_file</name>
                  <value>../../../dds_security/cert/peer1keyECdsa.pem</value>
                </element>
                <element>
                  <name>com.rti.serv.secure.access_control.permissions_authority_file</name>
                  <value>../../../dds_security/cert/cacertECdsa.pem</value>
                </element>
                <element>
                  <name>com.rti.serv.secure.access_control.governance_file</name>
                  <value>../../../dds_security/xml/signed/signed_Governance.p7s</value>
                </element>
                <element>
                  <name>com.rti.serv.secure.access_control.permissions_file</name>
                  <value>../../../dds_security/xml/signed/signed_PermissionsA.p7s</value>
                </element>
                <element>
                  <name>com.rti.serv.load_plugin</name>
                  <value>com.rti.serv.secure</value>
                </element>
                <element>
                  <name>com.rti.serv.secure.library</name>
                  <value>nddssecurity</value>
                </element>
                <element>
                  <name>com.rti.serv.secure.create_function</name>
                  <value>RTI_Security_PluginSuite_create</value>
                </element>
              </value>
            </property>
          </participant_qos>
        </qos_profile>
    </qos_library>
</dds>
```

**Comment by ruffsl** [comment]
Digging through the unit tests, I think I found my example:

https://github.com/eProsima/Fast-https://github.com/eProsima/Fast-RTPS/blob/017dfec913980bd93432f3a5fceb1475b31e3c8e/test/unittest/xmlparser/test_xml_security_profiles.xml#L4-L12

**Comment by richiware** [comment]
Sorry for the delay. I'm glad you find it. We realize this information isn't in our readthedocs. We will solve it. Close the issue if the example works for you. Thanks.

**Comment by ruffsl** [comment]
@richiware , I'm trying to secure a micro-RTPS-agent, but think I'm encountering an issue when I try and start a micro-RTPS-client on the same machine using the profile xml at the bottom \<details> . Given that DDS-XRC makes no mention on security, I was thinking of forcing a profile for the agent as to use security for only the interfaces that are not the local loopback interface. Is this feasible using something like the locacort lists?

``` shell
$ MicroRTPSAgent udp 2018
UDP agent initialization... OK
[SECURITY Error] Error validating the local participant identity. () -> Function init
[RTPS_PARTICIPANT Error] Cannot create participant due to security initialization error -> Function createParticipant
[PARTICIPANT Error] Problem creating RTPSParticipant -> Function createParticipant
```

https://github.com/eProsima/Fast-RTPS/blob/017dfec913980bd93432f3a5fceb1475b31e3c8e/test/unittest/xmlparser/test_xml_profiles.xml#L6-L26

<details>

``` xml
<profiles>
  <participant profile_name="default_xrce_participant_profile">
    <rtps>
      <builtin>
        <leaseDuration>
          <durationbyname>INFINITE</durationbyname>
        </leaseDuration>
        <domainId>0</domainId>
      </builtin>
      <name>turtlebot3_core</name>
      <propertiesPolicy>
      <properties>
        <property>
          <name>dds.sec.auth.plugin</name>
          <value>builtin.PKI-DH</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>dds.sec.crypto.plugin</name>
          <value>builtin.AES-GCM-GMAC</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>dds.sec.access.plugin</name>
          <value>builtin.Access-Permissions</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>dds.sec.auth.builtin.PKI-DH.identity_ca</name>
          <value>keymint_ws/install/turtlebot3_core/ca.cert.pem</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>dds.sec.auth.builtin.PKI-DH.identity_certificate</name>
          <value>keymint_ws/install/turtlebot3_core/cert.pem</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>dds.sec.auth.builtin.PKI-DH.private_key</name>
          <value>keymint_ws/install/turtlebot3_core/key.pem</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>dds.sec.access.builtin.Access-Permissions.permissions_ca</name>
          <value>keymint_ws/install/turtlebot3_core/ca.cert.pem</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>dds.sec.access.builtin.Access-Permissions.governance</name>
          <value>keymint_ws/install/turtlebot3_core/governance.p7s</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>dds.sec.access.builtin.Access-Permissions.permissions</name>
          <value>keymint_ws/install/turtlebot3_core/permissions.p7s</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>rtps.endpoint.submessage_protection_kind</name>
          <value>ENCRYPT</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>rtps.endpoint.payload_protection_kind</name>
          <value>ENCRYPT</value>
          <propagate>true</propagate>
        </property>
      </properties>
    </propertiesPolicy>
    </rtps>
  </participant>
</profiles>
```

**Comment by richiware** [comment]
@ruffsl Do you still have this error with new micro-XRCE-DDS-agent?

About your question. Security is done in an upper layer. Security and network transport low level layer doesn't know each other. You cannot do that. Security will go through all interfaces.

**Comment by ruffsl** [comment]
> @ruffsl Do you still have this error with new micro-XRCE-DDS-agent?

I haven't tested this against the latest branches yet, but if I have some spare time I'll try again soon.

> About your question. Security is done in an upper layer. Security and network transport low level layer doesn't know each other. You cannot do that. Security will go through all interfaces.

How exactly is an agent mediating traffic between the clients and the rest of the DDS domain on the RTPS level? My impression was that the agent is a bridge among neighboring XRCE-DDS client peers and a bridge between any XRCE-DDS client and an external DDS participants.

Though the clients themselves would be incapable of negotiating a Secure-DDS security handshake, I'd would've expected that the agent could conduct this upon the clients behalf; using its own bestowed permissions to negotiate external connections, checking the payload signatures deciphering before before forwarding received messages to the client, or ciphering and signing payloads from the client before forwarding them to the DDS network.

Would this necessitate the use of the relay permission? I would immediately think so, given one side of the 'relay' (agent) isn't even security cognisant. It not like any of the clients could decipher a 'relayed' ciphertext.

**Comment by richiware** [comment]
About your XML profile file I've detected that security is incorrectly configured. When the value of a security property is a file, example a PEM file, the URI has to contain `file://` at the beginning.

```xml
        <property>
          <name>dds.sec.auth.builtin.PKI-DH.identity_ca</name>
          <value>file://keymint_ws/install/turtlebot3_core/ca.cert.pem</value>
          <propagate>true</propagate>
        </property>
```

<details>

```xml
<profiles>
  <participant profile_name="default_xrce_participant_profile">
    <rtps>
      <builtin>
        <leaseDuration>
          <durationbyname>INFINITE</durationbyname>
        </leaseDuration>
        <domainId>0</domainId>
      </builtin>
      <name>turtlebot3_core</name>
      <propertiesPolicy>
      <properties>
        <property>
          <name>dds.sec.auth.plugin</name>
          <value>builtin.PKI-DH</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>dds.sec.crypto.plugin</name>
          <value>builtin.AES-GCM-GMAC</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>dds.sec.access.plugin</name>
          <value>builtin.Access-Permissions</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>dds.sec.auth.builtin.PKI-DH.identity_ca</name>
          <value>file://keymint_ws/install/turtlebot3_core/ca.cert.pem</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>dds.sec.auth.builtin.PKI-DH.identity_certificate</name>
          <value>file://keymint_ws/install/turtlebot3_core/cert.pem</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>dds.sec.auth.builtin.PKI-DH.private_key</name>
          <value>file://keymint_ws/install/turtlebot3_core/key.pem</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>dds.sec.access.builtin.Access-Permissions.permissions_ca</name>
          <value>file://keymint_ws/install/turtlebot3_core/ca.cert.pem</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>dds.sec.access.builtin.Access-Permissions.governance</name>
          <value>file://keymint_ws/install/turtlebot3_core/governance.p7s</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>dds.sec.access.builtin.Access-Permissions.permissions</name>
          <value>file://keymint_ws/install/turtlebot3_core/permissions.p7s</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>rtps.endpoint.submessage_protection_kind</name>
          <value>ENCRYPT</value>
          <propagate>true</propagate>
        </property>
        <property>
          <name>rtps.endpoint.payload_protection_kind</name>
          <value>ENCRYPT</value>
          <propagate>true</propagate>
        </property>
      </properties>
    </propertiesPolicy>
    </rtps>
  </participant>
</profiles>
```

</details>

**Comment by ruffsl** [comment]
> This can be done. You can configure the agent to use security in the DDS world. All DDS entities created in the agent by the clients will use security when sending data to DDS world.

When you have time, I think providing such an example using micro-XRCE-DDS-agent that folks could study would be helpful, and make it more straight forward to reproduce.

> What I understood with this sentence is you want to send secure data through network interfaces and non-secure data through localhost interface. But Fast-RTPS cannot do this. If you configure a secure publisher, it will send secure data through all interfaces.

If what you said in the previous paragraph is possible, having the agent speak Secure DDS on it's own clients' behave, then this is no longer an issue. Still, I thought it was perfectly possible to limit a DDS participant to only use a given set of network interfaces; e.g. having it use eth0 and never wlan1, etc.

**Comment by richiware** [comment]
Use a subset of network interfaces is allowed by Fast RTPS. You have to configure the transport with a whitelist. This whitelist will specify what network interfaces will be used. More information in this [link](https://eprosima-fast-rtps.readthedocs.io/en/latest/advanced.html#whitelist-interfaces)

**Comment by LuisGP** [comment]
As this was answered and no comments were received, we close the issue. Feel free to reopen if there is more clarification needed.
