### ISSUE TITLE
SequenceNumber.h

### ISSUE THREAD

**Issue by johnfinley** [eProsima/Fast-RTPS#27]
I think [SequenceNumber.h](https://github.com/eProsima/Fast-RTPS/blob/master/include/fastrtps/rtps/common/SequenceNumber.h) needs a review. At lines 79 and 87, the compares to pow(2.0,32) will always be false and incrementing beyond 32 bits won't work. At line 100, the LHS of the > will be done with 32 bits (then promoted to double) so that test will always be false. At line  102, 'module' will always be zero (due to integer overflow). I think some of the later operators also suffer similar problems.

I have not seen any of this cause any problems (it would take a while :) ), but just ran across it looking for other issues.

**Comment by richiprosima** [comment]
[SequenceNumber.h](https://github.com/eProsima/Fast-RTPS/blob/master/include/fastrtps/rtps/common/SequenceNumber.h) was changed and now it doesn't use [pow](http://en.cppreference.com/w/cpp/numeric/math/pow) function.
