### ISSUE TITLE
Compiling FastRTPS for QNX neutrino 

### ISSUE THREAD

**Issue by suneeshs** [eProsima/Fast-RTPS#272]
I am having some trouble compiling FastRTPS for QNX. ‘fastcdr’ builds but compiling ‘fastrtps’ errors out complaining about asio related issues. I noticed that you have listed QNX as one of the platforms for which FastRTPS has been built so wanted to check if I am missing something.

I am cross compiling through CMAKE using a QNX toolchain file. The workflow is described in the PDF file that is in the attached ZIP file. It also contains the toolchain file that I am using. Any help is appreciated, please let me know if you need any more information.
[FastRTPS_QNX_build_issue.zip](https://github.com/eProsima/Fast-RTPS/files/2461505/FastRTPS_QNX_build_issue.zip)

**Comment by seancx** [comment]
Add flag -stdlib=libstdc++, you may solve this problem.

**Comment by suneeshs** [comment]
> Hi @suneeshs,
> 
> I found someone with an issue compiling with asio that seems similar to your issue.
> 
> https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=224130#c3
> 
> They seem to have fixed the issue by upgrading to boost 1.67 (which includes asio 1.12.1)
> 
> Fast-RTPS is using asio [1.12.0](https://github.com/chriskohlhoff/asio/tree/asio-1-12-0). When the next asio version is released as requested on [chriskohlhoff/asio#309](https://github.com/chriskohlhoff/asio/issues/309), we will update our submodule.
> 
> I hope you can go on with Fast-RTPS with this information.

Unfortunately not. I have not yet tried using boost 1.67 with Fast-RTPS 1.6.0 yet. Instead I tried updating the ASIO library in thirdparty to the source code from "asio version 1.12.1 Released Sunday, 15 April 2018."  https://github.com/chriskohlhoff/asio/tree/master/asio and see the same issue.

**Comment by darbee** [comment]
> https://github.com/chriskohlhoff/asio/tree/master/asio

hi @suneeshs have you solved the problem? Now I also want to cross compile  FastRTPS  for QNX. But I download the FastRTPS at http://www.eprosima.com/index.php?option=com_ars&view=browses&layout=normal. There is not a CMakeList.txt, instead a configure.

**Comment by darbee** [comment]
Hi suneeshs @suneeshs  and hi all you should add -DTHIRDPARTY=ON to you cross compile. it solved fastcdr problem. But it report a error: 
/home/caros/Documents/qnx_lib/qnx-lib/fast-rtps/Fast-RTPS/src/cpp/utils/eClock.cpp: In static member function 'static void eprosima::fastrtps::eClock::my_sleep(uint32_t)':
/home/caros/Documents/qnx_lib/qnx-lib/fast-rtps/Fast-RTPS/src/cpp/utils/eClock.cpp:100:26: error: 'usleep' was not declared in this scope
  usleep(milliseconds*1000);

**Comment by suneeshs** [comment]
> Add flag -stdlib=libstdc++, you may solve this problem.

This helped with the compile issue. Thanks!

**Comment by suneeshs** [comment]
I was able to proceed compiling using @seancx  's suggestion of adding "-stdlib=libstdc++". However, now I am seeing an error while linking libfastrtps.so:

[ 97%] Building C object src/cpp/CMakeFiles/fastrtps.dir/rtps/persistence/sqlite3.c.o
[ 98%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/__/__/thirdparty/tinyxml2/tinyxml2.cpp.o
[ 99%] Linking CXX shared library libfastrtps.so
: Invalid argumentn64\x86_64\usr\bin\x86_64-pc-nto-qnx7.0.0-ld: cannot find CMakeFiles/fastrtps.dir/__/__/thirdparty/tinyxml2/tinyxml2.cpp.o
cc: c:/qnx700//host/win64/x86_64/usr/bin/x86_64-pc-nto-qnx7.0.0-ld caught signal 1
gmake[2]: *** [src/cpp/libfastrtps.so.1.6.0] Error 1
gmake[1]: *** [src/cpp/CMakeFiles/fastrtps.dir/all] Error 2
gmake.exe: *** [all] Error 2

**Comment by richiware** [comment]
Thanks for your help and collaboration. Currently we don't support officially QNX. We are working to make it officially in future versions. All contributions are appreciated.

**Comment by jilinzhou** [comment]
@richiware : Welcome. Found some old notes and re-run the compilation. Luckily It still works.

Here they are:

1. check out code

```
git clone https://github.com/eProsima/Fast-RTPS.git
cd Fast-RTPS
git checkout release/1.4.0
git submodule init
git submodule update
```

2. patch asio as shown above

```
Index: boost/asio/detail/impl/socket_ops.ipp
===================================================================
--- boost/asio/detail/impl/socket_ops.ipp	(revision 843663)
+++ boost/asio/detail/impl/socket_ops.ipp	(working copy)

       call_setsockopt(&msghdr::msg_namelen, s,
           SOL_SOCKET, SO_REUSEPORT, optval, optlen);
     }
+#else //QNX
+      call_setsockopt(&msghdr::msg_namelen, s,
+          SOL_SOCKET, SO_REUSEPORT, optval, optlen);
 #endif
   }
```

3. Generate makefiles and build
```
cd Fast-RTPSs
mkdir build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=/home/jilin/Downloads/fast_rtps_aarch64le_Toolchain.cmake -DCMAKE_INSTALL_PREFIX=/usr -DTHIRDPARTY=ON -DCMAKE_BUILD_TYPE=Release -DCOMPILE_EXAMPLES=OFF -DCMAKE_SHARED_LINKER_FLAGS=-lsocket ..
make -j4
```

You should see the following at the end:

```
[100%] Linking CXX shared library libfastrtps.so
[100%] Built target fastrtps
```
[fast_rtps_aarch64le_Toolchain.cmake.txt](https://github.com/eProsima/Fast-RTPS/files/2561845/fast_rtps_aarch64le_Toolchain.cmake.txt)

**Comment by darbee** [comment]
HI jilinzhou  @jilinzhou 

> for QNX SDP 7, by default it is linked to libc++. If you specify -stdlib=libstdc++, it will link to libstdc++. If your project needs a lot of third party libs, make sure they are all linked to the same c++ libs. Otherwise, you will see unexpected crashes in runtime

Just as you say, my project depend protobuf indeed. I need it is  linked to the libstdc++. But It failed. It seem that protobuf do not support flag  libstdc++. https://github.com/protocolbuffers/protobuf/issues/2945

**Comment by suneeshs** [comment]
I was able to get the HelloWorld program to run between my QNX machine and a Windows machine while using unicast (just have not had the time to try multicast discovery yet). So I consider this issue closed. To summarize, the changes I needed to make were:
1.  Add flag -stdlib=libstdc++ (thanks @seancx )
2. I did need to make some manual changes to the CMAKE generated build.make files and this is something I will need to address soon:
In the generated file: src\cpp\CMakeFiles\fastrtps.dir\build.make there is a command that does "Linking CXX shared library CMakeFiles/CMakeRelink.dir/libfastrtps.so". This command uses the object file list from src/cpp/CMakeFiles/fastrtps.dir/objects1.rsp. However, for my QNX build this did not work for some reason. I replaced the argument @CMakeFiles/fastrtps.dir/objects1.rsp with a list of the .o files and was able to proceed.

**Comment by darbee** [comment]
Hi, @jilinzhou, I have compile the fast rtps for qnx. And start it with a very simple example found at:
https://github.com/eProsima/Fast-RTPS/tree/master/examples/C%2B%2B/HelloWorldExample
But They can not communicate with each other. are there anything needed to set? I run all the node in the QNX.

The ifconfig output is
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 33136 inet 127.0.0.1 netmask 0xff000000 inet6 ::1 prefixlen 128 inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 ravb0: flags=8a43<UP,BROADCAST,RUNNING,ALLMULTI,SIMPLEX,MULTICAST> mtu 1500 address: 4a:3b:83:03:38:36 media: Ethernet autoselect (1000baseT full-duplex) status: active inet 172.20.102.35 netmask 0xffffff00 broadcast 172.20.102.255 inet6 fe80::483b:83ff:fe03:3836%ravb0 prefixlen 64 scopeid 0x11

**Comment by darbee** [comment]
append:
 the netstat -g output is:
root@~# netstat -g
`Virtual Interface Table is empty

Multicast Forwarding Cache is empty


IPv6 Multicast Interface Table is empty

IPv6 Multicast Routing Table is empty`


the nicinfo output is

`root@# nicinfo en0
en0:`

**Comment by jilinzhou** [comment]
@darbee : Cannot remember I ever run those examples. I suggest you enable logging and debug from there. Take a closer look of its CMakelist.txt and figure out all possible configurable parameters. Here are some related to logging: 

1. To build libfastrtps in debug mode, use -DCMAKE_BUILD_TYPE=Debug

2. To enable libfastrtps internal logging, use -DINTERNAL_DEBUG=ON

3. In any test program, in main.cc, set verbosity level
Log::SetVerbosity(Log::Kind::Info);

4. by default, all log messages go to console.

**Comment by jilinzhou** [comment]
@darbee :  Of course, it is not the log level problem. However looking at internal log messages help you find the root cause.

**Comment by suneeshs** [comment]
> Hi, @jilinzhou, I have compile the fast rtps for qnx. And start it with a very simple example found at:
> https://github.com/eProsima/Fast-RTPS/tree/master/examples/C%2B%2B/HelloWorldExample
> But They can not communicate with each other. are there anything needed to set? I run all the node in the QNX.
> 
> The ifconfig output is
> lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 33136 inet 127.0.0.1 netmask 0xff000000 inet6 ::1 prefixlen 128 inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 ravb0: flags=8a43<UP,BROADCAST,RUNNING,ALLMULTI,SIMPLEX,MULTICAST> mtu 1500 address: 4a:3b:83:03:38:36 media: Ethernet autoselect (1000baseT full-duplex) status: active inet 172.20.102.35 netmask 0xffffff00 broadcast 172.20.102.255 inet6 fe80::483b:83ff:fe03:3836%ravb0 prefixlen 64 scopeid 0x11

I did have to add initial peers. Probably something you could try:
For example in HelloWorldPublisher::init() I added:

    loc_initial_peer.set_IP4_address(127, 0, 0, 1);
    loc_initial_peer.port = 7610;
    PParam.rtps.builtin.initialPeersList.push_back(loc_initial_peer);
    
    loc_initial_peer_host.set_IP4_address(192, 168, 10,3);
    loc_initial_peer_host.port = 7610;
    PParam.rtps.builtin.initialPeersList.push_back(loc_initial_peer_host);

**Comment by darbee** [comment]
@suneeshs  thanks you , I will try your suggestion. Soon I will tell you the result

**Comment by darbee** [comment]
@jilinzhou  I want to cry. Why I can not get the output like you? Is there are some thing wrong with my QNX? I will listen to you to modify the  log level to see the reason. 
 By the way , can you tell me the output of " netstat -g " of you qnx machine?

**Comment by darbee** [comment]
the debug log is :
`[RTPS_READER Info] Sending ACKNACK: 2: -> Function event
[RTPS_MSG_IN Info] (ID:4) InfoDST message received, processing... -> Function processCDRMsg
[RTPS_MSG_IN Info] (ID:4) DST RTPSParticipant is now: 1.f.66.23.1c.40.45.0.0.0.0.0 -> Function proc_Submsg_InfoDST
[RTPS_MSG_IN Info] (ID:4) HB Submsg ignored, DST is another RTPSParticipant... -> Function processCDRMsg
[RTPS_MSG_OUT Info] UDPv4: 64 bytes TO endpoint: 172.20.102.35:7410 FROM 0.0.0.0:65438 -> Function SendThroughSocket
[RTPS_MSG_OUT Info] SENT 64 -> Function SendThroughSocket
[RTPS_MSG_IN Info] (ID:5) InfoDST message received, processing... -> Function processCDRMsg
[RTPS_MSG_OUT Info] UDPv4: 64 bytes TO endpoint: 239.255.0.1:7400 FROM 0.0.0.0:65438 -> Function SendThroughSocket
[RTPS_MSG_IN Info] (ID:5) DST RTPSParticipant is now: 1.f.66.23.1c.40.45.0.0.0.0.0 -> Function proc_Submsg_InfoDST
[RTPS_MSG_IN Info] (ID:5) Acknack Submsg ignored, DST is another RTPSParticipant... -> Function processCDRMsg
[RTPS_MSG_OUT Info] SENT 64 -> Function SendThroughSocket
[RTPS_MSG_IN Info] (ID:4) InfoDST message received, processing... -> Function processCDRMsg
[RTPS_MSG_IN Info] (ID:4) DST RTPSParticipant is now: 1.f.66.23.1c.40.45.0.0.0.0.0 -> Function proc_Submsg_InfoDST
[RTPS_MSG_IN Info] (ID:4) Acknack Submsg ignored, DST is another RTPSParticipant... -> Function processCDRMsg
[RTPS_MSG_IN Info] (ID:5) InfoDST message received, processing... -> Function processCDRMsg
[RTPS_MSG_IN Info] (ID:5) DST RTPSParticipant is now: 1.f.66.23.21.50.45.0.0.0.0.0 -> Function proc_Submsg_InfoDST
[RTPS_MSG_IN Info] (ID:5) Acknack Submsg received, processing... -> Function processCDRMsg
[RTPS_WRITER Info] Requested Changes: 1  -> Function requested_changes_set
[RTPS_MSG_IN Info] (ID:4) InfoDST message received, processing... -> Function processCDRMsg
[RTPS_MSG_IN Info] (ID:4) DST RTPSParticipant is now: 1.f.66.23.21.50.45.0.0.0.0.0 -> Function proc_Submsg_InfoDST
[RTPS_MSG_IN Info] (ID:4) Acknack Submsg received, processing... -> Function processCDRMsg
[RTPS_WRITER Info] Responding to Acknack msg -> Function event
[RTPS_WRITER Info] Sending relevant changes as DATA/DATA_FRAG messages -> Function add_data
[RTPS_WRITER Info] Sending INFO_TS message -> Function add_info_ts_in_buffer
[RTPS_MSG_OUT Info] UDPv4: 328 bytes TO endpoint: 127.0.0.1:7410 FROM 0.0.0.0:65438 -> Function SendThroughSocket
[RTPS_WRITER Info] Changing underway to unacked for Reader: 1.f.66.23.1c.40.45.0.0.0.0.0|0.0.4.c7 -> Function event
[RTPS_MSG_OUT Info] SENT 328 -> Function SendThroughSocket
[RTPS_WRITER Info] Finish sending unsent changes -> Function send_any_unsent_changes
[RTPS_MSG_IN Info] (ID:5) InfoDST message received, processing... -> Function processCDRMsg
[RTPS_MSG_IN Info] (ID:5) DST RTPSParticipant is now: 1.f.66.23.1c.40.45.0.0.0.0.0 -> Function proc_Submsg_InfoDST
[RTPS_MSG_IN Info] (ID:5) InfoTS Submsg received, processing... -> Function processCDRMsg
[RTPS_MSG_IN Info] (ID:5) Data Submsg ignored, DST is another RTPSParticipant -> Function processCDRMsg`

**Comment by darbee** [comment]
And again @jilinzhou   ilinzhou. Can you offer me your libs such as  libfastcdr.so  libfastcdr.so.1.0.7  libfastrtps.so  libfastrtps.so.1  libfastrtps.so.1.6.0 and your executable file HelloWorldExample？ Using these files  ,  I can find out 
1. if my compiled libs have problems or 
2. my example may don't work or
3 my qnx system env has something wrong.

When I first run 
`./HelloWorldExample publisher`

and then 
`./HelloWorldExample subscriber`

it will output 
`Subscriber matched`
But Don't ouput anything.

When I first run 
``./HelloWorldExample subscriber``

and then 
`./HelloWorldExample publisher`

It will output 
`Publisher matched
Message: HelloWorld with index: 1 SENT
Message: HelloWorld with index: 2 SENT
Message: HelloWorld with index: 3 SENT
Message: HelloWorld with index: 4 SENT
Message: HelloWorld with index: 5 SENT
Message: HelloWorld with index: 6 SENT
Message: HelloWorld with index: 7 SENT
Message: HelloWorld with index: 8 SENT
Message: HelloWorld with index: 9 SENT
Message: HelloWorld with index: 10 SENT`

But  subscriber output nothing.

It is very strange for me.

Please accept my deepest thanks jilinzhou.

**Comment by darbee** [comment]
Index: boost/asio/detail/impl/socket_ops.ipp
===================================================================
--- boost/asio/detail/impl/socket_ops.ipp	(revision 843663)
+++ boost/asio/detail/impl/socket_ops.ipp	(working copy)

       call_setsockopt(&msghdr::msg_namelen, s,
           SOL_SOCKET, SO_REUSEPORT, optval, optlen);
     }
+#else //QNX
+      call_setsockopt(&msghdr::msg_namelen, s,
+          SOL_SOCKET, SO_REUSEPORT, optval, optlen);
 #endif
   }

except this file , any other file have you changed for qnx @jilinzhou ? By the way , I don't find the boost/asio/detail/impl/socket_ops.ipp

I only find a file named socket_ops.ipp at
thirdparty/asio/asio/include/asio/detail/impl/socket_ops.ipp

**Comment by jilinzhou** [comment]
> # boost/asio/detail/impl/socket_ops.ipp
> 
> --- boost/asio/detail/impl/socket_ops.ipp (revision 843663)
> +++ boost/asio/detail/impl/socket_ops.ipp (working copy)
> 
> ```
>    call_setsockopt(&msghdr::msg_namelen, s,
>        SOL_SOCKET, SO_REUSEPORT, optval, optlen);
>  }
> ```
> 
> +#else //QNX
> 
>     * ```
>        call_setsockopt(&msghdr::msg_namelen, s,
>       ```
> 
>     * ```
>            SOL_SOCKET, SO_REUSEPORT, optval, optlen);
>       ```
> 
> 
> #endif
> }
> 
> except this file , any other file have you changed for qnx @jilinzhou ? By the way , I don't find the boost/asio/detail/impl/socket_ops.ipp
> 
> I only find a file named socket_ops.ipp at
> thirdparty/asio/asio/include/asio/detail/impl/socket_ops.ipp

That is the only file I changed.

**Comment by darbee** [comment]
Hmmm. Interesting, still does't work.. @jilinzhou . Would you mind giving me a copy of the code of your version (fast rtps).Although  I follow your steps and instructions to build the project
`git clone https://github.com/eProsima/Fast-RTPS.git
cd Fast-RTPS
git checkout release/1.4.0
git submodule init
git submodule update`
but I didn't get your results. Maybe this is the last way to help me to figure out what's wrong with my code.This may not seem very polite,But I've spent about a week on it.... I searched the whole network, there is nothing about qnx and fast rtps.  You are my last hope, kind man..

**Comment by jilinzhou** [comment]
@darbee Sorry, I cannot pass you the code but it should be exactly the same as yours. Are you using the toolchain file I uploaded?  Are you linking it with libstdc++ or libc++? Use _ntoaarch64-objdump -p_ to show that.

**Comment by darbee** [comment]
@jilinzhou  yes,I use your  toolchain file, and it link with libc++ . here is my objdump result:
`HelloWorldExample:     file format elf64-littleaarch64`
`Dynamic Section:
  NEEDED               libfastrtps.so.1
  NEEDED               libfastcdr.so.1.0.7
  NEEDED               libc++.so.1
  NEEDED               libm.so.3
  NEEDED               libc.so.4`


`build/src/cpp/libfastrtps.so:     file format elf64-littleaarch64`
`Dynamic Section:
  NEEDED               libsocket.so.3
  NEEDED               libfastcdr.so.1.0.7
  NEEDED               libc++.so.1
  NEEDED               libm.so.3
  NEEDED               libc.so.4
  SONAME               libfastrtps.so.1`

`build/thirdparty/fastcdr/src/cpp/libfastcdr.so:     file format elf64-littleaarch64`
`Dynamic Section:
  NEEDED               libsocket.so.3
  NEEDED               libc++.so.1
  NEEDED               libm.so.3
  NEEDED               libc.so.4
  SONAME               libfastcdr.so.1.0.7`

By the way  why In you project, there is a boost path,boost/asio/detail/impl/socket_ops.ipp
but mine is thirdparty/asio/asio/include/asio/detail/impl/socket_ops.ipp

**Comment by darbee** [comment]
Hi @jilinzhou  thanks again, I have work it out. On the basis of your help,  I change the socket_ops.ipp file. But instead using 
`+#else //QNX
+      call_setsockopt(&msghdr::msg_namelen, s,
+          SOL_SOCKET, SO_REUSEPORT, optval, optlen);`

**Comment by jilinzhou** [comment]
> Hi @jilinzhou thanks again, I have work it out. On the basis of your help, I change the socket_ops.ipp file. But instead using
> 
> ` else //QNX call_setsockopt(&msghdr::msg_namelen, s, SOL_SOCKET, SO_REUSEPORT, optval, optlen);`
> 
> I change the code
> from
> `|| defined(__NetBSD__) || defined(__FreeBSD__) || defined(__OpenBSD__)`
> to
> `|| defined(__NetBSD__) || defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__QNX__)`
> Thank you again for your tireless help. I can't solve this problem without you！

glad that you figured it out. My diff for socket_ops.ipp was generated in somewhere else. The way you are doing it is supposed to be.

**Comment by darbee** [comment]
Aha, That is how it is. Anyway, thank you very much for your selfless help.

**Comment by anup-pem** [comment]
Came across the following issue while compiling Fast-RTPS on QNX 7.0 with libc++

```
eProsima/Fast-RTPS/thirdparty/asio/asio/include/asio/detail/handler_alloc_helpers.hpp:169:26: error: 'struct std::__1::allocator_traits<asio::detail::hook_allocator<std::__1::__bind<void (eprosima::fastrtps::rtps::ResourceEvent::*)(), eprosima::fastrtps::rtps::ResourceEvent*>, void> >::rebind_alloc<asio::detail::completion_handler<std::__1::__bind<void (eprosima::fastrtps::rtps::ResourceEvent::*)(), eprosima::fastrtps::rtps::ResourceEvent*> > >' has no member named 'allocate'

       return a.allocate(1);
```

Since QNX libc++ is at 3.7 it does not yet support TEMPLATE_ALIASES. Created the  patch file [fast_rtps_asio.patch.gz](https://github.com/eProsima/Fast-RTPS/files/2651070/fast_rtps_asio.patch.gz) to fix the issue

**Comment by jilinzhou** [comment]
@anup-pem : It works fine with me. Take a look of 2nd listed feature as the following

```
jilin@jilin-Precision-3520 CMakeFiles (release/1.4.0) $ strings feature_tests.bin | grep FEATURE
CXX_FEATURE:0cxx_aggregate_default_initializers
CXX_FEATURE:0cxx_alias_templates
CXX_FEATURE:0cxx_alignas
CXX_FEATURE:0cxx_alignof
CXX_FEATURE:0cxx_attributes
CXX_FEATURE:0cxx_attribute_deprecated
CXX_FEATURE:0cxx_auto_type
CXX_FEATURE:0cxx_binary_literals
CXX_FEATURE:0cxx_constexpr
CXX_FEATURE:0cxx_contextual_conversions
CXX_FEATURE:0cxx_decltype
CXX_FEATURE:0cxx_decltype_auto
CXX_FEATURE:0cxx_decltype_incomplete_return_types
CXX_FEATURE:0cxx_default_function_template_args
CXX_FEATURE:0cxx_defaulted_functions
CXX_FEATURE:0cxx_defaulted_move_initializers
CXX_FEATURE:0cxx_delegating_constructors
CXX_FEATURE:0cxx_deleted_functions
CXX_FEATURE:0cxx_digit_separators
CXX_FEATURE:0cxx_enum_forward_declarations
CXX_FEATURE:0cxx_explicit_conversions
CXX_FEATURE:0cxx_extended_friend_declarations
CXX_FEATURE:0cxx_extern_templates
CXX_FEATURE:0cxx_final
CXX_FEATURE:0cxx_func_identifier
CXX_FEATURE:0cxx_generalized_initializers
CXX_FEATURE:0cxx_generic_lambdas
CXX_FEATURE:0cxx_inheriting_constructors
CXX_FEATURE:0cxx_inline_namespaces
CXX_FEATURE:0cxx_lambdas
CXX_FEATURE:0cxx_lambda_init_captures
CXX_FEATURE:0cxx_local_type_template_args
CXX_FEATURE:0cxx_long_long_type
CXX_FEATURE:0cxx_noexcept
CXX_FEATURE:0cxx_nonstatic_member_init
CXX_FEATURE:0cxx_nullptr
CXX_FEATURE:0cxx_override
CXX_FEATURE:0cxx_range_for
CXX_FEATURE:0cxx_raw_string_literals
CXX_FEATURE:0cxx_reference_qualified_functions
CXX_FEATURE:0cxx_relaxed_constexpr
CXX_FEATURE:0cxx_return_type_deduction
CXX_FEATURE:0cxx_right_angle_brackets
CXX_FEATURE:0cxx_rvalue_references
CXX_FEATURE:0cxx_sizeof_member
CXX_FEATURE:0cxx_static_assert
CXX_FEATURE:0cxx_strong_enums
CXX_FEATURE:1cxx_template_template_parameters
CXX_FEATURE:0cxx_thread_local
CXX_FEATURE:0cxx_trailing_return_types
CXX_FEATURE:0cxx_unicode_literals
CXX_FEATURE:0cxx_uniform_initialization
CXX_FEATURE:0cxx_unrestricted_unions
CXX_FEATURE:0cxx_user_literals
CXX_FEATURE:0cxx_variable_templates
CXX_FEATURE:0cxx_variadic_macros
CXX_FEATURE:0cxx_variadic_templates
```

**Comment by jilinzhou** [comment]
@anup-pem : I think your configuration has some issues. The libc++ shipped with QNX SDP 7.0.0 for sure has alias_template feature. I have attached the feature_tests.cxx used by CMake here. You can try it manually as the following:
[feature_tests.cxx.txt](https://github.com/eProsima/Fast-RTPS/files/2651500/feature_tests.cxx.txt)

```
>>ntoaarch64-g++  -std=c++11 feature_tests.cxx -o feature_tests.bin
>>strings feature_tests.bin | grep FEATURECXX_FEATURE:0cxx_aggregate_default_initializers
CXX_FEATURE:1cxx_alias_templates
CXX_FEATURE:1cxx_alignas
CXX_FEATURE:1cxx_alignof
CXX_FEATURE:1cxx_attributes
CXX_FEATURE:0cxx_attribute_deprecated
CXX_FEATURE:1cxx_auto_type
CXX_FEATURE:0cxx_binary_literals
CXX_FEATURE:1cxx_constexpr
CXX_FEATURE:0cxx_contextual_conversions
CXX_FEATURE:1cxx_decltype
CXX_FEATURE:0cxx_decltype_auto
CXX_FEATURE:1cxx_decltype_incomplete_return_types
CXX_FEATURE:1cxx_default_function_template_args
CXX_FEATURE:1cxx_defaulted_functions
CXX_FEATURE:1cxx_defaulted_move_initializers
CXX_FEATURE:1cxx_delegating_constructors
CXX_FEATURE:1cxx_deleted_functions
CXX_FEATURE:0cxx_digit_separators
CXX_FEATURE:1cxx_enum_forward_declarations
CXX_FEATURE:1cxx_explicit_conversions
CXX_FEATURE:1cxx_extended_friend_declarations
CXX_FEATURE:1cxx_extern_templates
CXX_FEATURE:1cxx_final
CXX_FEATURE:1cxx_func_identifier
CXX_FEATURE:1cxx_generalized_initializers
CXX_FEATURE:0cxx_generic_lambdas
CXX_FEATURE:1cxx_inheriting_constructors
CXX_FEATURE:1cxx_inline_namespaces
CXX_FEATURE:1cxx_lambdas
CXX_FEATURE:0cxx_lambda_init_captures
CXX_FEATURE:1cxx_local_type_template_args
CXX_FEATURE:1cxx_long_long_type
CXX_FEATURE:1cxx_noexcept
CXX_FEATURE:1cxx_nonstatic_member_init
CXX_FEATURE:1cxx_nullptr
CXX_FEATURE:1cxx_override
CXX_FEATURE:1cxx_range_for
CXX_FEATURE:1cxx_raw_string_literals
CXX_FEATURE:1cxx_reference_qualified_functions
CXX_FEATURE:0cxx_relaxed_constexpr
CXX_FEATURE:0cxx_return_type_deduction
CXX_FEATURE:1cxx_right_angle_brackets
CXX_FEATURE:1cxx_rvalue_references
CXX_FEATURE:1cxx_sizeof_member
CXX_FEATURE:1cxx_static_assert
CXX_FEATURE:1cxx_strong_enums
CXX_FEATURE:1cxx_template_template_parameters
CXX_FEATURE:1cxx_thread_local
CXX_FEATURE:1cxx_trailing_return_types
CXX_FEATURE:1cxx_unicode_literals
CXX_FEATURE:1cxx_uniform_initialization
CXX_FEATURE:1cxx_unrestricted_unions
CXX_FEATURE:1cxx_user_literals
CXX_FEATURE:0cxx_variable_templates
CXX_FEATURE:1cxx_variadic_macros
CXX_FEATURE:1cxx_variadic_templates
```

**Comment by anup-pem** [comment]
@jilinzhou For simplicity, I created a test case to reproduce the problem I see in asio package(asio/include/asio/detail/memory.hpp) when compiling Fast-RTPS with v1.6.0. 

Just copy this code into a file called test_bind.cpp and the command used to compile is at the beginning of the source code. If you uncomment the #ifndef and #else part of the code, it compiles fine. Please let me know if there is a better solution so that I don't have to use my asio patch (https://github.com/eProsima/Fast-RTPS/issues/272#issuecomment-444694893) . Just curious.

Thanks
Anup

```
//
// This code was compiled using the following command
//
// qnx700/host/linux/x86_64/usr/bin/qcc -lang-c++ -D__DEBUG -Wp,-isystem,-Vgcc_ntox86_64 -g -D__USESRCVERSION -D_QNX_SOURCE -DQNX -fsized-deallocation -Wall -pedantic -Wextra -Wno-unknown-pragmas -g -fPIC -std=c++14 -o test_bind test_bind.cpp

#include <memory>
#include <string>

// Example allocator, doesn't do anything but implements std::allocator_traits
template<typename T>
struct null_allocator {
using value_type = T;

null_allocator() {}

template<typename U>
null_allocator(const null_allocator<U>&) {}

T* allocate(size_t size) {
(void) size;
return NULL;
}

void deallocate(T* ptr, size_t size) {
(void) ptr;
(void) size;
}
};

template<typename T, typename U>
constexpr bool operator== (const null_allocator<T>&, const null_allocator<U>&) noexcept {
return true;
}

template<typename T, typename U>
constexpr bool operator!= (const null_allocator<T>&, const null_allocator<U>&) noexcept {
return false;
}

//
// NOTE: Uncomment the ifndef-else belows (lines 43 and 46-49) for the code to compile without errors
//
//#ifndef _LIBCPP_HAS_NO_TEMPLATE_ALIASES
template<typename T>
using RebindAlloc = typename std::allocator_traits<null_allocator<void>>::template rebind_alloc<T>;
//#else
//template<typename T>
//using RebindAlloc = typename std::allocator_traits<null_allocator<void>>::template rebind_alloc<T>::other;
//#endif

using MyString = std::basic_string<char, std::char_traits<char>, RebindAlloc<char>>;

int main(int /*argc*/, char ** /*argv*/)
{
// check that null_allocator follows allocator_traits
null_allocator<void> alloc;
void * ptr = std::allocator_traits<null_allocator<void>>::allocate(alloc, 1);

MyString string;
}
```

**Comment by jilinzhou** [comment]
https://en.cppreference.com/w/cpp/memory/allocator

quote here:

...
rebind (deprecated in C++17)(removed in C++20) | template< class U > struct rebind { typedef allocator<U> other; }

Note
The member template class rebind provides a way to obtain an allocator for a different type. For example, 
std::list<T, A> allocates nodes of some internal type Node<T>, using the allocator A::rebind<Node<T>>::other | (until C++11)
-- | --
std::list<T, A> allocates nodes of some internal type Node<T>, using the allocator std::allocator_traits<A>::rebind_alloc<Node<T>>, which is implemented in terms of A::rebind<Node<T>>::other if A is an std::allocator | (since C++11)

**Comment by jilinzhou** [comment]
@anup-pem :  qnx sdp7 qcc toolchain only supports gcc compiler (version 5.4.0) which has no built-in macro `__had_feature()` defined (it is a Clang thing). Therefore in $QNX_TARGET//usr/include/c++/v1/__config, it is set to 0 as the following:

```
#ifndef __has_feature
#define __has_feature(__x) 0
#endif
...
#define _LIBCPP_HAS_NO_TEMPLATE_ALIASES
...
```
The gcc compiler has `__has_cpp_attribute` defined for this purpose. Hope this info can help you a bit.

**Comment by anup-pem** [comment]
@jilinzhou 

> You can build it against GNU c++ library as the following:
qcc -Vgcc_ntox86_64_gpp -g -fsized-deallocation -Wall -pedantic -Wextra -Wno-unknown-pragmas -vv -Wfatal-errors -o test_bind test_bind.cpp

Yes, it works for libstdc++ with Vgcc_ntox86_64_gpp or -stdlib=libstdc++. The issue is with the LLVM C++.

> Have you been able to built it against LLVM c++ library on linux?
Have not tested on Linux. But we do OS X build with LLVM C++ lib and it works fine

> The gcc compiler has __has_cpp_attribute defined for this purpose. Hope this info can help you a bit.

Not sure how it will help in fixing the ` std::allocator_traits::rebind_alloc` alias error. Could you show me how can I use it either with the test_bind.cpp example or the newer version of Fast-RTPS so that I don't get the compile error with lib LLVM C++ (libc++) library? Might be I am missing something.

**Comment by MiguelCompany** [comment]
FYI, I created chriskohlhoff/asio#353 adding the SO_REUSEPORT option for QNX

**Comment by jilinzhou** [comment]
@MiguelCompany : Thanks!

**Comment by Johnnyxy** [comment]
For problems with QNX SDP 7.0 and LLVM backend (```cxx``` runtime) see here: https://github.com/boostorg/boost/issues/208#issuecomment-498182528
