### ISSUE TITLE
cpu usage gradually increases to 100%

### ISSUE THREAD

**Issue by johnfinley** [eProsima/Fast-RTPS#29]
If our program has an endpoint publishing at a few hundred messages/sec with qos=reliable, the cpu utilization for the process gradually increases until it is consuming all cpu. I modified the example "HelloWorld" program to send messages at a higher rate, and it does it too (although very slowly) when run on an ubuntu-14.04 VM. I have a different test program that can send at higher rates, and the CPU usage runs away pretty quickly. In our "real" program, the message rate is ~100/sec, and it ramps up to 100% within a few minutes (perhaps because of our slower processor). Same effect has been observed on our target hardware, os-x, and linux using our test programs, and has just been confirmed using HelloWorld on an ubuntu-14.04 vm. The HelloWorld test was done in a fresh clone and build on 3/16.

I can add our test programs if helpful, but I figured using HelloWorld would be more useful to you.

Two files attached:

[soak-diff.txt](https://github.com/eProsima/Fast-RTPS/files/180427/soak-diff.txt) is diffs from HelloWorld.

[soak-top.txt](https://github.com/eProsima/Fast-RTPS/files/180428/soak-top.txt) is output from top on the vm as the pub and sub run on the same vm. I think I used "top -b | grep <pid>" where <pid> is that of the publisher, so the samples are about 3 seconds apart.

**Comment by JaimeMartin** [comment]
Hi John,

We reproduced the issue and identified where is the problem. We will prepare a patch for you.

**Comment by JaimeMartin** [comment]
Hi John,

We uploaded a new temp branch(https://github.com/eProsima/Fast-RTPS/tree/hotfix/29) with a fix for your issue. We are testing now everything. Let me know is this solves your problem.

**Comment by johnfinley** [comment]
Thanks! We'll be trying it out over the next few days.
