### ISSUE TITLE
[Question] Details of hostname 

### ISSUE THREAD

**Issue by sriramster** [eProsima/Fast-RTPS#293]
Hi,

Is it possible to get the details of the hostname on which the nodes are running?

**Comment by richiware** [comment]
If I understand well you're asking about retrieve not only the IP address of the remote node but also the hostname. In 
this case this capability is not currently implemented. Participants only sends their IP addresses.

↪ 2018-11-02 vie 14:47, Sriram Raghunathan <notifications@github.com>:

**Comment by Jimmy316** [comment]
@richiware Can you explain how to get the remote IP - I would like to add it to my logs

**Comment by richiware** [comment]
This information is shared between participants in the discovery phase, but I've realized it is not offered to the user. Commit 13fd15ce02b722a86f0db4d9a47d7ec769aa8e3c will solve it and it is included in next release 1.7.0.

**Comment by richiware** [comment]
I hope this help you. I close the issue. If you have some problem feel free to reopen it.

**Comment by cvilas** [comment]
If I want to get the IP address of the remote participant just discovered, which locator list should I be looking in? (meta traffic unicast, meta traffic multicast, default unicast, default multicast?)

**Comment by codewithpassion** [comment]
@richiware Similar question, I can see the code has been added, but how can I access the properties?
I'd like to get the IP address for the remote publisher.

**Comment by richiware** [comment]
You should be able to get that information using default unicast locator list.
