### ISSUE TITLE
Transport Layer with Sharedmemory

### ISSUE THREAD

**Issue by anandtp** [eProsima/Fast-RTPS#312]
Are you planning an early release of Share memory transport (Beta version).

Regards,
Anand Pavaskar

**Comment by JaimeMartin** [comment]
Hi Anand,

While this feature is on our roadmap, we have no specific dates.

**Comment by fujitatomoya** [comment]
@JaimeMartin 

Hi, it's been a while, is there any approximate date to support shared memory?

my though is ROS2 intra-process is supported using unique_ptr and shared_ptr, but so far nothing is considered actively. expecting shared memory is really good method for inter-process.

thanks,
Tomoya

**Comment by vincent-hui** [comment]
eProsima and Sony will develop a Shared Memory Transport for ROS2
https://www.eprosima.com/index.php/company-all/news/121-eprosima-and-sony-will-develop-a-shared-memory-transport-for-ros2

**Comment by fujitatomoya** [comment]
@vincent-hui 

thanks for announcement !!!

**Comment by wenbin1989** [comment]
Seems that it has been released already?

**Comment by csherstan** [comment]
Same question. Has this already been implemented and released? If so, what version was it released in?

**Comment by csherstan** [comment]
Looks like the feature was just recently added, so probably not released yet: [https://github.com/eProsima/Fast-RTPS/pull/992](url)

**Comment by fujitatomoya** [comment]
@MiguelCompany @vincent-hui @adolfomarver 

would you like to mention the current status here, some people got interests.

@csherstan @wenbin1989 

as you see and know, eProsima and Sony(we) been working on it. as for release information, we'd like to hear from eProsima.

**Comment by MiguelCompany** [comment]
@anandtp @vincent-hui @wenbin1989 @csherstan Fast RTPS 1.10.0 will come out this week, and will include a shared memory transport enabled by default.
