### ISSUE TITLE
Can user config "MutationTries"

### ISSUE THREAD

**Issue by hwmagical** [eProsima/Fast-RTPS#324]
https://github.com/eProsima/Fast-RTPS/blob/ea57f15aaf689144cb8e75aa8d23e7b6ed832b3a/src/cpp/rtps/participant/RTPSParticipantImpl.h#L463

If there is more than 100 nodes，node created after can not receive message from node created before。
Is there any configuration to config “MutationTries”？

**Comment by richiware** [comment]
Currently not. Do you have a machine with more than 100 nodes?

**Comment by hwmagical** [comment]
@richiware  Yes，we will create more than 100 nodes

**Comment by richiware** [comment]
Right now we have the code frozen because we will release a new version 1.7.0. I've create a task for the next 1.8.0 
milestone to make the mutationTries configurable.

↪ 2018-11-16 vie 13:07, hwmagical <notifications@github.com>:
