### ISSUE TITLE
receiving failed after some packges

### ISSUE THREAD

**Issue by deiska** [eProsima/Fast-RTPS#335]
Two computers connected in a network via out LTE wireless device.
Computer A (Ubuntu) PING to computer B (also Ubuntu) is always reliable.

Our testing is based on "HelloWorldExample", but there are some differences:
    1. Added _Locator_  brefore _Domain::createSubscriber_ and _Domain::createPublisher_ with the code below:
    Locator_t new_locator;
    new_locator.set_IP4_address(239, 255, 0, 1);
    new_locator.port = 7900;
    Wparam(Rparam).multicastLocatorList.push_back(new_locator);

    2.the length of messages which were sent is increased to 200 bytes.

    3.modified the args[2] as number of the sending messages;

    4.reduced the durations in _HelloWorldPublisher::run_ to 1.

Computer A sent 999999 messages, but Computer B just received 205757, and no more.

Would you please help me to figure out if there were anything wrong about my configuration?
Thx!

**Comment by LuisGP** [comment]
Are you configuring both publisher's and subscriber's QoS as RELIABLE?

    Wparam.qos.m_reliability.kind = RELIABLE_RELIABILITY_QOS;

    Rparam.qos.m_reliability.kind = RELIABLE_RELIABILITY_QOS;

**Comment by deiska** [comment]
> Are you configuring both publisher's and subscriber's QoS as RELIABLE?
> 
> ```
> Wparam.qos.m_reliability.kind = RELIABLE_RELIABILITY_QOS;
> 
> Rparam.qos.m_reliability.kind = RELIABLE_RELIABILITY_QOS;
> ```
> Another typical misconfiguration that can cause similar issues is that the publisher starts sending messages before it matched against the subscriber.

Thx for your reply!

Actually I tyied both `RELIABLE_RELIABILITY_QOS` and `BEST_EFFORT_RELIABILITY_QOS`, in the first condition, it would received less then the other .

**Comment by richiware** [comment]
Using reliability you have to consider to configure the history. Depending of its depth, fastrtps will be able to repair 
the lost samples. How to set history in https://eprosima-fast-rtps.readthedocs.io/en/latest/pubsub.html#history.


↪ 2018-11-27 mar 08:11, deiska <notifications@github.com>:

**Comment by LuisGP** [comment]
As this was answered and no comments were received, we close the issue. Feel free to reopen if there is more clarification needed.
