### ISSUE TITLE
PublisherHistory: stateless writer never removes samples

### ISSUE THREAD

**Issue by liamstask** [eProsima/Fast-RTPS#34]
The fix for #33 is not correct in the case of a `StatelessWriter`. If the publisher is configured with KEEP_LAST_HISTORY_QOS and BEST_EFFORT reliability, `StatelessWriter::clean_history()` always returns false now, which means that when it's called in `PublisherHistory::add_pub_change()`, it triggers the path that logs `Attempting to add Data to Full WriterCache:`.

Might be enough to return `true` from `StatelessWriter::clean_history()` instead.

**Comment by SantiagoMunoz** [comment]
It seems this issue has been solved on version 1.2.0. Cheers!
