### ISSUE TITLE
Non-blocking calls

### ISSUE THREAD

**Issue by richiware** [eProsima/Fast-RTPS#345]
# Non-blocking calls

## Solution strategy

The strategy is to avoid any call that blocks for an indeterminate time the application's threads.
In a previous analysis there were detected several *blocking* calls.
These *blocking* calls are caused by next functions:

* `std::recursive_mutex::lock()`: this function protects a critical area from accessing several threads.
While a thread is in this critical are, the rest of threads are blocked for an indeterminate time.
* `boost::asio::basic_datagram_socket::sendto()`: this function sends a datagram to the network.
For this purpose it tries to write the datagram in the socket kernel buffer.
The thread could be blocked for an indeterminate time if there is no space in the buffer.

Converting these functions in a *non-blocking* way should be easy.
This is the approach this design follows:

* `std::recursive_mutex` instances will be changed by `std::recursive_timed_mutex` instances.
This new class offers the function `std::recursive_timed_mutex::try_lock_until()` which blocks the thread until
specified timeout.
This function will be used in the logic executed by the application's threads.
Also, this class implements the function `std::recursive_timed_mutex::lock()` which can be maintained in the
logic executed by the non-application's threads.

* boost::asio provides access to the native socket via `boost::asio::basic_socket::native_handle()`.
Using the function `setsockopt()` and the native socket we can set the kernel socket option `SO_SNDTIMEO`.
This option sets a timeout when a datagram is sent.
If the thread is blocked because there are no space in the buffer, it is blocked until the timeout.

## Building block view

This section addresses the necessary changes in the product at component and class level to fit the requirements and
technical requirements.
There are three components which require changes: Write, Reader and UDP transport.

### Writer component

Writer component has to be protected because several threads can access to it: application's thread, event's thread,
so on.
In current implementation, several classes which form this component contain its own `std::recursive_mutex`.
These classes are: `RTPSWriter`, `ReaderProxy` and `TimedEvent`.

This design sets to joining all lock mechanisms in only one for the whole Writer component.
The unique lock mechanism will be a `std::recursive_time_mutex` instance.
The lock will be done before adding the sample to the `WriterHistory`.
If the lock fails because the timeout expires, the user will receive an error writing the sample.

![Write sample](http://www.plantuml.com/plantuml/png/XPD1Qnin48Nl-XL3ScaF2NPoS2Yf2J4jAVHWwa8F8OJnQkmLMMcMqMnj4_BVAodRu7eTAeCjvdipR_2-lOcAefrlFZZx-PSuTM4D215zsz174oji23nkuM8q6ctpbr6dgVRZvtm1tt570cUG6yjbnhxbG46ZgR1Lnm6-XOImAdTU0JNaCuTDJG4s1ux6n2SNMXJqy6m0OesMDrcnmYPIgg08RsRSiC3fP9G_kLWfoosB9Jb4rT-DZcEXIZ6i6pgE0olTOlMq5kw2xUcgd9x-P-nN3dhOzWONIaAik_Q8xCMyoU1atYqR5skI4xY-dYKjka0odG96k89JMuvfqwAuJlByE8RQv_r_0yON2TFlT4sedm3t1jAPapYshheZ55qIQgcUdPMVBxa5kaWHb25IiD3s-iBhlQQ7VnqlasFLO8m3nnocrwNthVfKET--PWPpXePZn--F9RGaS-7jRd_kGba8N5Yn-38JSCcT0XOgv5a9fFGEtIRlkVNhthcOnW_z-e23nu1hih3SWTPKU7u9UgiNSmNdztsE7iwdsUyJeBMFLPsoG6PyUS0l4XSgR_6ZEayob8oJf6ijQcgV7B3Bn0AhM-tC3GNR-SRy0G00)

This design decision addresses next requirements: TR-RT-NBC-1, TR-RT-NBC-2, TR-RT-NBC-3.

**Asynchronous writer**

A user can configure a writer as asynchronous writer.
In this case the application's thread only adds the sample to the `WriterHistory` and notifies the asynchronous thread
to wake up.

Currently the notification mechanism uses a `std::mutex` and a `std::condition_variable`.
They will be changed by a `std::timed_mutex` and a `std::condition_variable_any`.

When the application's thread will notify the asynchronous thread, it is blocked and two things can occur:

- The thread has access to modify the atomic variable and then use `std::condition_variable_any::notify_one()`.
- The timeout expired and the asynchronous thread is not notified.
Anyway the atomic variable is modified.
This case should be almost impossible because the mutex will be locked only to change a variable.
But the case has to be contemplated.

After making its work, the asynchronous thread will call `std::condition_variable_any::wait_until()`.
The reason to call this function instead of `std::condition_variable_any::wait()` is to avoid the unlikely case where
there wasn't awake because the application's thread could not take the `std::timed_mutex`.

![Async write sample](http://www.plantuml.com/plantuml/png/VP9HQzim4CVVzIcEzcLxICbMQ4leGjV0s60FPIdieOHnbIwsg7Go9ndNb7ttIOuJcivK1bk-t__-Eabt4nDAQhtxOCsNtsAJvGemzgnh2HpQw7f0YEWRHnzLrEW8F3x3v_by_bnUAjcKOx_kxzRm4tiIc47n6IQhu9l0n2agZKsoWU47PuHwc8Sja2DVE7GrCNJl5w1KVBBSeA275mKGQpIXAmbRT95o14L2jmek29nUpijJWZe5kGrYIDuYlIzm6WlfX5mvciOS4jsYVgeaj6n6kXt6dhvl-ormUfjsWEj4GY7rpOJihph8uEGE9Lbj6-Hq0jVNgwn6ooJB9M242pWrmpXAQH-TZJN9HCBL8Q79UyCgoyk5_gzzUNs0yEayO-qmnen61tZ84XYQOsSn_CvcvRFl4kkRNGzWwObCDiUsbzEs1uFlDgOW_MldTGxGs3FWaR4Y0uyzf9e6tkrhsUI3l8ApX_5gDcVBiju2q9W_kaQkIELj7V6BZB-MzjojVbyBeLaiE2IxxLNEFdOxp_AHtH2RrZlr3m00)

This design decision addresses next requirements: TR-RT-NBC-5.

**Setting the timeout**

To set the maximum time the application's thread could be blocked, we will use the already existing Writer's QoS
`max_blocking_time`.

### Reader component

When a user takes a sample using `Subscriber::takeNextData()`, the `RTPSReader` and `ReaderHistory` are protected with
the same `std::recursive_mutex`.
This protection will be changed by a `std::recusive_timed_mutex`.
Also `Subscriber::takeNextData()` will have a new parameter `timeout`.

This design decision addresses next requirements: TR-RT-NBC-6.

## Architecture decisions

See #384

**Comment by deeplearningrobotics** [comment]
@richiware: Two questions:

1. How do handle priority inheritance? Let's say two threads with different priority try to access data which is protected by the same lock/
2. As there is a high chance that the standard C++ multithreading part will not be usable for safety-critical applications for various reasons can you provide the option to replace the threading functionality at compile time such as for example:

```
struct std_multithreading_trait {
  using mutex = std::mutex;
  using thread = std::thread
  ...
};

DomainParticipant<std_multithreading> dp;
...

// For safety-critical applications:

struct safe_multithreading_trait {
  using mutex = propriatery_mutex;
  using thread = propriatery_thread;
  ...
};

DomainParticipant<safe_multithreading_trait> dp;
```
