### ISSUE TITLE
participant lease can't be renewed

### ISSUE THREAD

**Issue by johnfinley** [eProsima/Fast-RTPS#35]
I don't think a lease duration that is not infinity works. What I observe is if I set a participant's lease duration to (for example) 10 seconds, and set the lease duration announce period to 2 seconds, the lease is never renewed and the participant is removed on the other end when the 10 second timer expires. The first announcement is received, but none of the announcements after that reset the timer.

What I think is happening is something like this:
 * I set "partitcipant1" lease duration to 10 seconds, announce period to 2 seconds
 * "participant2" recognizes participant1 and starts the 10 second timer
 * participant1 sends another announcement after 2 seconds
 * participant2 receives the announcement as far as StatelessReader::change_received
 * but in ReaderHistory::add_change, it fails to add the change to the history because (I think) the sequence number has not changed, and the change is discarded at that point.

I think it is correct that the sequence number has not changed, since the spec says the announcement is sent by just calling unsent_changes_reset. I do not know how the receiving end should handle the change, since it thinks it already has that change (since the sequence number is correct), but somehow it should reset the lease duration timer.

**Comment by PabloMansanet** [comment]
Thanks for the report! 

I can't seem to reproduce this problem on the latest development version. This will probably not be an issue in the upcoming release, but please let me know if the behaviour resurfaces.

**Comment by PabloMansanet** [comment]
We can't trace the point where this bug went under, but it seems solved now. Thanks!
