### ISSUE TITLE
poor performance w/unreliable link

### ISSUE THREAD

**Issue by liamstask** [eProsima/Fast-RTPS#36]
we are still working to characterize this further, but we have observed poor throughput and cpu usage when there is even a small amount of packet loss.

our setup is as follows:
* a simple pair of apps that publishes/receives a configurable number of msgs/sec (default 500/sec) in either reliable or best effort config
* publisher is running in a vm (Linux), the other on host machine (OS X), with a host-only network connecting them

2 main problems so far:
* when configured as reliable, a single dropped packet leads to cpu saturation on receiver until packet is resent
* we simulate 2% packet loss at 1000 msg/sec and all message delivery appears to stop - still investigating what is actually happening in this situation

To simulate 2% packet loss on the Linux machine, run `sudo tc qdisc change dev eth2 root netem loss 2%` 

We are continuing to look into these further, but wanted to provide some preliminary info about this issue.

/cc @johnfinley

**Comment by richiprosima** [comment]
Can you provide me your configuration of your Subscriber and Publisher? Thanks.

**Comment by liamstask** [comment]
Sure thing. In this 

```
config.history = 1000;
```

```c++
PublisherAttributes pub_attr;
pub_attr.topic.topicKind = NO_KEY;
pub_attr.topic.topicName = TopicData::topic_name;
pub_attr.topic.topicDataType = TopicData::topic_type;
pub_attr.topic.historyQos.kind = KEEP_LAST_HISTORY_QOS;
pub_attr.topic.historyQos.depth = config.history;
pub_attr.topic.resourceLimitsQos.max_samples = 2 * config.history;
pub_attr.topic.resourceLimitsQos.allocated_samples = 2 * config.history;
pub_attr.times.heartbeatPeriod.fraction = 4294967 * 200; // ~200 millis
pub_attr.qos.m_reliability.kind = config.reliable ? RELIABLE_RELIABILITY_QOS : BEST_EFFORT_RELIABILITY_QOS;
```

and

```c++
SubscriberAttributes sub_attr;
sub_attr.topic.topicKind = NO_KEY;
sub_attr.topic.topicName = TopicData::topic_name;
sub_attr.topic.topicDataType = TopicData::topic_type;
sub_attr.topic.historyQos.kind = KEEP_LAST_HISTORY_QOS;
sub_attr.topic.historyQos.depth = config.history;
sub_attr.topic.resourceLimitsQos.max_samples = 2 * config.history;
sub_attr.topic.resourceLimitsQos.allocated_samples = 2 * config.history;
sub_attr.qos.m_reliability.kind = config.reliable ? RELIABLE_RELIABILITY_QOS : BEST_EFFORT_RELIABILITY_QOS;
```

**Comment by richiprosima** [comment]
'''heartbeatPeriod''' has as default value of 3 seconds.  Maybe it is bad documented. In your configuration only fractions are set. I advice to set it to 100milliseconds.
'''pub_attr.times.heartbeatPeriod.seconds = 0;
pub_attr.times.heartbeatPeriod.fraction = 4294967 * 100;'''

Also I advice to set '''heartbeatResponsePeriod''' to 50 milliseconds in subscriber side. 

I test it and it improves the performance.

**Comment by liamstask** [comment]
@richiprosima thanks, that does improve the throughput.

however, do you still see the cpu usage issue? we have not identified it precisely, but it seems like it may be saturating cpu on the subscriber while waiting for a dropped packet, or something along those lines.

**Comment by richiware** [comment]
CPU usage was improved in release 1.1.0 and in next release to come out. I close this issue.
