### ISSUE TITLE
fastrtpsgen IDL identifier case sensitivity [4288]

### ISSUE THREAD

**Issue by wtsnyder** [eProsima/Fast-RTPS#360]
fastrtpsgen  does not properly handle case sensitivity when processing IDL files.
The following IDL should result in collision errors between identifiers Bar, bar, and BAR.

```
module foo {
  struct Bar {
  };

  struct bar {

  };

  module BAR {

  };
};
```

From the [IDL Spec Version 4.1](https://www.omg.org/spec/IDL/4.1/PDF)

> 7.2.3 Identifiers
An identifier is an arbitrarily long sequence of ASCII alphabetic, digit and underscore (_) characters. The first character must be an ASCII alphabetic character. All characters are significant.
IDL identifiers are case insensitive. However, all references to a definition must use the same case as the defining occurrence. This allows natural mappings to case-sensitive languages.
7.2.3.1 Collision Rules
When comparing two identifiers to see if they collide:
• Upper- and lower-case letters are treated as the same letter. Table 7-2 defines the equivalence mapping of upper- and lower-case letters.
• All characters are significant.
Identifiers that differ only in case collide, and will yield a compilation error under certain circumstances. An identifier for a given definition must be spelled identically (e.g., with respect to case) throughout a specification.
There is only one namespace for IDL identifiers in each scope. Using the same identifier for a constant and an interface, for example, produces a compilation error.

**Comment by LuisGP** [comment]
Hi @wtsnyder 

Thank you very much for reporting this issue. I just added checkings to IDL-Parser to implement these rules (based on 4.2).
I added the escape character feature to identifiers too, so from now "_myid" is treated as "myid". This allows using keywords as identifiers for example, "_module".

Please, if you can, check that FastRTPSGen handles it correctly.

The PR is #464 

Best regards.

**Comment by wtsnyder** [comment]
Hi @LuisGP 

Thanks for looking into this.  Your fixes seem to work in some cases but I was still able to pass some invalid IDL through.

This test case fails correctly
```
module foo {
    struct Bar {
        long a;
    };
// fails correctly: error: Illegal identifier
    module bar {
        struct Baz {
            long b;  
        };
    };
};
```
However, reversing the order of the module and the struct does not cause any errors, which is not correct.
```
module foo {
    module bar {
        struct Baz {
            long b;  
        };
    };
    // this should collide with module bar but doesn't
    struct Bar {
        long a;
    };
};
```

I have been using the Linux libidl to check if an IDL file is well formed or not.
There is no guarantee that they do everything correctly to the spec. but it at least lets me confirm my opinions on what is or isn't valid IDL.  Below is a CMakeLists.txt and a c source file which allows you to check an IDL file against libidl.

```
include(FindPkgConfig)
pkg_search_module(IDL2 libIDL-2.0)
include_directories(${IDL2_INCLUDE_DIRS})

add_executable(libidl_test libidl_test.c)
target_link_libraries(libidl_test  ${IDL2_LIBRARIES})
```

```
#include <stdio.h>
#include <libIDL/IDL.h>

int main(int argc, char **argv)
{
    IDL_tree tree;
    // parse the file
    if (IDL_parse_filename(argv[1], NULL, NULL, &tree, NULL, 0, IDL_WARNINGMAX) != IDL_SUCCESS)
    {
        exit(1);
    }
    // Cleanup
    IDL_tree_free(tree);
    return 0;
}
```
This may not be foolproof though. For example, based on the quotation of the spec in my original post, fastrtpsgen is correct in failing on this file while libidl only provides a warning.
```
module foo {
    struct Bar {
        long c;
    };
    struct Baz {
        // libidl Warning:
        // (Identifiers should be case-consistent after initial declaration)
        // fails in fastrtpsgen
        bar a;
    };  
};
```

I didn't have a chance to test the "_" escape character feature but we haven't had a need for it in our application yet.

**Comment by LuisGP** [comment]
Hi @wtsnyder 

Thanks for your time.

We really appreciate you tested it as these use cases aren't our typical usages. I updated the PR with a fix for the module error. It was related to when we add the module definitions to the context, at the end of the module instead of the beginning. I tested with some simple IDL files and seems to work now in these cases.

Please, check it from your side if you have time. And if you find another issue we will be pleasured to take a look at it. 

Thank you for the tip about *libidl*. Comparison against other implementations is always a powerful tool to improve our product.

**Comment by wtsnyder** [comment]
@LuisGP 

This seems to work on my end as well.  Thanks for closing out this issue. I'll post another issue if I run into any other small IDL corner cases between your parser and other implementations.

Will
