### ISSUE TITLE
Encryption/Decryption of CryptoToken [4289]

### ISSUE THREAD

**Issue by pokitoz** [eProsima/Fast-RTPS#363]
Hello,

I have a question about the following lines:
https://github.com/eProsima/Fast-RTPS/blob/b48ce9d2fba6fc94e756da01c58b72f2ad848238/src/cpp/security/cryptography/AESGCMGMAC_KeyExchange.cpp#L64

and 

https://github.com/eProsima/Fast-RTPS/blob/b48ce9d2fba6fc94e756da01c58b72f2ad848238/src/cpp/security/cryptography/AESGCMGMAC_KeyExchange.cpp#L110

In previous version of Fast-RTPS, the dds.cryp.keymat was encrypted/decrypted (the code is still there but commented). After digging a bit more in the code, I could not find in the SecureManager (https://github.com/eProsima/Fast-RTPS/blob/v1.7.0/src/cpp/rtps/security/SecurityManager.cpp) how the content of the keymat was encrypted/decrypted. I was expecting the StatefulWriter participant_volatile_message_secure_writer_ to be responsible of this but it seems the protection support is disabled:
`participant_->set_endpoint_rtps_protection_supports(wout, false);`

As the CryptoToken contains the symmetric keys (KeyMaterial), I am expecting them to be encrypted at one point. So I guess I am missing something in the process.

Why did the encryption/decryption has been commented and how are the messages secured in Fast-RTPS?

Thanks :)

**Comment by MiguelCompany** [comment]
Hi @pokitoz 

As you stated the protection is done by `participant_volatile_message_secure_writer_`, as it is created with `watt.endpoint.security_attributes().is_submessage_protected = true;`, i.e. setting protection on the submessage. The line you pointed out `participant_->set_endpoint_rtps_protection_supports(wout, false);` just inhibit the protection of the whole RTPS message for the specified writer.

All these are specified on version 1.1 of the [DDS security specification](https://www.omg.org/spec/DDS-SECURITY/About-DDS-SECURITY/), and made Fast-RTPS security module interoperable with other implementations of the protocol.

I hope this answers your question.

**Comment by MiguelCompany** [comment]
As this was answered and no comments were received, we close the issue. Feel free to reopen if there is more clarification needed.
