### ISSUE TITLE
Feature Request: Scoped Enumerations [4290]

### ISSUE THREAD

**Issue by raykraft** [eProsima/Fast-RTPS#365]
Scoped enumerations are often preferred over unscoped. This is a feature request for Fast-RTPS to support C++11 enum class scoped enumerations.

**Comment by jml1795** [comment]
This would be very helpful for my project as well

**Comment by richiware** [comment]
[v1.7.1](https://github.com/eProsima/Fast-RTPS/releases/tag/v1.7.1) incorporates eProsima/Fast-CDR#42. Can you verify it is working for you? Thanks.

**Comment by richiware** [comment]
For now I will close the issue. If you continue having problems, feel free to reopen the issue.
