### ISSUE TITLE
Which QoS does the FAST-RTPS support？[4297]

### ISSUE THREAD

**Issue by zhenfei0601** [eProsima/Fast-RTPS#368]
I want to know how many QoS and which QoS does the FAST-RTPS support?

**Comment by pokitoz** [comment]
I am not part of FastRTPS, but until you get an answer, I would suggest you have a look at 
https://eprosima-fast-rtps.readthedocs.io/en/latest/xmlprofiles.html#qos

where you can see the different options to customize the QoS for FastRTPS

**Comment by LuisGP** [comment]
@pokitoz answer is correct. We are working to add more QoS in the next release 1.8.0. You'll find them documented in that link once the release is published.
I'm closing the issue, feel free to reopen it again if you need more information.
