### ISSUE TITLE
Can qos ReliableReliability ensure the message order in subscriber? [4327]

### ISSUE THREAD

**Issue by zhuangli1987** [eProsima/Fast-RTPS#373]
Say, if we have 2 publisher and 1 subscriber in same topic, and qos is ReliableReliability.
Publisher 1, send msg_1_1, msg_1_2, msg_1_3,
Publisher 2, send msg_2_1, msg_2_2, msg_2_3

The question is, can we ensure the subscriber receive msg_1 and msg_2 by order separately?

**Comment by richiware** [comment]
Currently the policy fastrtps works with is: you will receive the sample of a publisher in order, but between publishers you might not receive the samples in order. Using your example you can receive:

```
msg_1_1 , msg_1_2, msg_2_1, msg_2_2, msg_1_3, msg_2_3
```

Have I answer your question?

**Comment by richiware** [comment]
I will close the issue. I'm glad it was helpful.
