### ISSUE TITLE
 Issue in Benchmark  example [4642]

### ISSUE THREAD

**Issue by Yale323** [eProsima/Fast-RTPS#395]
I'm trying to run Benchmark example with following parameters：

./Benchmark subscriber tcp
 ./Benchmark publisher tcp

But I got errors in publisher terminal：
2019-01-31 14:27:49.871 [RTCP Error] Cannot find an available logical port. -> Function PrepareAndSendCheckLogicalPortsRequest
2019-01-31 14:27:50.392 [RTCP Error] Cannot find an available logical port. -> Function PrepareAndSendCheckLogicalPortsRequest
2019-01-31 14:27:50.835 [RTCP Error] Cannot find an available logical port. -> Function PrepareAndSendCheckLogicalPortsRequest
2019-01-31 14:27:51.892 [RTCP Error] Cannot find an available logical port. -> Function PrepareAndSendCheckLogicalPortsRequest
......

**Comment by LuisGP** [comment]
Hi @Yale323,

seems that you found a misconfiguration bug in this example.
I'll fix it cleaning it a bit and will prepare a PR that you will be able to test on your side too.

Sorry for the inconveniences, and thank you very much for opening the issue!

**Comment by LuisGP** [comment]
Here you have the fix: #408

**Comment by Yale323** [comment]
> Here you have the fix: #408

Thanks，I checkout branch release/1.7.1,   and run "cmake -DTHIRDPARTY=ON -DBUILD_JAVA=ON -DCOMPILE_EXAMPLES=ON -DPERFORMANCE_TESTS=ON -DSECURITY=ON .."
then make, I got following error:
[  0%] Generating Java application

> Task :idl:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: /home/yale/Fast-RTPS/Fast-RTPS/thirdparty/idl/src/main/java/com/eprosima/idl/generator/manager/TemplateUtil.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
/home/yale/Fast-RTPS/Fast-RTPS/fastrtpsgen/src/com/eprosima/fastrtps/fastrtpsgen.java:32: error: cannot find symbol
import com.eprosima.idl.parser.typecode.Kind;
                                       ^
  symbol:   class Kind
  location: package com.eprosima.idl.parser.typecode
/home/yale/Fast-RTPS/Fast-RTPS/fastrtpsgen/src/com/eprosima/fastrtps/idl/grammar/Context.java:21: error: cannot find symbol
import com.eprosima.idl.parser.typecode.Kind;
                                       ^
  symbol:   class Kind
  location: package com.eprosima.idl.parser.typecode
/home/yale/Fast-RTPS/Fast-RTPS/thirdparty/fastcdr/src/java/com/eprosima/fastcdr/idl/generator/TypesGenerator.java:23: error: cannot find symbol
import com.eprosima.idl.parser.typecode.Kind;
                                       ^
  symbol:   class Kind
  location: package com.eprosima.idl.parser.typecode
3 errors


FAILURE: Build failed with an exception.

**Comment by LuisGP** [comment]
Yes, we detected the issue a moments ago.

The branch release/1.7.1 is going to update IDL-Parser, but the master branch doesn't have some develop's commits yet.
I created the PR to solve this issue, but meanwhile, you can try it switching manually your IDL submodule to develop (you may stage the modified submodule to avoid CMake revert the changes).

Best regards.

**Comment by LuisGP** [comment]
Hi @Yale323,

the fix is merged in the release/1.7.1 branch. Can you test it?

**Comment by Yale323** [comment]
Hi @LuisGP 
It works well，thanks for the bug fix.
