### ISSUE TITLE
[MUST] Roadmap is missing [4663]

### ISSUE THREAD

**Issue by jason-fox** [eProsima/Fast-RTPS#397]
A roadmap for the project for the short (3 months) , medium (one year) and long term  should be added to the repository and publicly available.

**Comment by richiware** [comment]
#413 adds roadmap in the README file.

**Comment by jason-fox** [comment]
@richiware - your fix doesn't fulfill the relevant [contributor requirements](https://fiware-requirements.readthedocs.io/en/latest/GE_Requirements/index.html#roadmap) - could you separate the roadmap to new file and use the template found [here](https://github.com/Fiware/contribution-requirements/blob/master/docs/GE_roadmap_template.md) please.

You can see https://github.com/telefonicaid/fiware-orion/blob/master/doc/roadmap.md for an example

**Comment by richiware** [comment]
Sorry, I was not aware about the template. #421 addresses it.

**Comment by jason-fox** [comment]
@richiware - 👍 - the roadmap is now compliant.
