### ISSUE TITLE
std::vector mutated during iteration

### ISSUE THREAD

**Issue by liamstask** [eProsima/Fast-RTPS#40]
There are several places where items are removed from a `std::vector` during iteration - this invalidates the iterator, so subsequent operations may be invalid.

One example is `History::remove_all_changes()` - it creates an iterator and loops through the vector of changes, but calls `remove_change()` which removes an entry. In my case, it would then segfault when trying to continue removing changes based on the invalid iterator.

My local fix for it is something like:
```c++
while (!m_changes.empty()) {
  remove_change(m_changes.front());
}
```

But there may be a better option that is easier to reuse in other scenarios.

It's probably worth doing an audit of the project for this pattern, and resolving other instances as well.

**Comment by SantiagoMunoz** [comment]
@liamstask Thanks for the heads up. We've fixed it and checked we've not missed this somewhere else in version 1.2.0 which is already being uploaded.
