### ISSUE TITLE
Info Logging Issue [4591]

### ISSUE THREAD

**Issue by nhreimer** [eProsima/Fast-RTPS#402]
SetVerbosity( Log::Kind::Info ) doesn't log when using logInfo( cat, msg ):

```
  Log::SetVerbosity( Log::Kind::Info );
  logError( WHATEVER, "this is a test" );
  logInfo( WHATEVER1, "this is a test" );
```
only the error appears:
`19.443 [WHATEVER Error] this is a test -> Function main`

If I redefine the macro in Log.h:

`#define logInfo_(cat, msg) { if (Log::GetVerbosity() >= Log::Kind::Info) { std::stringstream ss; ss << msg; Log::QueueLog(ss.str(), Log::Context{__FILE__, __LINE__, __func__, #cat}, Log::Kind::Info); } }`

And then rerun:

```
  Log::SetVerbosity( Log::Kind::Info );
  logError( WHATEVER, "this is a test" );
  logInfo( WHATEVER1, "this is a test" );
```

I get the following output: 

```
19.761 [WHATEVER Error] this is a test -> Function main
19.761 [WHATEVER1 Info] this is a test -> Function main
```

**Comment by MiguelCompany** [comment]
Info messages are only expected to work under Debug builds. As you can see [here](https://github.com/eProsima/Fast-RTPS/blob/e4b7865312916f14cd46d83825c48197701a4324/include/fastrtps/log/Log.h#L187-L188) the definition of the macro is protected by the definition of debug and internaldebug macros.

**Comment by nhreimer** [comment]
Thanks for the response. I did see that but I didn't know whether it was a bug/mistake because it's counterintuitive given that SetVerbosity(...) allows runtime control over message output but options for SetVerbosity are removed during compile time.

**Comment by MiguelCompany** [comment]
I see your point. We've been talking about this, and we think it may be a good idea to turn most of the current logInfo messages into logDebug calls and make that the one which is disabled on Release builds.

A new `Log::Kind::Debug` constant would be defined only on Debug builds to control the output of logDebug calls.

We have taken note on our internal task system and will close this issue.

Thank you for your feedback.
