### ISSUE TITLE
Too many open files -> Function Connect [4767]

### ISSUE THREAD

**Issue by bwilliamsH** [eProsima/Fast-RTPS#409]
Hello,
  I'm building from source and essentially using the examples in C++ on Ubuntu 16.04.  I have one machine subscribing to two publishers from two linux boxes on external IP addresses.  Occasionally I get this error:

2019-02-11 16:03:55.848 [RTCP Error] Openning socket open: Too many open files -> Function Connect

After I get it I stop receiving messages from the publishers and have to restart them in order to receive messages again.  Any help would be greatly appreciated.  thank you!

**Comment by LuisGP** [comment]
Hi @bwilliamsH,

The system shows that message when exhausts the available file descriptors for sockets. It shouldn't happen in a stable network.
Could you please share your configuration parameters for each node?
Did it happens at regular intervals, or it is random?
Eventually, every execution shows the error?
Only in the subscribers show the error, right?

Thank you very much.

**Comment by bwilliamsH** [comment]
Hello and thank you for your reply.  We ended up moving to use Participants at the higher level and are not seeing this problem.  I'll close this.
