### ISSUE TITLE
Fast-Cdr throw a exception [4768]

### ISSUE THREAD

**Issue by 43970117** [eProsima/Fast-RTPS#412]
Using ROS2 in Windows, the fast-CDR throw an NotEnoughMemoryException.
The crash back trace:
E0129 15:00:36.606562 52528 loghelper.cpp:24] *** Aborted at 1548745236 (unix time) try "date -d @1548745236" if you are using GNU date ***
E0129 15:00:36.756268 52528 loghelper.cpp:24] @ 0x7ff939a6d4cb raise
E0129 15:00:36.757266 52528 loghelper.cpp:24] @ 0x7ff939a6e561 abort
E0129 15:00:36.757266 52528 loghelper.cpp:24] @ 0x7ff939a6dc2f terminate
E0129 15:00:36.933893 52528 loghelper.cpp:24] @ 0x7ff72b0f9117 __scrt_unhandled_exception_filter
E0129 15:00:36.935889 52528 loghelper.cpp:24] @ 0x7ff93986bcf0 UnhandledExceptionFilter
E0129 15:00:36.937893 52528 loghelper.cpp:24] @ 0x7ff93c923167 memset
E0129 15:00:36.938880 52528 loghelper.cpp:24] @ 0x7ff93c90b5e6 __C_specific_handler
E0129 15:00:36.938880 52528 loghelper.cpp:24] @ 0x7ff93c91f7dd __chkstk
E0129 15:00:36.938880 52528 loghelper.cpp:24] @ 0x7ff93c88d856 RtlWalkFrameChain
E0129 15:00:36.939878 52528 loghelper.cpp:24] @ 0x7ff93c88be9a RtlRaiseException
E0129 15:00:36.939878 52528 loghelper.cpp:24] @ 0x7ff9397ba388 RaiseException
E0129 15:00:36.940899 52528 loghelper.cpp:24] @ 0x7ff9295a42cd _CxxThrowException
E0129 15:00:36.943876 52528 loghelper.cpp:24] @ 0x7ff9137d4170 private: char const * __ptr64 __cdecl eprosima::fastcdr::Cdr::readString(unsigned int & __ptr64) __ptr64
E0129 15:00:36.943876 52528 loghelper.cpp:24] @ 0x7ff9137d29c1 public: class eprosima::fastcdr::Cdr & __ptr64 __cdecl eprosima::fastcdr::Cdr::deserialize(class std::basic_string<char,struct std::char_traits,class std::allocator > & __ptr64) __ptr64
E0129 15:00:36.945886 52528 loghelper.cpp:24] @ 0x7ff9137b3770 bool __cdecl rcl_interfaces::msg::typesupport_fastrtps_cpp::cdr_deserialize(class eprosima::fastcdr::Cdr & __ptr64,struct rcl_interfaces::msg::ParameterEvent_<class std::allocator > & __ptr64)
E0129 15:00:36.946883 52528 loghelper.cpp:24] @ 0x7ff91637fd54 rmw_destroy_wait_set
E0129 15:00:36.947881 52528 loghelper.cpp:24] @ 0x7ff910153eeb public: virtual bool __cdecl rmw_fastrtps_shared_cpp::TypeSupport::deserialize(struct eprosima::fastrtps::rtps::SerializedPayload_t * __ptr64,void * __ptr64) __ptr64
E0129 15:00:36.951875 52528 loghelper.cpp:24] @ 0x7ff8ec2e489e public: virtual __cdecl eprosima::fastrtps::SubscriberListener::~SubscriberListener(void) __ptr64
E0129 15:00:36.951875 52528 loghelper.cpp:24] @ 0x7ff910151766 int __cdecl rmw_fastrtps_shared_cpp::__rmw_take_with_info(char const * __ptr64,struct rmw_subscription_t const * __ptr64,void * __ptr64,bool * __ptr64,struct rmw_message_info_t * __ptr64)
E0129 15:00:36.951875 52528 loghelper.cpp:24] @ 0x7ff91637f14f rmw_take_with_info
E0129 15:00:36.953840 52528 loghelper.cpp:24] @ 0x7ff9223c6619 rmw_take_with_info
E0129 15:00:36.954864 52528 loghelper.cpp:24] @ 0x7ff91febf0cb rcl_take
E0129 15:00:36.956832 52528 loghelper.cpp:24] @ 0x7ff906d7e6b2 protected: static void __cdecl rclcpp::executor::Executor::execute_subscription(class std::shared_ptr)
E0129 15:00:36.957829 52528 loghelper.cpp:24] @ 0x7ff906d7d553 protected: void __cdecl rclcpp::executor::Executor::execute_any_executable(struct rclcpp::executor::AnyExecutable & __ptr64) __ptr64
E0129 15:00:36.957829 52528 loghelper.cpp:24] @ 0x7ff906d83ad0 protected: void __cdecl rclcpp::executors::MultiThreadedExecutor::run(unsigned __int64) __ptr64
E0129 15:00:36.958853 52528 loghelper.cpp:24] @ 0x7ff906d83440 public: virtual __cdecl rclcpp::executors::MultiThreadedExecutor::~MultiThreadedExecutor(void) __ptr64
E0129 15:00:36.958853 52528 loghelper.cpp:24] @ 0x7ff906d82f89 public: virtual __cdecl rclcpp::executors::MultiThreadedExecutor::~MultiThreadedExecutor(void) __ptr64
E0129 15:00:36.958853 52528 loghelper.cpp:24] @ 0x7ff939a1c4ce _o_ceil
E0129 15:00:36.960845 52528 loghelper.cpp:24] @ 0x7ff93b3e3034 BaseThreadInitThunk
E0129 15:00:36.961818 52528 loghelper.cpp:24] @ 0x7ff93c8f3691 RtlUserThreadStart

* Operating System:
  
  * Windows 10
* Installation type:
  
  * from source
* Version or commit hash:
  eProsima/Fast-CDR:
  type: git
  url: https://github.com/eProsima/Fast-CDR.git
  version: v1.0.8
  eProsima/Fast-RTPS:
  type: git
  url: https://github.com/eProsima/Fast-RTPS.git
  version: b48ce9d2fba6fc94e756da01c58b72f2ad848238

**Comment by MiguelBarro** [comment]
We have been given some though to this issue. 

The problem has nothing to do with serialization mechanism (Fast-CDR) but from the upper layer (Fast-RTPS) that relies on it.

We require more context information. What are your endpoint QoS settings?

**Comment by 43970117** [comment]
The QoS used is the below:
static const rmw_qos_profile_t rmw_qos_profile_sensor_data =
{
  RMW_QOS_POLICY_HISTORY_KEEP_LAST,
  5,
  RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT,
  RMW_QOS_POLICY_DURABILITY_VOLATILE,
  false
};

**Comment by MiguelBarro** [comment]
That settings shouldn't arise any problem.

Reviewing your crash back trace we detected that the ParameterEvent.msg there mentioned is implementation dependent:
-  For cristal there is a string member.
-  For bouncy there isn't any string member.

Could it be possible that not all your nodes are running the same ROS2 instance? There are several scenarios that may justify the crash. :

-  some of them use cristal and others bouncy. 
-  the cristal update that introduces the string was made on Dec 4 2018. Are all your cristal instances up-to-date?
	
Please, let us know.

**Comment by 43970117** [comment]
Thank you. You are right. My application has nodes, one Windows node, many Linux nodes. I am sure of the windows node ROS 2 Crystal Clemmys, which is built from source. Linux nodes is built from source, it is master branch. Its date is about Oct.  After checked, ParameterEvent.msg for Windows has a more string node field, while the Linux's has no. 

This issue happened after running for many hours, though,  do you mean they are incompatible?

**Comment by MiguelBarro** [comment]
Happy you work it out. 
		
From the Fast-RTPS point of view they are incompatible. According to the [standard](http://www.omg.org/spec/DDSI-RTPS/2.2) two RTPS endpoints MUST share the same topic otherwise serialization trouble would arise.
		
Why it took so long to break down? Our ROS pundits can only conjecture:
		
- According to [ROS2 design](https://design.ros2.org/articles/ros_parameters.html) parameter events may not be triggered often.

- Fast-CDR only throws an exception when a serialization error is detected. Most errors would go undetected. For example, if the buffer address where the string length was supposed to be keeps 0s, no exception would have been thrown.
