### ISSUE TITLE
ObjectPool.cpp [4769]

### ISSUE THREAD

**Issue by AnandShastry** [eProsima/Fast-RTPS#416]
I tried including all files as source for compiling Fast-RTPS. I am not much aware of why ObjectPool.cpp is not included for compilation. But in future if this needs to be included, some of the references this file includes needs to be corrected.

ex: CDRMessage_t.h doesnt exist in the path mentioned

**Comment by richiware** [comment]
#433 removes that old file. I will close this issue. Thanks.
