### ISSUE TITLE
An error occurs when installing 1.7 with the option of -DBUILD_JAVA = ON [4770]

### ISSUE THREAD

**Issue by kozueikeda** [eProsima/Fast-RTPS#417]
The environment is below.

OS: Windows 7, Windows 10 64 bit
cmake: 3.13.4
OpenSSL: 1 _ 0 _ 2
Java: 1.8.0_201
gradle: 5.2.1

Installation with the following command will succeed.

cmake - G "Visual Studio 14 2015 Win 64" - DTHIRDPARTY = ON
cmake --build. --target install

When DBUILD_JAVA is turned on as follows,
An error will occur while executing the command of the second line.
cmake - G "Visual Studio 14 2015 Win 64" - DTHIRDPARTY = ON - DBUILD - JAVA = ON
cmake --build. --target install

The error is as follows.
C: \ Program Files (x86) \ MSBuild \ Microsoft.Cpp \ v4.0 \ V140 \ Microsoft.CppCommon.targets (171, 5):
 error MSB 6006: "cmd.exe" exited with code 1. [C: \ Fast-RTPS \ build \ java.vcxproj]
 

If you know the steps and settings necessary to resolve this error and install it
Please kindly advise.

**Comment by kozueikeda** [comment]
additional information.
I installed only installed SDK 1.8
An error occurred.

We downgraded the gradle version to 5.0
A similar error occurred.

**Comment by murikill** [comment]
I've the same issue...

**Comment by LuisGP** [comment]
Hi,

if the first time you executed `cmake --build .` was with a non-JDK version of Java, the generated CMake cache files will keep the reference to that version, so you must to clean all build directory and execute again both cmake commands.

If this doesn't solve the problem let us know.

**Comment by LuisGP** [comment]
As this was answered and no comments were received, we close the issue. Feel free to reopen it if there is more clarification needed.

**Comment by sgmenon** [comment]
I also ran into this problem. I debugged it a bit and was able to get around this by changing
Fast-RTPS\cmake\dev\java_support.cmake
```powershell
> diff --git a/cmake/dev/java_support.cmake b/cmake/dev/java_support.cmake
index 8c018230..7f1bf855 100644
--- a/cmake/dev/java_support.cmake
+++ b/cmake/dev/java_support.cmake
@@ -16,6 +16,7 @@ macro(gradle_build directory)
     find_package(Java 1.6 COMPONENTS Runtime REQUIRED)
     if(WIN32)
         find_program(GRADLE_EXE NAMES gradle gradle.exe gradle.bat)
+        set(GRADLE_EXE ${GRADLE_EXE}.bat )
     else()
         find_program(GRADLE_EXE gradle)
     endif()
```

it looks like the "cmake -E" command needs the full path to gradle

**Comment by dahaosoft** [comment]
> As this was answered and no comments were received, we close the issue. Feel free to reopen it if there is more clarification needed.

Hi LuisGP,
Well, you can reopen it, the v1.7.2 still occurs.

**Comment by MiguelCompany** [comment]
Also present in develop. Reopening issue.

**Comment by LuisGP** [comment]
Hi,
@dahaosoft and @sgmenon could you please test if develop branch solved the issue?

**Comment by LuisGP** [comment]
As this was answered and no comments were received, we close the issue. Feel free to reopen it if there is still any related problems.
