### ISSUE TITLE
Using the same ParticipantID on multiple DomainIDs [4753]

### ISSUE THREAD

**Issue by AndreasRentschler** [eProsima/Fast-RTPS#419]
When registering a participant, we assign our *own participant ID*. Our reason for manually assigning participant IDs is to support the unicast discovery mechanism: FastRTPS opens a listening UDP port with a port number derived from the participant ID. To establish the unicast discovery, we have to know all ports in advance, i.e., we have to know the participant IDs.

On the other hand, we want our FastRTPS clients to register participants over *multiple domains*. This does not work when the same client registers participants with the same ID but on different domains, as the FastRTPS implementation requires participant IDs to be globally unique. This is a constraint that is purely local to a client. Taking a quick look in the FastRTPS sources, the single reason our case is rejected is a global lookup set in [RTPSDomain.h](https://github.com/eProsima/Fast-RTPS/blob/v1.6.0/include/fastrtps/rtps/RTPSDomain.h), `std::set<uint32_t> RTPSDomain::m_RTPSParticipantIDs;`. A simple fix would be to maintain a set of tuples of participant ID and domain ID instead, something along the lines of `std::set<std::tuple<uint32_t, uint32_t>> RTPSDomain::m_RTPSParticipantIDs;`.

Are there conceptual or technical reasons for the current constraint we are not aware of, or could it be relaxed in the suggested way or another?

We are working on FastRTPS v1.6.0, but the issue seems to be at least present on v1.7.0.

**Comment by MiguelCompany** [comment]
Hi @AndreasRentschler 

Although the change you propose may be a good idea, you could use a different approach to accomplish your goal of using unicast discovery. Just set the `metatrafficUnicastLocatorList` attribute of the [participant's built-in parameters](https://eprosima-fast-rtps.readthedocs.io/en/latest/xmlprofiles.html#built-in-parameters) to override the default port mapping.

**Comment by MiguelCompany** [comment]
I am closing this, as the OP was pointed to an alternative solution. Feel free to reopen if still an issue.
