### ISSUE TITLE
Processing solidifies when publisher is executed with sample source HelloWorldExampleTCP [4923]

### ISSUE THREAD

**Issue by kozueikeda** [eProsima/Fast-RTPS#427]
If I run the sample source HelloWorldExampleTCP with localhost,
I could communicate without trouble in the local PC.

If Ｉ specify an IP address and test over the network,
There is a phenomenon that the published application hangs up.

The number of samples is infinite, and the interval is 100 msec.

Please tell me if necessary settings etc.

**Comment by LuisGP** [comment]
Hi @kozueikeda 

Which branch/version of Fast-RTPS are you using?
Which arguments are you passing to HelloWorldExampleTCP on each role (publisher/subscriber)?
When you say "over the network" you mean a LAN or a WAN environment?

**Comment by kozueikeda** [comment]
The version of FastRTPS is 1.7.1.
The argument uses subscriber.
An error has occurred when FastRTPS is a subscriber and OpenSplice is a publisher .
The network uses a LAN environment.

**Comment by LuisGP** [comment]
Hi @kozueikeda 

We need more details about your setup to reproduce the issue. Could you paste the commands and output from publisher and subscriber?

Thank you very much.

**Comment by kozueikeda** [comment]
I'm sorry.
It occurs in v1.7.0,
This issue has been resolved by upgrading to v1.7.1.
