### ISSUE TITLE
Feature Request: Support for Deadline, Liveliness, and Lifespan QoS policies

### ISSUE THREAD

**Issue by nburek** [eProsima/Fast-RTPS#429]
There is a design document for ROS 2 that is adding support for Deadlines, Liveliness, and Lifespan on ROS topics and services (https://github.com/ros2/design/pull/212). These new ROS QoS settings are designed to correlate with the same DDS QoS settings so the rmw implementations can take advantage of them. 

I wanted to create this issue to track adding support to Fast-RTPS for these settings. My team has already been looking at the work required to add these settings to Fast-RTPS and we can put together a document to share here on what we think the work would be if that is useful to have with this issue. We are happy to help with implementing these as well, but before we go to far it would be good to know what work is being done by others around additional QoS policies in FastRTPS to avoid duplication of effort.

**Comment by LuisGP** [comment]
Hi @nburek 
Take a look at #468
