### ISSUE TITLE
An error occurs in communication between OpenSplice and FastRTPS (v1.7)

### ISSUE THREAD

**Issue by kozueikeda** [eProsima/Fast-RTPS#435]
I am trying to communicate with OpenSplice with FastRTPS (v1.7).
  I launched publisher with FastRTPS, started subscriber with OpenSplice, and then write topic,
  The following error has occurred in publisher..
 
   [RTCP_MSG_IN Error] Size of incoming TCP message is bigger than buffer capacity: 33620212 vs. 65500. The full message will be dropped. -> Function eprosima :: fastrtps :: rtps :: TCP TransportInterface :: Receive
  
   In the case of OpenSplice and FastRTPS, we can communicate without problems.
   Can I change the capacity setting in FastRTPS?

**Comment by LuisGP** [comment]
Hi @kozueikeda 

For TCP communication Fast-RTPS implements the TCP/IP PSM for DDS-RTPS proposal. Seems that OpenSplice uses another way to encapsulate the RTPS traffic using TCP, so the compatibility is not possible.
In the other hand, as our TCP transport implementation is still a proposal from the OMG it may change in the future.

**Comment by kozueikeda** [comment]
Thank you for your reply.
I understand that FastRTPS and OpenSplice are not compatible with TCP communication.
