### ISSUE TITLE
Issue in Keys example [5624]

### ISSUE THREAD

**Issue by HorizonAD** [eProsima/Fast-RTPS#437]
I'm trying to run Keys example , following issue happeed.
It seems like that publisher and subscriber doesn't match when " Publishing 5 keys, 10 samples per key".

Publisher
yale@yale-ThinkPad-T470:~/FastRTPS/Fast-RTPS/build$ ./examples/C++/Keys/keys publisher
Creating Publisher...
Publishing 5 keys, 10 samples per key...
2019-02-27 16:59:28.736 [PUBLISHER Error] Change not found, something is wrong -> Function remove_change_pub
......
2019-02-27 16:59:28.738 [PUBLISHER Error] Change not found, something is wrong -> Function remove_change_pub
Publishing 10 more samples on a key 3...

Subscriber
yale@yale-ThinkPad-T470:~/FastRTPS/Fast-RTPS/build$ ./examples/C++/Keys/keys subscriber
Creating Subscriber...
1Message 11 RECEIVED
2Message 12 RECEIVED
3Message 13 RECEIVED
4Message 14 RECEIVED
5Message 15 RECEIVED
6Message 16 RECEIVED
7Message 17 RECEIVED
8Message 18 RECEIVED
9Message 19 RECEIVED
10Message 20 RECEIVED

**Comment by HorizonAD** [comment]
It seems like it is caused by the durability configureation, if it is TRANSIENT_LOCAL_DURABILITY_QOS for both publisher and subscriber, then it would work well.

**Comment by AlvaroMolinillo** [comment]
Hi @HorizonAD
We have solved that issue. It was a log trace that shouldn't appear. It was not a real bug. The application works fine, and for the moment, you could ignore that trace. Anyway, we will realease a patch soon.

Thank you for reporting the issue.
Best regards!

**Comment by cvilas** [comment]
I don't understand the point of the keys example. What is it really trying to demonstrate. If you fixed the issue with matching that the original poster raised, every message published, irrespective of the key, gets received by the subscriber. The behavior is exactly the same if topicKind is set to NO_KEY for both publisher and subscriber.
