### ISSUE TITLE
cppcheck errors

### ISSUE THREAD

**Issue by dherring** [eProsima/Fast-RTPS#449]
Cppcheck is a static analysis tool.  It found a few errors in this code (member values not initialized in constructor, pointer set null but not freed, undefined behavior, ...).  It also offers many suggestions such as passing parameters by reference.

Please use tools like cppcheck as a regular part of your development.

Example run:
```
mkdir build
cd build
cmake "-DCMAKE_CXX_CPPCHECK=/usr/bin/cppcheck;--std=c++11" -DTHIRDPARTY=ON ..
make -j6 > log 2>&1
```

Example fix:
```
include/fastrtps/qos/QosPolicies.h:
-    RTPS_DllAPI TypeConsistencyEnforcementQosPolicy() {};
+    RTPS_DllAPI TypeConsistencyEnforcementQosPolicy() :
+                 m_kind(DISALLOW_TYPE_COERCION),
+                 m_ignore_sequence_bounds(true),
+                 m_ignore_string_bounds(true),
+                 m_ignore_member_names(false),
+                 m_prevent_type_widening(false),
+                 m_force_type_validation(false)
+   {};
```

Useful links:
https://blog.kitware.com/static-checks-with-cmake-cdash-iwyu-clang-tidy-lwyu-cpplint-and-cppcheck/
https://github.com/lefticus/cppbestpractices/blob/master/02-Use_the_Tools_Available.md

**Comment by LuisGP** [comment]
Hi @dherring 
Thank you very much for reporting this issue. We will integrate cppcheck in the future as part of #210.
In the same way, I'm closing the issue because it was addressed.
