### ISSUE TITLE
Increase of RSS memory due to the memory pool for serialization RTPS submessages

### ISSUE THREAD

**Issue by richiware** [eProsima/Fast-RTPS#451]
This issue is opened for tracking a bug that is already fixed on branch [feature/write_nonblocking](https://github.com/eProsima/Fast-RTPS/tree/feature/write_nonblocking).

This bug was detected using [performance_test](https://github.com/ApexAI/performance_test). This tool discovered an unusual increase of RSS memory. The CDRMessagePool object was responsible for it.

**Comment by alsora** [comment]
That's great!

I wanted to test an example in the `feature/write_nonblocking` branch and actually the memory footprint is reduced.

According to Valgrdind's heap profiler (`valgrind --tool=massif --trace-children=yes CMD`) the `CDRMessaagePool` object is not created anymore (it was taking 1MB of memory).

Moreover, now I do not see anymore the calls to `rtps::EDPSimple::create_sedp_secure_endpoints` and to `rtps::WLP::createSecureEndpoints`.
Each of these objects was ~64KB.

This reduces the size of :

- `rtps::ReaderHistory` and `rtps::WriterHistory` from ~550KB  to ~350KB, each.
- `rtps::RTPSParticipantImpl` from ~383KB to ~191KB.

In the plots these reductions can be seen from the reduced size of `rtps::History`from 1.1MB to 657KB and of each `RTPSWriter` from 447KB to 255KB

![fastrtps_merged](https://user-images.githubusercontent.com/25433200/54552746-b7e3be00-49a8-11e9-8953-18fb25e742a5.png)

**Comment by MiguelCompany** [comment]
Closing this as branch `feature/write_nonblocking` was already merged into master
