### ISSUE TITLE
ReaderProxy histroy reloaded incorrectly

### ISSUE THREAD

**Issue by guillaumeautran** [eProsima/Fast-RTPS#452]
When a new reader is added to a state-full writer and the the last cachechange in the writer history have been deleted, the ReaderProxy history cache is not reloaded properly causing a missing GAP message.

**Comment by guillaumeautran** [comment]
I think the PR related to this issue has been merged already. Can we close this?

**Comment by raquelalvarezbanos** [comment]
Yes, it was merged. This issue should be closed automatically when it gets merged into master.

**Comment by raquelalvarezbanos** [comment]
I am closing this issue as the PR was merged and it wasn't closed automatically.
