### ISSUE TITLE
Compile on windows with Microsoft Visual Studio 10 2010 x64

### ISSUE THREAD

**Issue by murikill** [eProsima/Fast-RTPS#454]
Hi, 

I'm very interested in Fast-RTPS DDS solution and my question is:

 - is it posible to compile from source by using of Microsoft Visual Studio 10 2010 x64 compiler? Or do you know quick hack to solve my issue? 

Thanks!

**Comment by richiware** [comment]
Fast-RTPS source code uses CMake as a build system. CMake permits to select the version of the Visual Studio using the argument `-G`.

```bash
cmake -G "Visual Studio 15 2017 Win64"
```
But I don't think it will work with Visual Studio 2010. Fast-RTPS uses c++11 and it is not fully supported on that version of Visual Studio. Why a compiler so old?

**Comment by murikill** [comment]
Thank you for your reply,

my another programms/dependencies need this...
