### ISSUE TITLE
RTPS Domain hostid part of the GUID match first interface IP [4969]

### ISSUE THREAD

**Issue by guillaumeautran** [eProsima/Fast-RTPS#456]
Given the code [here](https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/rtps/RTPSDomain.cpp#L113) to determine and assign a participant GUID, the "hostid" portion of the GUID (first 4 bytes) is initialized with eProsima prefix (0x010f) and the last two digit of the IPv4 address of the first network interface found. 
On system with several interfaces, most of which internals, this scheme is not sufficient for generating a mostly unique hostid to be used for the RTPS Domain. 

When the Fast-RTPS process is started as part of the boot sequence, the process ID can often be the same on multiple machines causing multiple participant to have the exact same GUID and confuse each-others.

A more robust approach (on linux and osx) would be to make a call to the [gethostid(2)](https://linux.die.net/man/2/gethostid) method and use the information received to initialized the hostid portion of the RTPS GUID.

**Comment by MiguelCompany** [comment]
Pull request #53 suggested a different way to adress this, by using the MD5 hash of all the returned interfaces. It may be a nice mechanism ... ¿thoughts?

**Comment by guillaumeautran** [comment]
I supposed we could do something with the hash of the MAC address of the interface, yes. This would be a lot more unique compared to an ip especially when you have many interfaces. Considering using all of the MAC addresses for all interfaces might actually work better and cover most if not all cases.

**Comment by guillaumeautran** [comment]
Just looked at the original pull request. I'll play around with it and see how I can make it work more broadly.

**Comment by guillaumeautran** [comment]
I think the PR to address this issue has been merged. Can we close this issue then?

**Comment by MiguelCompany** [comment]
Should automatically close tomorrow when it gets into master
