### ISSUE TITLE
Participant with different lease expiration timeout fail to reconnect [4971]

### ISSUE THREAD

**Issue by guillaumeautran** [eProsima/Fast-RTPS#457]
Given two participants on a network, if both participant have a different participant lease timeout value (for example, one has 120s lease while the other has 360s lease). When the network gets disconnected and the participant with the shorter lease timeout expire, if the network connection is reconnected before the longer lease participant had the opportunity to timeout, then communication cannot be re-established.

**Comment by richiware** [comment]
Sound as a regression. This was fixed on #155. We will look into it. Thanks.

**Comment by guillaumeautran** [comment]
Yes, this looks exactly like the issue linked.
Notes that I noticed / reproduced the problem on Fast-Rtps v1. 7.1

**Comment by guillaumeautran** [comment]
Ping, any insight about what might be happening here?

**Comment by LuisGP** [comment]
Hi @guillaumeautran 

We are working in a hotfix for this. We have been able to reproduce it in a network environment (and the hotfix is ready) but we haven't in localhost.

We want to understand why is this happening and make sure it doesn't have any side effects before releasing the hotfix. Being able to reproduce it on localhost will allow us to create a test for this issue.

Best regards.
