### ISSUE TITLE
Single test takes four minutes

### ISSUE THREAD

**Issue by dirk-thomas** [eProsima/Fast-RTPS#46]
The test BlackBox.AsyncPubSubAsNonReliableData300kb takes four minutes (240606 ms). Compared to all the other tests that is significant. If the test can't be speed up it might make sense to not run it by default.

**Comment by PabloMansanet** [comment]
Hello Dirk,

We have reviewed all NonReliable tests so they take substantially less; this one should be running in around 10 seconds for the next release.

Thanks!

**Comment by richiprosima** [comment]
Hi @dirk-thomas

Non-reliable tests were refactored in version 1.2.0. This test takes now 15
seconds. Thanks.
