### ISSUE TITLE
Maximum serialized size of the type in bytes [5089]

### ISSUE THREAD

**Issue by chengwei920412** [eProsima/Fast-RTPS#474]
TopicDataType::m_typeSize
If the type has unbounded fields, and therefore cannot have a maximum size, use 0.
but, i get a error."2019-04-02 10:47:39.226 [PARTICIPANT Error] Registered Type must have maximum byte size > 0 -> Function eprosima::fastrtps::ParticipantImpl::registerType"

**Comment by LuisGP** [comment]
Hi @chengwei920412 

Currently, Fast-RTPS doesn't support types with maximum size 0, but in next major releases, it will be probably supported.
