### ISSUE TITLE
Building with -DSECURITY=ON increases memory usage also in non-secured applications [5082]

### ISSUE THREAD

**Issue by alsora** [eProsima/Fast-RTPS#482]
Hi,

I built Fast-RTPS master branch using the CMake argument `-DSECURITY=ON`

Then I ran the HelloWorldExample (which does not use security).

The problem is that the memory usage is considerably higher than if I would have built Fast-RTPS with `-DSECURITY=OFF`.

The difference in memory is mainly caused by the fact that 

1) Additional secured end-points are created together with the usual non-secured end-points by [EDPSimple::initEDP method](https://github.com/eProsima/Fast-RTPS/blob/release/1.7.2/src/cpp/rtps/builtin/discovery/endpoint/EDPSimple.cpp#L124)
2) A third object of type `CDRMessage_t` is created in each [RTPSMessageGroup](https://github.com/eProsima/Fast-RTPS/blob/release/1.7.2/include/fastrtps/rtps/messages/RTPSMessageGroup.h#L42)

I got the following numbers running HelloWorldExample subscriber with FastRTPS v1.7.2

Resident set size computed using `ps` or `top` 

 - RSS Security ON:   11.3MB
 - RSS Security OFF:  9MB

The difference increases with the number of pubs/subs created in each participant.

I think that the decision at the build time should not cause any additional memory allocation.

Moreover I think that, from the ROS2 point of view, having both secured as well as not secured end-points inside a node is not useful, as secured processes will not be able to see/communicate non secured ones.
However, maybe this feature is required for other Fast-RTPS implementations.

**Comment by MiguelCompany** [comment]
This was fixed on #[479](https://github.com/eProsima/Fast-RTPS/pull/479/files#diff-667a9e1219bfacd17199a05bcced6d75) which was released with 1.9.0, so I think it may be closed
