### ISSUE TITLE
Interoperability configuration xml for RTI

### ISSUE THREAD

**Issue by neeleym** [eProsima/Fast-RTPS#484]
Moving this over from Micro-XRCE-DDS as this is an RTPS interoperability question ...

I was reviewing the Shapes Demo for interoperability testing and came across this documentation:

https://eprosima-shapes-demo.readthedocs.io/en/latest/troubleshooting.html

In this description you mention the existence of RTISHAPESDEMOQOSPROFILES.xml . I didn't find this file in the distribution anywhere. Can you supply this file or give me a location where to find it?

Thanks

**Comment by LuisGP** [comment]
Hello @neeleym 

That file belongs to RTI Shapes Demo. In its current version seems that they renamed to *RTI_SHAPES_DEMO_QOS_PROFILE.xml*. Once RTI Shapes Demo is installed, you can find the file under *resource/xml* folder.

**Comment by LuisGP** [comment]
As this was answered and no comments were received, we close the issue. Feel free to reopen it if there is more clarification needed.
