### ISSUE TITLE
profiling tests fail without valgrind

### ISSUE THREAD

**Issue by dirk-thomas** [eProsima/Fast-RTPS#49]
They should be disabled if `valgrind` is not available. It would also be good to use the `valgrind` executable found in CMake (https://github.com/eProsima/Fast-RTPS/blob/a742bdbc17946e4ff712d395d3365a122df06476/CTestJenkins.cmake#L40) rather then the hard coded name.

**Comment by PabloMansanet** [comment]
Last minute solved for 1.2.0. Thanks for the heads up!

**Comment by dirk-thomas** [comment]
For the record the change is in aa47b4621791f54b7c69447f2b442c2455a9c151.
