### ISSUE TITLE
IDL: Support for setting float/double constants to +/- inf

### ISSUE THREAD

**Issue by raykraft** [eProsima/Fast-RTPS#498]
This feature request is for allowing the specification of IEEE 754-1985 positive and negative infinity for assignment to constants of type double and float in IDL specification.

Example:
   const float FOO = -inf

**Comment by LuisGP** [comment]
Hi @raykraft 

The IDL 4.2 specification doesn't support "inf" as a floating-point literal, so we have no plan to support it.
