### ISSUE TITLE
test UDPv4Tests hangs on OS X

### ISSUE THREAD

**Issue by dirk-thomas** [eProsima/Fast-RTPS#50]
The test hangs forever: http://ci.ros2.org/job/ci_osx/1180/console, http://ci.ros2.org/job/ci_osx/1181/console

**Comment by richiprosima** [comment]
@dirk-thomas I was checking that test. I found this [line](https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/transport/UDPv4Transport.cpp#L287) causes the hanging. Commenting it the test doesn't hang. Any idea why this occurs in Mac OSX, and only in this test and not ever?

**Comment by dirk-thomas** [comment]
I don't know why it is specific to OS X but on our builds since yesterday it was pretty much happening always as far as I know.

**Comment by richiprosima** [comment]
@dirk-thomas I commented the tests causing the hanging on Mac OSX .
