### ISSUE TITLE
Support localhost and container connection?

### ISSUE THREAD

**Issue by daohu527** [eProsima/Fast-RTPS#501]
I have a condition like this: 
1. one client in localhost
2. one client in the docker, and the docker is in localhost.
I want to connect them use fast-rtps. Is this condition support? How to deal with it?

**Comment by LuisGP** [comment]
This purely a docker container configuration question. Seems that you were answered in [#7995](https://github.com/ApolloAuto/apollo/issues/7995). I'm closing the issue but if you need more information feel free to reopen it.
