### ISSUE TITLE
New Feature: Implementation of manual assertion and events for Liveliness QoS policy

### ISSUE THREAD

**Issue by nburek** [eProsima/Fast-RTPS#503]
There is an ongoing project to support the Liveliness QoS feature in the Dashing release of ROS 2. Support for this in rmw_fastrtps is blocked on the Liveliness feature being fully supported in Fast-RTPS. This includes both the ability to assert manual liveliness and also the ability to be notified of changes to liveliness. 

Below is the list of everything that we think still needs to be implemented in order to support Liveliness. If there is ongoing work towards any of these please let us know. Otherwise we can start to send over Pull Requests towards implementing this feature.

### Writer
- [ ] Set the aliveness flag on a **Writer** when the manual assertion is called or when messages are published
- [ ] Add a timed event that sends out the heartbeat for a **Writer** using MANUAL_BY_TOPIC level of liveliness and clears the aliveness flag on the **Writer**
- [ ] Set the aliveness flag on a **Participant** when the manual assertion is called or when there is activity on any of the **Writers** on the **Participant**
- [ ] Create a timed event that handles when the liveliness expires on a **Writer** and generates the on_liveliness_changed event
- [ ] Keep a counter for heartbeat messages sent on a **Participant** using MANUAL_BY_PARTICIPANT and have it send out the corresponding message for Simple Participant Discovery Protocol (SPDP) that reflects the updated count when it changes

### Reader
- [ ] Implement `StatelessReader::processHeartbeatMsg()`
- [ ] Expand `StatefulReader::processHeartbeatMsg()` to track information on WriterProxies
- [ ] Create a timed event for notifying when liveliness expires on a **Writer** or **Participant**

**Comment by raquelalvarezbanos** [comment]
Hi @nburek, thanks for opening this issue.

We have indeed started working on this QoS. We finished a design this week that involves a bit more work than what you mention (as an example, one thing we have to consider is that liveliness should also be supported for stateless readers, which is not currently the case in Fast-RTPS). The plan is to release this QoS in 1.8.1. I can keep you updated on the progress if you like.

**Comment by adam-dunc** [comment]
Hi @raquelalvarezbanos, thank you for the quick reply. We have two developers working on this and would be more than happy to collaborate with you on development: designs, testing as well as contribute code. We can continue to submit updates here if thats easiest or jump on a call. 

What are your current timelines for v.1.8.1?

**Comment by raquelalvarezbanos** [comment]
Hi both,
Sorry for the delay in responding. The rest of this week is bank holiday here, but we can arrange a call next week to discuss timelines and see if we can collaborate on this. I will check with @JaimeMartin when the best time would be for us (we are away Monday and Tuesday), and we can suggest a date and a time, if that works for you.

**Comment by rutvih** [comment]
@raquelalvarezbanos Let us know when would be a good time to chat more about this. Happy to setup a call if you could suggest time that works best for you!

**Comment by emersonknapp** [comment]
Bumping this issue - it looks like `release/1.8.1` branch adds `Publisher::assert_liveliness`, but not `Participant::assert_liveliness` yet

**Comment by raquelalvarezbanos** [comment]
Hi All, since liveliness was implemented as part of release 1.8.1, please let us know if this issue can be now closed. Thanks!
