### ISSUE TITLE
question: delete publisher in  Fast-RTPS/src/cpp/participant/ParticipantImpl.cpp 

### ISSUE THREAD

**Issue by jilinzhou** [eProsima/Fast-RTPS#504]
It seems the **publisher** itself does not get deleted
```
bool ParticipantImpl::removePublisher(Publisher* pub)
{
    for(auto pit = this->m_publishers.begin();pit!= m_publishers.end();++pit)
    {
        if(pit->second->getGuid() == pub->getGuid())
        {
            delete(pit->second);
            m_publishers.erase(pit);
            return true;
        }
    }
    return false;
}

// There are two new operators are called in createPublisher as the following:
Publisher* ParticipantImpl::createPublisher(
        const PublisherAttributes& att,
        PublisherListener* listen)
{
...
    PublisherImpl* pubimpl = new PublisherImpl(this,p_type,att,listen);
    Publisher* pub = new Publisher(pubimpl);
    pubimpl->mp_userPublisher = pub;
    pubimpl->mp_rtpsParticipant = this->mp_rtpsParticipant;
...
}
```

**Comment by MiguelBarro** [comment]
It's a little cumbersome but it Works as follows: ParticipantImpl keeps its publishers in the container t_v_PublisherPairs m_publishers where 
	
	typedef std::pair<Publisher*,PublisherImpl*> t_p_PublisherPair;
	typedef std::vector<t_p_PublisherPair> t_v_PublisherPairs;
	
So in the removal:
	
	bool ParticipantImpl::removePublisher(Publisher* pub)
	{
		for(auto pit = this->m_publishers.begin();pit!= m_publishers.end();++pit)
		{
			if(pit->second->getGuid() == pub->getGuid())
			{
				delete(pit->second);	// deletes the PublisherImpl object
				m_publishers.erase(pit);
				return true;
			}
		}
		return false;
	}
	
The PublisherImpl destructor:
	
	PublisherImpl::~PublisherImpl()
	{
		if(mp_writer != nullptr)
		{
			logInfo(PUBLISHER, this->getGuid().entityId << " in topic: " << this->m_att.topic.topicName);
		}

		RTPSDomain::removeRTPSWriter(mp_writer);
		delete(this->mp_userPublisher); // deletes the Publisher object
	}
	
deletes the referenced (Publisher* mp_userPublisher) object pass in construction.
	
So both PublisherImpl and Publisher get deleted in ParticipantImpl::removePublisher.

**Comment by jilinzhou** [comment]
@MiguelBarro : Thanks for the detailed trace through.
