### ISSUE TITLE
Large published data not received on remote device

### ISSUE THREAD

**Issue by khuang024** [eProsima/Fast-RTPS#506]
I'm writing a sample demo using publisher and subscriber.
When the publisher and subscriber are launched on the same device. The demo works with both small and large data (3 MB).
But when the publisher and subscriber launched on different devices the subscriber can receive small data when only small data is published. But the subscriber cannot receive any data when only large data is published.

The large data size is about 3 MB and published 10 times/second.

I've configured the net.core.rmem_max and net.core.wmem_max to 26M

The configurations of the publisher and subscriber are listed as below

For publisher

    ParticipantAttributes PParam;
  
    PParam.rtps.builtin.leaseDuration = c_TimeInfinite;
    PParam.rtps.builtin.writerHistoryMemoryPolicy =
    PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
    PParam.rtps.sendSocketBufferSize = 30000000;

    PublisherAttributes Wparam;
    Wparam.topic.topicKind = WITH_KEY;
    Wparam.topic.topicDataType = ...
    Wparam.topic.historyQos.depth = 5;
    Wparam.qos.m_reliability.kind = RELIABLE_RELIABILITY_QOS;
    Wparam.qos.m_publishMode.kind = ASYNCHRONOUS_PUBLISH_MODE;
    Wparam.topic.historyQos.kind = KEEP_LAST_HISTORY_QOS;
    Wparam.historyMemoryPolicy = DYNAMIC_RESERVE_MEMORY_MODE;

For subscriber

    ParticipantAttributes PParam;
    PParam.rtps.builtin.leaseDuration = c_TimeInfinite;
    PParam.rtps.builtin.readerHistoryMemoryPolicy = PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
    PParam.rtps.listenSocketBufferSize = 30000000;

    SubscriberAttributes Rparam;
    Rparam.topic.topicKind = WITH_KEY;
    Rparam.topic.topicDataType = ...
    Rparam.qos.m_reliability.kind = RELIABLE_RELIABILITY_QOS;
    Rparam.historyMemoryPolicy = DYNAMIC_RESERVE_MEMORY_MODE;

**Comment by LuisGP** [comment]
Hi @khuang024 

Can you test your application using the branch 1.8.0?

Thank you very much.

**Comment by khuang024** [comment]
OK We'll test with that.
Thank you

**Comment by LuisGP** [comment]
As this was answered and no comments were received, we close the issue. Feel free to reopen it if the problem persists.
