### ISSUE TITLE
Messages not received after participant rediscovery

### ISSUE THREAD

**Issue by cvilas** [eProsima/Fast-RTPS#514]
We are operating over 5GHz WiFi on BestEffort QoS, sending 6kB/sec messages (10Hz) across two RTPS participants - one implements a reader and the other a writer. Occasionally we would notice the writer node drop out momentarily - we get a  DROPPED_PARTICIPANT notification - we think due to wifi interference. Usually, in a matter of seconds, the participant gets rediscovered - we get a DISCOVERED_PARTICIPANT notification. However, the reader does not resume receiving messages. 

One really strange behaviour (to me) is that if I were now to run another program with nothing more than a participant on the domain (no publishers or subscribers), but implements a custom listener to subscribe to discovery topics (exactly as per section 9.6 of the Fast RTPS 1.7.2 manual), then the other reader node starts receiving messages again. Does introducing this unrelated participant into the domain trigger something in the discovery process for existing readers and writers? This behaviour is consistent. 

Either way, my issue is that the reader does not resume receiving messages after a dropout. I am not specifically configuring reader or writer liveliness or heartbeat settings. Any ideas how I could ensure readers and writers robustly find each other after a network brownout?

**Comment by cvilas** [comment]
After further experimentation running the HelloWorldExample, it seems like while particpant discovery works as it should, the endpoint discovery does not. Specifically, remote endpoints (ie. readers and writers not on the localhost) aren't always discovered (or not discovered soon enough), and this causes the communication to stall after a participant rediscovery. I am able to reproduce this with the HelloWorldExample (changed only to set QoS to best effort)

**Comment by MiguelCompany** [comment]
This seems to be the same as #457, which has been solved on #505.

**Comment by cvilas** [comment]
@MiguelCompany : Will this be available in v1.8.0?

**Comment by MiguelCompany** [comment]
@cvilas YES

**Comment by cvilas** [comment]
Been testing the *develop* branch with the fix in it all morning. Definitely seems better - seems to always recover from a connection loss. Thank you!

**Comment by LuisGP** [comment]
As the fix for this issue is already in develop branch and soon in release 1.8.0, I'm closing it.
