### ISSUE TITLE
examples fail to build [5690]

### ISSUE THREAD

**Issue by gaoyadianta** [eProsima/Fast-RTPS#517]
i have tried to build the examples from the source code in eProsima_FastRTPS-1.7.1-Linux/examples/C++/HelloWorldExample, when i tried "cmake .. " i got this:

```
CMake Error at CMakeLists.txt:25 (find_package):
  By not providing "Findfastcdr.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fastcdr", but
  CMake did not find one.

  Could not find a package configuration file provided by "fastcdr" with any
  of the following names:
    fastcdrConfig.cmake
    fastcdr-config.cmake
  Add the installation prefix of "fastcdr" to CMAKE_PREFIX_PATH or set
  "fastcdr_DIR" to a directory containing one of the above files.  If
  "fastcdr" provides a separate development package or SDK, be sure it has
  been installed.
-- Configuring incomplete, errors occurred!
See also "/home/lbj/FastRTPS/work/HelloWorldExample/build/CMakeFiles/CMakeOutput.log".
```

then, i tried to delete these codes in CMakeLists.txt:

```
if(NOT fastcdr_FOUND)
    find_package(fastcdr REQUIRED)
endif()

if(NOT fastrtps_FOUND)
    find_package(fastrtps REQUIRED)
endif()

```
after that, the cmake worked well, but when i make , error occured again, who can tell what to do to fix this bug?

**Comment by raquelalvarezbanos** [comment]
Hi @gaoyadianta, can you let us know how you run cmake? Did you use -DTHIRDPARTY=ON?

**Comment by raquelalvarezbanos** [comment]
Closing this issue since there's been no response in a while. Feel free to reopen it if you still have trouble.

**Comment by simon0914** [comment]
Hey, I got the same error when trying to execute the command "cmake ..". I know this issue is closed for a while.
Is there any news on that issue?
Thanks a lot!

**Comment by JesusPoderoso** [comment]
Hi @simon0914, thanks for using Fast DDS.
Have you followed the [Fast DDS installation instructions](https://fast-dds.docs.eprosima.com/en/latest/installation/sources/sources_linux.html)? If that is the case, and you have already built Fast DDS, make sure you [source the environment](https://fast-dds.docs.eprosima.com/en/latest/installation/sources/sources_linux.html#run-an-application) before building the examples.

PD: the examples can be built together with the Fast DDS library using the CMake argument `COMPILE_EXAMPLES=ON`.

**Comment by simon0914** [comment]
Hi @JesusPoderoso, thank you for responding. Yes, I followed the instructions and built on macOS with colcon. I tried to source in any directory but apart from the /Fast-DDS/install/ it did not work. I always get the following error.
`User@MacBook-Pro ~ % source ~/Fast-DDS/install/setup.bash
not found: "/Users/User/local_setup.bash"`

I followed the instructions in the eProsima Video for the example https://www.youtube.com/watch?v=Vwo6fm9ZEJI

In the example in "CMakeLists.txt" I added following line, which worked, to cmake and make the example. Unfortunately writers and readers do not find each other after that.
`set(CMAKE_PREFIX_PATH "/Users/User/Fast-DDS/install")`

Building with the CMake argument with the Fast DDS library: Do you mean adding the argument in Step 3 from "5.1.4.1. Local installation"?

Thank you in advance

**Comment by JesusPoderoso** [comment]
Hi @simon0914, sorry for the inconvenience. 
I've checked that in MacOS the colcon setup utils need to be run in the same folder as it is. Try:
```bash
User@MacBook-Pro ~ % cd ~/Fast-DDS/install/
User@MacBook-Pro install % source setup.bash
```
If you are following CMake installation instead of colcon installation, then you need to include the Fast DDS install folder in the CMake prefix path

```bash
User@MacBook-Pro ~ % cd <my_application_path>
User@MacBook-Pro <my_application_path> % cmake <my_cmake_args...> -DCMAKE_PREFIX_PATH=~/Fast-DDS/install
```

> Do you mean adding the argument in Step 3 from "5.1.4.1. Local installation"?

Yes! The CMake flag is: `-DCOMPILE_EXAMPLES=ON` and this is the complete (modified) code snippet:
```bash
cd ~/Fast-DDS
git clone https://github.com/eProsima/Fast-DDS.git
mkdir Fast-DDS/build
cd Fast-DDS/build
cmake ..  -DCOMPILE_EXAMPLES=ON -DCMAKE_INSTALL_PREFIX=~/Fast-DDS/install -DCMAKE_PREFIX_PATH=~/Fast-DDS/install
sudo cmake --build . --target install
```
In case you are interested, [this is a complete list of the supported CMake options](https://fast-dds.docs.eprosima.com/en/latest/installation/configuration/cmake_options.html#).

**Comment by simon0914** [comment]
Hey @JesusPoderoso, sorry for late response.
Thanks for checking the installation guide. I installed again using the cmake way. It worked.
