### ISSUE TITLE
large files in the git repository

### ISSUE THREAD

**Issue by wjwwood** [eProsima/Fast-RTPS#52]
When pushing/cloning this repository I get a message like this:

```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File test/profiling/vgcore.17050 is 79.62 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
```

Not only does this slow down cloning your repository but it adds a lot of overhead to things like our build farm. Please consider removing this file to off-site (like amazon s3) and downloading it when needed or using git-lfs.

Thanks! 😄

**Comment by PabloMansanet** [comment]
Hello wjwood.

Thank you for making us know! That's a profiling file that got added by mistake, it's going out ASAP.

**Comment by richiprosima** [comment]
@wjwwood I was investigating how to remove this file from our repo history. I found this [page](https://help.github.com/articles/remove-sensitive-data/).  Did you use any of those methods? Are they secure?

**Comment by wjwwood** [comment]
I've used the filter branch command before, but not the repo cleaner. Since they're on a github page I'd trust them to work and be secure.

**Comment by wjwwood** [comment]
One thing you'll want to watch out for though is that it will rewrite your history. That might cause outstanding pull requests and branches to no longer merge and may somewhat disrupt people with existing checkouts from pulling. I don't know if there is a way to remove it without rewriting the history but I doubt there is.

**Comment by MiguelCompany** [comment]
This was solved long ago. Closing issue
