### ISSUE TITLE
Document required version of third party libraries [5688]

### ISSUE THREAD

**Issue by hansfn** [eProsima/Fast-RTPS#535]
Currently (it seems) you have to clone the source code and run `cmake ../ -DTHIRDPARTY=ON` to get any info about used versions of Tinyxml2 and Asio:

- Asio 1.12.2
- Tinyxml2 6.0.0

**It's unclear if these are the minimal required versions, and it would be nice to get this documented.**

My use case is installation on a Linux machine where Tinyxml2 and Asio is already installed on the system. Very specifically, I have created ebuilds for Fast-RTPS (and FAST-CDR) on Gentoo so our developers can easily install (and uninstall) Fast-RTPS using the normal package manager.

PS! It would also be nice to know which version of Fast CDR that is required. It seems HEAD is checked out in the submodule.

**Comment by laura-eprosima** [comment]
Hi @hansfn,

The minimal required versions are the following:

- Asio --> Apart from 1.12.2, we also support 1.10
- Tinyxml2 --> 6.0.0
- Fast CDR --> You can use any version

**Comment by hansfn** [comment]
With documenting, I was think about adding it to the readme. Anyway, thanks a lot for confirming. 

I'm closing since I'm not going to post a PR myself.
