### ISSUE TITLE
test UDPv6Tests fails on OS X

### ISSUE THREAD

**Issue by dirk-thomas** [eProsima/Fast-RTPS#55]
http://ci.ros2.org/job/ci_osx/1210/testReport/junit/projectroot.test.unittest/transport/UDPv6Tests/

**Comment by richiprosima** [comment]
@dirk-thomas I made same changes that I did to resolve UDPv4Tests on OSX. Can you check them in your CI? Whether it still fails, reopen this issue. Thanks.

**Comment by dirk-thomas** [comment]
The test still fails in the latest CI build: http://ci.ros2.org/job/ci_osx/1234/testReport/projectroot.test.unittest/transport/

I don't have the permission to reopen this ticket. So please reopen it.

**Comment by richiprosima** [comment]
Maybe it's not the same issue as UDPv4Test on OSX. I will check it thoroughly.

**Comment by dirk-thomas** [comment]
The test also has a compiler warning: see http://ci.ros2.org/view/nightly/job/nightly_osx_debug/143/warnings8Result/

**Comment by dirk-thomas** [comment]
Any update on this? It still had two compiler warnings and fails a test: http://ci.ros2.org/job/nightly_osx_debug/160/

**Comment by dirk-thomas** [comment]
@richiprosima Ping

**Comment by richiprosima** [comment]
According to this [link](http://stackoverflow.com/questions/23123817/boost-asio-ipv6-join-group-does-not-work-on-os-x) there is a problem using boost::asio::set_option() and multicast on OSX. Meantime I've disabled the test on OSX.
I've pushed the changes on branch [hotfix/55](https://github.com/eProsima/Fast-RTPS/tree/hotfix/55) to be tests in your CI server. 
If the changes work successfully, I will merge it in master branch.

**Comment by dirk-thomas** [comment]
I ran another build on OS X which doesn't have the test (failure) anymore: http://ci.ros2.org/job/ci_osx/1276/

So the branch can be merged as far as I can tell. Thanks.

**Comment by dirk-thomas** [comment]
@richiprosima Could you please also look into the remaining warnings: http://ci.ros2.org/job/ci_osx/1276/warnings9Result/ Those are the only ones keeping us from having a green build (at least sometimes :wink:).

**Comment by richiprosima** [comment]
I've updated branch hotfix/55, removing the warnings. As quick as you are agree with the changes, I will merge the branch in master.

**Comment by dirk-thomas** [comment]
The new OS X build (http://ci.ros2.org/job/ci_osx/1277/) looks good. +1 to merge this. Thank you.

**Comment by richiprosima** [comment]
Merged in master
