### ISSUE TITLE
fastrtpsgen doesn't compile due to end of Java 6 support [5665]

### ISSUE THREAD

**Issue by rooly4** [eProsima/Fast-RTPS#550]
Attempting to build Fast-RTPS v1.7.2 on Windows 10 in a CMD shell results in a build error during the `java` build target:

```
%1 not a valid Win32 application
```
The error seems related to a gradle compile failure

Commands used:

```
> set INSTDIR=%cd%/install
> cd Fast-RTPS-1.7.2
> mkdir build
> cd build
> cmake -DTHIRDPARTY=ON -DBUILD_JAVA=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=%INSTDIR% ..
> cmake --build . --target install
```

Environment used:
```
> echo %PATH%
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\;C:\Qt\5.12.3\msvc2017\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Java\java-se-8u40-ri\bin;C:\Program Files\CMake\bin;C:\Program Files\Git\cmd;C:\Program Files\7-Zip;C:\Gradle\gradle-5.4.1\bin;C:\MinGW\msys\1.0\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja

> echo %JAVA_HOME%
C:\Program Files\Java\java-se-8u40-ri

> gradle --version

------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_40 (Oracle Corporation 25.40-b25)
OS:           Windows 8.1 6.3 x86

> java -version
openjdk version "1.8.0_40"
OpenJDK Runtime Environment (build 1.8.0_40-b25)
OpenJDK Client VM (build 25.40-b25, mixed mode)
```

Fast-RTPS version used include 

- v1.8.0 tag 
- v1.7.2 tag

Java SE versions used include 
- Oracle 8u212 
- Oracle 12.0.1
- openJDK 1.8.0_40 (windows)

CMake generators used include 

- Visual Studio 15 2017 Win64
- Nmake makefiles
- Ninja
- Default (no -G)

**Comment by rooly4** [comment]
After further investigation, The `%1 is not a valid Win32 application` error is caused by the java target using

```
COMMAND cmake -E env --unset=JAVA_HOME PATH=...;%PATH% ${GRADLE_EXE} -Pcustomversion=... build
```

if I remove the `cmake -E env ...` portion of the command and just use `${GRADLE_EXE}` directly gradle begins to execute.

Now gradle fails with the error

```
error: Source option 6 is no longer supported. Use 7 or later
error: Target option 6 is no longer supported. Use 7 or later
```

using Oracle JDK 12.0.1

Will investigate upgrading source and target option in gradle

**Comment by rooly4** [comment]
The gradle build succeeds when I switch to the OpenJDK 1.8_40.

fastrtpsgen is incompatible with the current available download of Oracle JDK (12.0.1)

further, the BUILD_JAVA target fails on Windows systems with long system paths due to the shell-expansion that occurs in the java `add_custom_target` gradle build command

I'll generate a pull request to repair these issues

**Comment by breezZe** [comment]
I have the same problem with #555 ,which version of java should we use?

**Comment by breezZe** [comment]
@rooly4  I've change a little in fastrtpsgen.java.

Line number 525.
From
TemplateManager tmanager = new TemplateManager("FastCdrCommon:eprosima:Common");
To    
TemplateManager tmanager = new TemplateManager("FastCdrCommon:eprosima:Common",ctx,true);

Add the problem mentioned in #555 is solved.
JDK version: openjdk-8-jdk 1.8.0_212 (Installed by $sudo apt-get install openjdk-8-jdk)
Gradle version: gradle 5.4.1
