### ISSUE TITLE
iOS and Android support

### ISSUE THREAD

**Issue by ShawnSchaerer** [eProsima/Fast-RTPS#57]
has this library been tested on iOS and Android?

**Comment by JaimeMartin** [comment]
Hi Shawn,

Yes. It works on iOS and is used on this platform by some users. It has been ported to android (see https://github.com/eProsima/Fast-RTPS/pull/26) but we didn't have the time to review and incorporate this pull request yet.

**Comment by esteve** [comment]
@ShawnSchaerer FYI, I just announced that I ported ROS2 to iOS, which includes FastRTPS:

https://github.com/eProsima/Fast-RTPS/pull/26

https://discourse.ros.org/t/announcing-objective-c-on-macos-and-ios-for-ros2/946?u=esteve

**Comment by ShawnSchaerer** [comment]
@esteve great news.  I will check it out

**Comment by JavierIH** [comment]
We merged #26 so I'm closing this issue. Thank you!
