### ISSUE TITLE
Fail to receive messages completely at the high publishing rate [5762]

### ISSUE THREAD

**Issue by vinnamkim** [eProsima/Fast-RTPS#571]
Hi, I'm studying on this ROS2(rclcpp) issue https://github.com/ros2/rclcpp/issues/755. I found that this bug is not likely to be happened on the other DDS vendor(OpenSplice). So, I tried to reproduce this situation using FastRTPS's native API. The following codes are some modifications of FastRTPS example([HelloWorldExample](https://github.com/eProsima/Fast-RTPS/tree/master/examples/C%2B%2B/HelloWorldExample)).

First, I made `HelloWorldPublisher` to publish rapidly(100 microseconds).

```
void HelloWorldPublisher::runThread(uint32_t samples, uint32_t sleep)
{
    if (samples == 0)
    {
        while(!stop)
        {
            if(publish(false))
            {
                std::cout << "Message: "<<m_Hello.message()<< " with index: "<< m_Hello.index()<< " SENT"<<std::endl;
            }
            // eClock::my_sleep(sleep);
            usleep(100);
        }
    }
    else
    {
        for(uint32_t i = 0;i<samples;++i)
        {
            if(!publish())
                --i;
            else
            {
                std::cout << "Message: "<<m_Hello.message()<< " with index: "<< m_Hello.index()<< " SENT"<<std::endl;
            }
            //eClock::my_sleep(sleep);
            usleep(100);
        }
    }
}
```

Second, print out the number of received message and the index of the latest received message after `HelloWorldSubscriber::run()`.

```
void HelloWorldSubscriber::run()
{
    std::cout << "Subscriber running. Please press enter to stop the Subscriber" << std::endl;
    std::cin.ignore();
    std::cout << "Subscribed count : " << this->m_listener.n_samples <<std::endl;
    std::cout << "Subscribed latest index : "  << this->m_listener.m_Hello.index() << std::endl;
}
```

Also, I give enough QoS resources to both of them.

```
Rparam.topic.historyQos.depth = 5000;
Rparam.topic.resourceLimitsQos.max_samples = 10000;
Rparam.topic.resourceLimitsQos.allocated_samples = 5000;
```

Lastly, I run `HelloWorldPublisher` before `HelloWorldSubscriber`. 

Terminal 1
```
HelloWorldExample publisher 2000
```

Terminal 2

```
HelloWorldExample subscriber
```

Then, the output is following.

Terminal 1
```
...
Message: HelloWorld with index: 1998 SENT
Message: HelloWorld with index: 1999 SENT
Message: HelloWorld with index: 2000 SENT
```

Terminal 2
```
...
Message HelloWorld 254 RECEIVED
Message HelloWorld 255 RECEIVED
Message HelloWorld 256 RECEIVED
Subscriber unmatched
(Enter key pressed)
Subscribed count : 256
Subscribed latest index : 256
```

I guess the expected output should be `Subscribed latest index : 2000` although `Subscribed count < 2000`. Is this right?

**Comment by vinnamkim** [comment]
@clalancette In case of switching from "reliable" to "Best Effort" QoS,

HelloWorldPublisher.cpp
```
Wparam.qos.m_reliability.kind = BEST_EFFORT_RELIABILITY_QOS;
```
HelloWorldSubscriber.cpp
```
Rparam.qos.m_reliability.kind = BEST_EFFORT_RELIABILITY_QOS;
```

The output is following.

Terminal 1
```
...
Message: HelloWorld with index: 1998 SENT
Message: HelloWorld with index: 1999 SENT
Message: HelloWorld with index: 2000 SENT
```
Terminal 2
```
Message HelloWorld 1998 RECEIVED
Message HelloWorld 1999 RECEIVED
Message HelloWorld 2000 RECEIVED
Subscriber unmatched
(Enter key pressed)
Subscribed count : 1463
Subscribed latest index : 2000
```

**Comment by laura-eprosima** [comment]
Hi @vinnamkim,
That's because the publisher ends its execution before the subscriber receives all the samples since the publisher doesn't wait for them to be acknowledged.

This problem can be solved reducing the heartbeat period. For instance, you can use the following values:

```
Wparam.times.heartbeatPeriod.seconds = 0;
Wparam.times.heartbeatPeriod.nanosec = 1000*1000;
```

Or using the Publisher function `wait_for_all_acked()` after sending the samples, so that the publisher has to wait until all the samples are received and acknowledged by the subscriber. 

If you implement any of those two alternatives the output will be the following:

Publisher Terminal
```
...
Message: HelloWorld with index: 1996 SENT
Message: HelloWorld with index: 1997 SENT
Message: HelloWorld with index: 1998 SENT
Message: HelloWorld with index: 1999 SENT
Message: HelloWorld with index: 2000 SENT
```


Subscriber Terminal
```
...
Message HelloWorld 1996 RECEIVED
Message HelloWorld 1997 RECEIVED
Message HelloWorld 1998 RECEIVED
Message HelloWorld 1999 RECEIVED
Message HelloWorld 2000 RECEIVED
Subscriber unmatched

Subscriber count : 2000
Subscriber latest index : 2000
```

I hope this helps you.

**Comment by laura-eprosima** [comment]
As this was answered and no comments were received, we close the issue. Feel free to reopen it if the problem persists.
