### ISSUE TITLE
How do I implement filtering by keys in the RTPS layer [5758]

### ISSUE THREAD

**Issue by cvilas** [eProsima/Fast-RTPS#573]
I am using the RTPS layer directly for passing messages, and would like the ability to write/read multiple instances of a topic. I understand this is done using keys. Looking in the FastRTPS User Manual on how to implement the functionality, it does not go beyond saying that:

> The RTPS Layer requires you to call the getKey() method manually within your callbacks.

Well OK. Looking in the source code of some examples and tracing calls through RTPS library, it seems to me that `getKey()` essentially serialises the key into an `InstanceHandle_t`, which gets transmitted along with serialised data as part of `CacheChange_t` added by the RTPS writer into writer history. So I implemented something similar. I also set `endpoint.topicKind=WITH_KEY` for both reader and writer attributes, and `topicKind=WITH_KEY` for TopicAttributes. However, on the other end, while the `RTPSReader` receives the `CacheChange` with the serialised data correctly, the `instanceHandle` is always all zeros (all 16 bytes of them). 

So I am struggling a bit to understand where exactly the information in the `instanceHandle` is getting lost. (I believe it is not being written out by the RTPSWriter at all, and gets filtered out by `RTPSMessageCreator::addMessageData` or `RTPSMessageCreator::addSubmessageData`) 

The source code of my experiment is attached. Any advice on the preferred approach to transmitting keys is welcome. Once working, I would be more than happy to create a C++ example that demonstrates how to use keys for filtering and contribute it as a pull request.

[rtps_keys_exp.zip](https://github.com/eProsima/Fast-RTPS/files/3325470/rtps_keys_exp.zip)

**Comment by MiguelCompany** [comment]
Took a quick look to your code, and I think you just need to set `expectsInlineQos = true` on your `ReaderAttributes` before creating the reader. This way, when the writer finds the reader, it will know that the reader expects the `InstanceHandle_t` to be transmitted inside the DATA submessage.

**Comment by cvilas** [comment]
YeeHaw! @MiguelCompany you are a star!

That was totally unintuitive though. Had to look hard in the DDS Interoperability Protocol v2.2 to even know how `inlineQoS` flag affects transmission of keys

**Comment by cvilas** [comment]
Also, could you please confirm that ~filtering by key~ essentially involves receiving the `CacheChange` in the reader and discarding it if the `instanceHandle` does not match what I expect? I hope I am not missing some magic that could lead to better efficiency in bandwidth utilisation.

**Comment by MiguelCompany** [comment]
> Had to look hard in the DDS Interoperability Protocol v2.2 to even know that `inlineQoS` flag affects transmission of keys

You are using the RTPS layer, which is for expert users, so reading the standard is almost mandatory for some features.

Keys are described as part of the DDS data type and are thus part of the serialized payload of the `CacheChange`. What is transmitted inside the inlineQoS is a key hash. See sections 8.7.9 and 9.6.3.3 for more info. That may suit your needs, but in a generic case the key may have any length, so it may need to be computed/extracted from the data whenever received.

**Comment by MiguelCompany** [comment]
> Also, could you please confirm that filtering by key essentially involves receiving the `CacheChange` in the reader and discarding it if the `instanceHandle` does not match what I expect?

Yes, that is what it involves.

> I hope I am not missing some magic that could lead to better efficiency in bandwidth utilisation.

In the future we may add content filters, which will make the writer send GAP messages instead of DATA messages when it knows the reader does not need certain changes.

**Comment by cvilas** [comment]
closing, as I am happy with the approach suggested above.
