### ISSUE TITLE
need for automated testing with e.g. Travis and AppVeyor

### ISSUE THREAD

**Issue by dirk-thomas** [eProsima/Fast-RTPS#62]
This repository would benefit from running the tests on every commit and pull request on each supported platform. It happens frequently that new changes result in compiler warning and/or failing test. By adding automated builds using Travis (for Linux and OS X) and AppVeyor (for Windows) those could be either detected earlier (when committed directly) or even addressed before being merged (when using pull requests).

The latest examples are:
- http://ci.ros2.org/view/nightly/job/nightly_linux_debug/199/warnings20Result/new/
- http://ci.ros2.org/view/nightly/job/nightly_osx_debug/199/testReport/

**Comment by richiware** [comment]
We have an internal CI. In a few weeks we will make the access public. We will close the issue.

**Comment by richiware** [comment]
Finally we have a public IP for our [CI](http://jenkins.eprosima.com:8080).
