### ISSUE TITLE
Fast-RTPS no longer builds due to non-standard install location for dependency foonathan_memory [6117]

### ISSUE THREAD

**Issue by cvilas** [eProsima/Fast-RTPS#620]
Calling `make install` after building foonathan_memory as per README installs the library within the build directory itself, which seems to be the default install path. Therefore, when subsequently building FastRTPS, it is unable to find the corresponding cmake config files for foonathan_memory. I would expect that generating build files with `-DTHIRDPARTY=ON` would still work, just as it did with asio, tinyxml and Fast-CDR. But it doesn't. 

I don't want to set `CMAKE_INSTALL_PREFIX` when generating makefiles for foonathan_memory because I am not sure whether it is safe to do so. There must be a reason why the original author decided to change the default install path.

Ubuntu 18.04 host

**Comment by cvilas** [comment]
Installed foonathan_memory after setting `-DCMAKE_INSTALL_PREFIX=/usr/local`. Now building FastRTPS gives the following error:
````
.....
[ 97%] Building C object src/cpp/CMakeFiles/fastrtps.dir/rtps/persistence/sqlite3.c.o
[ 97%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/utils/TimedConditionVariable.cpp.o
[ 98%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/transport/TCPChannelResourceSecure.cpp.o
[ 99%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/transport/TCPAcceptorSecure.cpp.o
[100%] Linking CXX shared library libfastrtps.so
/usr/bin/ld: /usr/local/lib/libfoonathan_memory-0.6.1.a(free_list.cpp.o): relocation R_X86_64_PC32 against symbol `_ZN9foonathan6memory6detail13list_get_nextEPv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
src/cpp/CMakeFiles/fastrtps.dir/build.make:3557: recipe for target 'src/cpp/libfastrtps.so.1.9.0' failed
make[2]: *** [src/cpp/libfastrtps.so.1.9.0] Error 1
CMakeFiles/Makefile2:981: recipe for target 'src/cpp/CMakeFiles/fastrtps.dir/all' failed
make[1]: *** [src/cpp/CMakeFiles/fastrtps.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by kyrofa** [comment]
Doesn't build in ros2 either:

```
--- stderr: fastrtps
CMake Error at CMakeLists.txt:215 (find_package):
  By not providing "Findfoonathan_memory.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "foonathan_memory", but CMake did not find one.

  Could not find a package configuration file provided by "foonathan_memory"
  with any of the following names:

    foonathan_memoryConfig.cmake
    foonathan_memory-config.cmake

  Add the installation prefix of "foonathan_memory" to CMAKE_PREFIX_PATH or
  set "foonathan_memory_DIR" to a directory containing one of the above
  files.  If "foonathan_memory" provides a separate development package or
  SDK, be sure it has been installed.


make: *** [cmake_check_build_system] Error 1
---
```

**Comment by kyrofa** [comment]
31512910db8c029b6164457c3609c5e6c8f86506 seems to be the problematic commit. Using 31512910db8c029b6164457c3609c5e6c8f86506:

```
$ colcon build --symlink-install --packages-up-to fastrtps
Starting >>> fastcdr 
Finished <<< fastcdr [0.16s]                  
Starting >>> fastrtps
--- stderr: fastrtps                         
CMake Error at CMakeLists.txt:215 (find_package):
  By not providing "Findfoonathan_memory.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "foonathan_memory", but CMake did not find one.

  Could not find a package configuration file provided by "foonathan_memory"
  with any of the following names:

    foonathan_memoryConfig.cmake
    foonathan_memory-config.cmake

  Add the installation prefix of "foonathan_memory" to CMAKE_PREFIX_PATH or
  set "foonathan_memory_DIR" to a directory containing one of the above
  files.  If "foonathan_memory" provides a separate development package or
  SDK, be sure it has been installed.


make: *** [cmake_check_build_system] Error 1
---
Failed   <<< fastrtps	[ Exited with code 2 ]

Summary: 1 package finished [1.73s]
  1 package failed: fastrtps
  1 package had stderr output: fastrtps
```

Whereas, using 7c445d4e4ffd68ffc36c60e4327177db8a791af1 works:

```
$ colcon build --symlink-install --packages-up-to fastrtps
Starting >>> fastcdr 
Starting >>> osrf_testing_tools_cpp
Finished <<< fastcdr [0.18s]                                                                        
Finished <<< osrf_testing_tools_cpp [0.39s]                      
Starting >>> fastrtps
[Processing: fastrtps]                             
Finished <<< fastrtps [31.9s]                      

Summary: 3 packages finished [33.9s]
```

**Comment by hansfn** [comment]
I have filed an issue for foonathan_memory - foonathan/memory#48 - asking if the change of default installation directory is intended.

Until then the Fast-RTPS Readme has to be updated. Replace

```
cmake ..
```

with 

```
cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_SHARED_LIBS=ON ..
```

as already posted by cvilas.

@kyrofa: The reason it fails to build for 3151291 is that the foonathan_memory dependency was imported in that commit.

**Comment by richiware** [comment]
@cvilas Due to we were not able to integrate *foonatham_memory* as a Git submodule, new version of FastRTPS doesn't support `-DTHIRDPARTY`.
Thinking in the integration in ROS2, we created a vendor package [foonatham_memory_vendor](https://github.com/eProsima/foonathan_memory_vendor). Maybe using this package to install *foonatham_memory* instead of using directly *foonathan_memory* repository will help you. This package installs *foonatham_memory* in `CMAKE_INSTALL_PREFIX`.

Even though FastRTPS and its dependencies can be compiled and installed manually, we recommend to use *colcon* to install Fast-RTPS using this [repos file](https://raw.githubusercontent.com/eProsima/Fast-RTPS/master/fastrtps.repos).

**Comment by cvilas** [comment]
Thanks @richiware. I think I will accept solution in https://github.com/eProsima/Fast-RTPS/issues/620#issuecomment-519058586 for now. Our source tree is ROS independent, and runs on a variety of targets. I am not sure yet whether I want to introduce _colcon_ as a means to build the sources. The bigger problem for us not being able to cross-compile for Android (similar to problem described in https://github.com/eProsima/Fast-RTPS/issues/666)

**Comment by richiware** [comment]
#675 updates the README to recommend the installation of _foonathan_memory_ using our vendor package.

```bash
    $ git clone https://github.com/eProsima/foonathan_memory_vendor.git
    $ cd foonathan_memory_vendor
    $ mkdir build && cd build
    $ cmake ..
    $ cmake --build . --target install
```
