### ISSUE TITLE
Performance issues with lookupReaderProxyData and lookupWriterProxyData [6116]

### ISSUE THREAD

**Issue by guillaumeautran** [eProsima/Fast-RTPS#636]
Looking up a reader or writer proxy structure is very computational expensive in both the PDP and EDP code. 
https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/rtps/builtin/discovery/participant/PDP.cpp#L478-L496
https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/rtps/builtin/discovery/participant/PDP.cpp#L517-L535

As well as a few other places. 
The runtime complexity is at in the worst case: O(p^e) with p=#participant and e=#endpoint per participant. On large distributed system, this can be come a significant bottleneck. 

To reproduce the issue, simple create a subscriber (or subscribers) with a very large number (50,000+) of publisher endpoint with reliable QoS. The creation of this number of endpoints takes time but is it not too bad. Then, once these endpoints are created, destroy them one at a time in a loop. As the deletion of those endpoint happens, the gross inefficiency of the code really takes its toll. Having a good profiler to visualize the time taken (such as vtune) will pinpoint the performance problem to the GUID comparison. Although this takes time, it is simply because the lookup method end up comparing every single guid with every single other guid in the lookup.

**Comment by MiguelCompany** [comment]
This was fixed by #772
