### ISSUE TITLE
configure TTL for RTPS packages

### ISSUE THREAD

**Issue by Karsten1987** [eProsima/Fast-RTPS#64]
Would it make sense to make the TTL of the RTPS packages configurable? We've seen that sending big data via unicast or multicast can basically block the complete network even if all publisher/subscriber are executed on the same computer.

This could be prevented by setting the TTL of each RTPS package to 0. Regardless of multicast/unicast, the packages would not leave the machine, doesn't affect the network and all communication happens exclusively locally.

**Comment by wjwwood** [comment]
Just as a note, I do not believe (based on what I can find on the Internet) that the mechanism used in #65 (i.e. `IPPROTO_IP`/`IP_MULTICAST_TTL` via `ip::multicast::hops`) will affect unicast at all, only multicast. I think this is the desired behavior, but I thought I'd point it out.

**Comment by JavierIH** [comment]
Hi, the PR associated was merged. I have been testing the changes and it works as expected so I think we can close this issue. Thank you for the contribution.
