### ISSUE TITLE
Fast-RTPS 1.8.1 build fails with BUILD_JAVA=ON

### ISSUE THREAD

**Issue by TSC21** [eProsima/Fast-RTPS#641]
**System:** Ubuntu 18.04, with Java `11.0.2+9-Ubuntu-3ubuntu118.04.3` and Gradle 5.5-rc-3.

**Problem:** Fast-RTPS release 1.8.1 fails building with `-DBUILD_JAVA=ON`:

```sh
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> Task :copyResources UP-TO-DATE
> Task :processResources
> Task :idl:clean UP-TO-DATE

> Task :idl:generateGrammarSource FAILED
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
error(7):  cannot find or open file: ../antlr4/omg/com/eprosima/idl/parser/grammar/IDL.g4

> Task :buildIDLParser FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':idl:generateGrammarSource'.
> There was 1 error during grammar generation

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by MiguelCompany** [comment]
This was already informed on #583 and was fixed on #586

**Comment by TSC21** [comment]
@MiguelCompany alright sorry for the duplicate. What I don't understand is why is this scheduled for a 1.9.0 release when this is a bug in a previous release (not even in upstream code). IMHO this should be applied as an hotfix to 1.8.0, or we risk always having to update the FastRTPS versions so to fix release bugs.

**Comment by MiguelCompany** [comment]
@TSC21 You're right. We are backporting some fixes to branch 1.8.x, and will also backport #586 on it

**Comment by MiguelCompany** [comment]
Commit cfaf5307dae3ab94e6ff929f7507779585895691 should fix this issue.

**Comment by TSC21** [comment]
@MiguelCompany how and when are you planning to sync the release branches with that `1.8.x` branch?

**Comment by LuisGP** [comment]
FastRTPSGen is now an independent project and both master branches should work. 
I'm closing this due to deprecation, please, feel free to reopen it again if you have more issues.
