### ISSUE TITLE
Waiting for acknowledgement from all readers

### ISSUE THREAD

**Issue by cvilas** [eProsima/Fast-RTPS#644]
Reference:
https://github.com/eProsima/Fast-RTPS/blob/94034320b21d844ffa3685e8a68d36a63e904235/include/fastrtps/rtps/writer/RTPSWriter.h#L122

At the moment, `RTPSWriter::wait_for_all_acked` just returns `true` (i.e., all readers acknowledged). Is there a plan for this feature to be implemented correctly? If not, is there an alternative workaround, say for instance, by querying participants?

**Comment by MiguelCompany** [comment]
The method is virtual and is currently implemented on StatefulWriter which is the one knowing if the readers have acknowledged the changes or not:

https://github.com/eProsima/Fast-RTPS/blob/94034320b21d844ffa3685e8a68d36a63e904235/src/cpp/rtps/writer/StatefulWriter.cpp#L876-L895

**Comment by cvilas** [comment]
OK, I feel stupid now. Thanks for pointing it out @MiguelCompany
