### ISSUE TITLE
fastrtpsgen generated examples won't compile [6212]

### ISSUE THREAD

**Issue by mathias110** [eProsima/Fast-RTPS#663]
In the generated example files has the  line

PParam.rtps.builtin.leaseDuration  = c_TimeInfinite;

should be changed to 

PParam.rtps.builtin.discovery_config.leaseDuration = c_TimeInfinite;

**Comment by richiware** [comment]
We've started to separate the generator Java application from the main repository. Try to use the Java application hosted in this [repository](https://github.com/eProsima/Fast-RTPS-Gen). It contains the fix to your issue.

**Comment by richiware** [comment]
@mathias110 Does it work for you?

**Comment by mathias110** [comment]
I haven't tried it yet due to other more urgent tasks.

**Comment by LuisGP** [comment]
I'm closing this because it should be fixed now. Please, feel free to reopen it again if you found that the issue persists.
