### ISSUE TITLE
'(': illegal token on right side of '::' FastRTPS 1.8.1 Windows [6214]

### ISSUE THREAD

**Issue by ghostravenstorm** [eProsima/Fast-RTPS#665]
I'm building a DDS LIbrary wrapper fro FastRTPS, and Visual Studio is complaining about `'(': illegal token on right side of '::'` in `ResouceLimitedVector.hpp` in every instance `std::min(` is used.

**Comment by LuisGP** [comment]
Hi @ghostravenstorm 

Microsoft has the bad habit to define `min` (and `max`) as macros in `Windef.h` (probably included through `Windows.h`).

You should be able to avoid the collision by defining the macro `NOMINMAX`.
