### ISSUE TITLE
[fastrtpsgen] ERROR: Getting platforms. null [6218]

### ISSUE THREAD

**Issue by PeripateticWind** [eProsima/Fast-RTPS#669]
The following error occurred when I'm trying to use fastrtpsgen:

```
~$ fastrtpsgen 
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
ERROR: Getting platforms. null
```

 I can not find the  recommended version for fastRTPS and installed java8
**The JAVA version details is:**

```
~$ java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```
**The gradle version details is:**
```
~$ gradle -v

------------------------------------------------------------
Gradle 5.0
------------------------------------------------------------

Build time:   2018-11-26 11:48:43 UTC
Revision:     7fc6e5abf2fc5fe0824aec8a0f5462664dbcd987

Kotlin DSL:   1.0.4
Kotlin:       1.3.10
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Linux 4.15.0-55-generic amd64
```
**The environment I'm using is shown below:**
OS: Linux(Ubuntu16.04)
FastRTPS: building from source.
Version : master branch
JAVA : Oracle JAVA 8 JDK

**Some details:**
I followed [FastRTPS INSTALLATION MANUAL](https://eprosima-fast-rtps.readthedocs.io/en/latest/sources.html) and adding -DBUILD_JAVA=ON  -DCOMPILE_EXAMPLES=ON -DPERFORMANCE_TESTS=ON -DSECURITY=ON
I created a .idl file after installation of the FastRTPS as follows:
```
struct HelloWorld
{
    string msg;
};
```
and then run
` fastrtpsgen -example CMake HelloWorld.idl.`
then the error occurred as follows:
```
$ fastrtpsgen -example CMake HelloWorld.idl 
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
ERROR: Getting platforms. null
```

What's the problem? Thank you!

**Comment by salerio-gs** [comment]
See also https://github.com/eProsima/Fast-RTPS/issues/672 which was opened in error (more of less the same problem I think).

**Comment by LuisGP** [comment]
Closing due to duplicate #672.
