### ISSUE TITLE
Boost 1.58 from Ubuntu Xenial seems to work

### ISSUE THREAD

**Issue by mcharleb** [eProsima/Fast-RTPS#67]
It seems to build OK with the system boost libraries from Xenial. You just need the following:
libboost-dev
libboost-atomic-dev
libboost-regex-dev
libboost-chrono-dev
libboost-thread-dev
libboost-date-time-dev

and gtest:
libgtest-dev

**Comment by JavierIH** [comment]
Hi, since 4666e34d0f04267e58ff4f13e1b0a356741a3b70 Fast RTPS doesn't require Boost libraries anymore.
