### ISSUE TITLE
IDL module is listed twice in .gitmodules [6219]

### ISSUE THREAD

**Issue by PIXEVIA** [eProsima/Fast-RTPS#670]
IDL module is listed twice in file .gitmodules
[submodule "thirdparty/idl"]
...
[submodule "thirdparty/idl"]
...

CentOS (centos-release-7-6.) with git 1.8 produces an error -> 
error: invalid key (newline): submodule.thirdparty/idl

**Comment by LuisGP** [comment]
Hi @PIXEVIA 
This issue should be solved by PR #677.
Could you test it?

**Comment by LuisGP** [comment]
Closing because #677 removes the submodule.
