### ISSUE TITLE
Project fails to build (3rd party error) when downloaded vs cloned. [6223]

### ISSUE THREAD

**Issue by SumolX** [eProsima/Fast-RTPS#674]
Unable to build Fast-RTPS when downloading the project as a zip archive vs cloning the project via GIT.

-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring Fast RTPS
-- Version: 1.9.0
-- To change the version modify the file configure.ac
-- Performing Test SUPPORTS_CXX14
-- Performing Test SUPPORTS_CXX14 - Success
-- Performing Test SUPPORTS_CXX1Y
-- Performing Test SUPPORTS_CXX1Y - Success
-- Performing Test SUPPORTS_CXX11
-- Performing Test SUPPORTS_CXX11 - Success
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- fastcdr library found...
fatal: not a git repository (or any of the parent directories): .git
CMake Error at cmake/common/eprosima_libraries.cmake:90 (message):
  Cannot configure Git submodule Asio
Call Stack (most recent call first):
  CMakeLists.txt:213 (eprosima_find_thirdparty)

-- Configuring incomplete, errors occurred!

**Comment by LuisGP** [comment]
Hi @SumolX 

Seems that we broke the usage of the thirdparties in the downloaded version.

The problem is that the `.git` directory of FastRTPS is missing, so isn't recognized as a git repository.

We are migrating to the colcon build system, you can follow the guide to build FastRTPS with it in the [FastRTPS's readme](https://github.com/eProsima/Fast-RTPS#colcon-installation).
Building with colcon needs to have Asio installed in the system.

Probably you can work around the problem if you re-create the FastRTPS git repository locally and then build again.

**Comment by shynur** [comment]
This should be mentioned in <https://fast-dds.docs.eprosima.com/en/stable/notes/versions.html#library-dependencies>.
