### ISSUE TITLE
fastrtpsgen: no viable alternative at input [6279]

### ISSUE THREAD

**Issue by TSC21** [eProsima/Fast-RTPS#690]
Fast-RTPS version 1.8.1 (compiled from branch 1.8.x)

**Description:**
Trying to run `/fastrtpsgen -example x64Linux2.6gcc` over the following IDL file:

```
// generated from rosidl_adapter/resource/msg.idl.em
// with input from px4_msgs/msg/QshellRetval.msg
// generated code does not contain a copyright notice


module px4_msgs {
  module msg {
    struct QshellRetval {
      @verbatim (language="comment", text=" time since system start (microseconds)")
      uint64 timestamp;

      int32 return_value;

      uint32 sequence;
    };
  };
};
```

Results in:
```sh
/home/nuno/PX4/px4_ros_com_ros2/install/px4_msgs/share/px4_msgs/msg/QshellRetval.idl:14:13: error: no viable alternative at input 'sequence'
Exception in thread "main" java.lang.NullPointerException
	at com.eprosima.fastrtps.fastrtpsgen.execute(fastrtpsgen.java:323)
	at com.eprosima.fastrtps.fastrtpsgen.main(fastrtpsgen.java:1188)
```

Any idea on what may be causing this? Thank you!

**Comment by TSC21** [comment]
@richiware any inputs are welcomed. Thank you!

**Comment by TSC21** [comment]
Note that the same happens with 1.9.0.

**Comment by LuisGP** [comment]
Hi @TSC21,
since some time ago, we implemented the variable name restrictions following the standard, so as the member `sequence` is a reserved word, FastRTPSGen fails to parse the file.
Here you have two alternatives:
- Rename the variable to avoid the collision.
- Add the prefix "_" to the variable name, that it is used to ignore such restriction: `uint32 _sequence;`

Hope this helps.

**Comment by TSC21** [comment]
> Hi @TSC21,
> since some time ago, we implemented the variable name restrictions following the standard, so as the member `sequence` is a reserved word, FastRTPSGen fails to parse the file.
> Here you have two alternatives:
> 
> * Rename the variable to avoid the collision.
> * Add the prefix "_" to the variable name, that it is used to ignore such restriction: `uint32 _sequence;`
> 
> Hope this helps.

Oh I see. Well since I can't add the prefix to the variable name, I have to find a way of rename it. I will test it and check how it goes. Thanks @LuisGP!

**Comment by LuisGP** [comment]
> > Hi @TSC21,
> > since some time ago, we implemented the variable name restrictions following the standard, so as the member `sequence` is a reserved word, FastRTPSGen fails to parse the file.
> > Here you have two alternatives:
> > 
> > * Rename the variable to avoid the collision.
> > * Add the prefix "_" to the variable name, that it is used to ignore such restriction: `uint32 _sequence;`
> > 
> > Hope this helps.
> 
> Oh I see. Well since I can't add the prefix to the variable name, I have to find a way of rename it. I will test it and check how it goes. Thanks @LuisGP!

Take into account that the prefix is ignored in term of generated code, so your application code will be unaffected. 

If you need more help, don't hesitate to contact with us.

Best regards.

**Comment by TSC21** [comment]
@LuisGP changing the naming helped. Thank you!

**Comment by TSC21** [comment]
@LuisGP closing this as solved. Thank you for your assistance!

**Comment by TSC21** [comment]
@LuisGP one thing that I see happening is that `FastRTPSGen` doesn't handle very well line breaks in comments. For example:
```
# Optical flow in XYZ body frame in SI units.
# Check http://en.wikipedia.org/wiki/International_System_of_Units
```

Which results in:
```c++
    @verbatim (language="comment", text=" Optical flow in XYZ body frame in SI units.
 Check http://en.wikipedia.org/wiki/International_System_of_Units")
```

Which turns into an error in the parser:
```sh
/home/nuno/PX4/px4_ros_com_ros2/install/px4_msgs/share/px4_msgs/msg/OpticalFlow.idl:8:41: warning: missing terminating " character
     @verbatim (language="comment", text=" Optical flow in XYZ body frame in SI units.
                                         ^
/home/nuno/PX4/px4_ros_com_ros2/install/px4_msgs/share/px4_msgs/msg/OpticalFlow.idl:11:27: error: mismatched input 'comment' expecting {',', ')', '/', '*', '+', '-', '^', '&', '|', '%', '>>', '<<'}
/home/nuno/PX4/px4_ros_com_ros2/install/px4_msgs/share/px4_msgs/msg/OpticalFlow.idl:11:82: error: no viable alternative at input '")\n      uint64 timestamp;\n\n      @verbatim (language="'
```

Is this something we should predict on the message file so to be defined correctly on the IDL or is this a bug on the `FastRTPSGen` parser and it needs to be fixed? Should I bring this to a new issue then? Thanks!

**Comment by TSC21** [comment]
@LuisGP I brought this into https://github.com/eProsima/Fast-RTPS/issues/693 so we don't mix issues.

**Comment by LuisGP** [comment]
Hi @TSC21,

I'm afraid I cannot test it by myself in a while, probably until next week, but we are pretty sure the generated IDL is wrong. In this case, a backslash should be placed to prevent the split of the string.

        @verbatim (language="comment", text=" Optical flow in XYZ body frame in SI units.\
     Check http://en.wikipedia.org/wiki/International_System_of_Units")

Another solution could be to generate two annotations, one per line, instead of just one annotation.

    @verbatim (language="comment", text=" Optical flow in XYZ body frame in SI units.")
    @verbatim (language="comment", text=" Check http://en.wikipedia.org/wiki/International_System_of_Units")

Both alternatives should work. If not, please open the issue in the [IDL-Parser](https://github.com/eProsima/IDL-Parser) project.

**Comment by TSC21** [comment]
@LuisGP then generated IDL comes from `rosidl_adapter/resource/msg.idl.em`. So this is ROS2 `rosidl_adapter` taking care of it.

**Comment by TSC21** [comment]
@LuisGP adding `\` does solve the issue. But then I guess that's a problem to solve in `rosidl_adapter`.
