### ISSUE TITLE
Unnamed mutex lock released early [6292]

### ISSUE THREAD

**Issue by DavidLoftus** [eProsima/Fast-RTPS#697]
The code [here](https://github.com/eProsima/Fast-RTPS/blob/84e6cc6aabd4b4102c1967eba0d58a833aa307ae/src/cpp/security/cryptography/AESGCMGMAC_KeyFactory.cpp#L375) acquires a lock and immediately releases it since it is not named.
According to git blame that line has been there for over 3 years, is this somehow intentional?

**Comment by LuisGP** [comment]
Hi @DavidLoftus 
Isn't intentional, nice catch!
A PR in your honor is on the way.
