### ISSUE TITLE
failing test on Windows

### ISSUE THREAD

**Issue by dirk-thomas** [eProsima/Fast-RTPS#70]
Since the most recent commit d4d647424f86b0a74303adede0df6d711f6e51e3 one of the tests is failing on Windows: http://ci.ros2.org/view/nightly/job/nightly_win_rel/290/testReport/junit/projectroot.test/communication/

**Comment by JavierIH** [comment]
We have found the bug and now it is fixed on master branch. Thank you for the feedback.

**Comment by dirk-thomas** [comment]
The latest Windows build looks good: http://ci.ros2.org/job/nightly_win_rel/311/testReport/projectroot.test/communication/SimpleCommunication/ Thank you for the fix.

I suggest looking into setting up AppVeyor which is a free service like Travis but for Windows. Both enable to build and run all tests on every commit / pull request to catch such regressions.
