### ISSUE TITLE
ERROR: Fastrtpsgen illegal identifier: id is already defined, value is already defined.

### ISSUE THREAD

**Issue by adrianfime27** [eProsima/Fast-RTPS#704]
To generate the structure with fastrtpsgen.
Loading templates...
Processing the file dato.idl...
dato.idl:12:13: error: Illegal identifier: id is already defined (Annotation: id)
dato.idl:13:15: error: Illegal identifier: value is already defined (Annotation: value)
Exception in thread "main" java.lang.NullPointerException
	at com.eprosima.fastrtps.fastrtpsgen.execute(fastrtpsgen.java:336)
	at com.eprosima.fastrtps.fastrtpsgen.main(fastrtpsgen.java:1200)

**Comment by adrianfime27** [comment]
This is the file .idl

**struct** dato{
**@key long** key_value;
**string** id;
**float** value;
**boolean** state;
};

**Comment by LuisGP** [comment]
This is the same case that IDL-Parser issue [#34](https://github.com/eProsima/IDL-Parser/issues/34)
