### ISSUE TITLE
KEEP_LAST history not respected [6329]

### ISSUE THREAD

**Issue by eboasson** [eProsima/Fast-RTPS#708]
If a KEEP_LAST reader history is full and a sample arrives from a "new" writer (one from which there are no older samples present in the history), it will be rejected and retried until room is available. The correct behaviour is to drop the oldest sample from the history and store the new one.

See https://github.com/ros2/geometry2/pull/160 for background information and a test case.

**Comment by MiguelCompany** [comment]
@eboasson thanks for the hint. A fix is on the way on #712
