### ISSUE TITLE
CMake Minimum Version is wrong when building Java component

### ISSUE THREAD

**Issue by dljsjr** [eProsima/Fast-RTPS#72]
If `-DBUILD_JAVA=ON` is set during a build, the generated makefiles for the Java application use `cmake -E env`. The `env` subcommand was introduced in CMake 3.1

The primary CMakeLists.txt still targets CMake 2.8.12.

**Comment by richiware** [comment]
Now depending on CMake version the command is used or not. Thanks for the reporting.
