### ISSUE TITLE
executable doesn't always start right ahead

### ISSUE THREAD

**Issue by Karsten1987** [eProsima/Fast-RTPS#73]
I encountered the following error message a couple of times and I wondered if I am doing something wrong with it. I'll get this message, but once I restarted the application, it works just fine. Is there any time constraint between stopping and restarting an application?

```
listener: /home/karsten/workspace/osrf/ros2_src/src/eProsima/Fast-RTPS/src/cpp/rtps/reader/WriterProxy.cpp:281: bool eprosima::fastrtps::rtps::WriterProxy::received_change_set(const eprosima::fastrtps::rtps::SequenceNumber_t&, bool): Assertion `chit->getStatus() == UNKNOWN || chit->getStatus() == MISSING' failed.
```

**Comment by richiprosima** [comment]
It is a wrong assertion. It was solved in commit @b323d710929f94b4b8ea30722196d7823e3ba9e0. Thanks
