### ISSUE TITLE
Unbounded sequence limited to 100 elements

### ISSUE THREAD

**Issue by jespersmith** [eProsima/Fast-RTPS#74]
When using fastrtpsgen to create a message from the included IDL, the sequence elements are limited to 100 elements. To my understanding they should be unbounded.

```
module sensor_msgs{
    struct Time{
        long sec;
        unsigned long nanosec;
    };

    struct Header{
        Time stamp;
        string frame_id;
    };

    struct LaserScan{
        Header header;
        float angle_min;
        float angle_max;
        float angle_increment;
        float time_increment;
        float scan_time;
        float range_min;
        float range_max;

        sequence<float> ranges;
        sequence<float> intensities;
    };
};
```

results in the following serialize method

```
void sensor_msgs::LaserScan::serialize(eprosima::fastcdr::Cdr &scdr) const
{
    scdr << m_header;

    scdr << m_angle_min;

    scdr << m_angle_max;

    scdr << m_angle_increment;

    scdr << m_time_increment;

    scdr << m_scan_time;

    scdr << m_range_min;

    scdr << m_range_max;

    if(m_ranges.size() <= 100)
    scdr << m_ranges;
    else
        throw eprosima::fastcdr::exception::BadParamException("ranges field exceeds the maximum length");
    if(m_intensities.size() <= 100)
    scdr << m_intensities;
    else
        throw eprosima::fastcdr::exception::BadParamException("intensities field exceeds the maximum length");
}
```

**Comment by richiprosima** [comment]
Originally Fast RTPS used a preallocated memory policy. Buffers were allocated at the beginning with a fixed size. For this reason data types had a maximum serialized size known at the beginning of the execution.

IDL supports variable data types as `sequence`. A default maximum serialized size had to be set. In case of `sequence` was `100`. `fastrtpsgen` generates code with these preconditions. There are currently two ways to solve this:

* Increase the maximum of the `sequence`in the IDL file: `sequence<float, 1000> ranges`
* Currently Fast RTPS supports three memory polices: `PREALLOCATED_MEMORY_MODE`, `PREALLOCATED_WITH_REALLOC_MEMORY_MODE` and `DYNAMIC_RESERVE_MEMORY_MODE`. The last two ones don't need a maximum serialized size. You can use them configuring `SubscriberAttributes` and `PublisherAttributes`. But `fastrtpsgen` generates code with the restrictions. Till we change the generator to support dynamic allocation,  you have to remove the conditions in the generated code.

**Comment by richiware** [comment]
eProsima/Fast-CDR@affa48d511a36351ef24d40029db1e8217be86b1 removes the limitation. I will close this issue
