### ISSUE TITLE
with multiple subscribers and certain data size, missing a few messages to deliver for subscribers. [6490]

### ISSUE THREAD

**Issue by fujitatomoya** [eProsima/Fast-RTPS#747]
we detected this issue with 8MB data size and 16 subscribers at the same time via ROS2 APIs.

# Environment

## OS Distribution

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04

## Hardware Information
Architecture:        x86_64
CPU(s):              8
Vendor ID:           GenuineIntel
Model name:          Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz

# Reproduction Procedure

## Test Program
[demo_test_fastrtps.tar.gz](https://github.com/eProsima/Fast-RTPS/files/3669417/demo_test_fastrtps.tar.gz)

## Procedure to Build

```
ROS2 Dashing distribution (source code)	
$ mkdir -p ros2_src/src
$ cd ros2_src
$ git clone -b dashing https://github.com/ros2/ros2.git
$ vcs import src < ros2/ros2.repos

test code 'demo_test' refer to ROS2 'demo_nodes_cpp' talker/listener
$ cd ..
$ mkdir -p rmw_test/src
$ cd rmw_test/src
$ tar xvf demo_test.tar.gz
	
$ cd ../../rmw_test
$ MAKEFLAGS=-j2 colcon build --merge-install --cmake-args -DCMAKE_BUILD_TYPE=Debug
```

## Procedure to Run

```
Running 'demo_test' and watching the first communication log, some listeners maybe miss log
# test script src/demo_test/demo_test.sh
(Note that there are 30% reproduce rate to reproduce this bug)
	
As below, one talker and 16 listeners, but there are 14 listeners' log in the first communication.
	
$ source ../ros2_src/install/local_setup.sh
$ source install/local_setup.sh
$ ./src/demo_test/demo_test.sh
[INFO] [talker]: Publishing: '1'
[INFO] [listener]: I heard: [1]
[INFO] [listener]: I heard: [1]
[INFO] [listener]: I heard: [1]
[INFO] [listener]: I heard: [1]
[INFO] [listener]: I heard: [1]
[INFO] [listener]: I heard: [1]
[INFO] [listener]: I heard: [1]
[INFO] [listener]: I heard: [1]
[INFO] [listener]: I heard: [1]
[INFO] [listener]: I heard: [1]
[INFO] [listener]: I heard: [1]
[INFO] [listener]: I heard: [1]
[INFO] [listener]: I heard: [1]
[INFO] [listener]: I heard: [1]
[INFO] [talker]: Publishing: '2'
[INFO] [listener]: I heard: [2]
[INFO] [listener]: I heard: [2]
[INFO] [listener]: I heard: [2]
[INFO] [listener]: I heard: [2]
[INFO] [listener]: I heard: [2]
[INFO] [listener]: I heard: [2]
[INFO] [listener]: I heard: [2]
[INFO] [listener]: I heard: [2]
[INFO] [listener]: I heard: [2]
[INFO] [listener]: I heard: [2]
[INFO] [listener]: I heard: [1]
[INFO] [listener]: I heard: [2]
[INFO] [listener]: I heard: [2]
[INFO] [listener]: I heard: [2]
[INFO] [listener]: I heard: [2]
[INFO] [listener]: I heard: [1]
...
```

**Comment by MiguelCompany** [comment]
Hi @fujitatomoya 

It seems your example is using the default QoS settings for ROS2 topics, which means having a durability kind of VOLATILE. In this case, the talker will discard the message when all the listeners it is aware of acknowledge the message. So it may be the case that it didn't discover all the listeners and so the first sample is discarded. Changing the qos to TRANSIENT_LOCAL should fix this. Another possibility is to wait until the subscription count gets to the expected value before starting publishing data.

**Comment by fujitatomoya** [comment]
the following part concerns me,

https://github.com/eProsima/Fast-RTPS/blob/9d562024886f4e1e7be363356ab032ecba934490/src/cpp/rtps/writer/StatefulWriter.cpp#L910-L913

it looks that it tries to get lowest mark number, but if last loop(last reader proxy) only receives minimum mark number, it will be not minimum value at all. lowest mark number is used to control if the all of the readers have received fragment data.

**Comment by fujitatomoya** [comment]
@MiguelCompany 

> Changing the qos to TRANSIENT_LOCAL should fix this. 

of course, using TRANSIENT_LOCAL can not reproduce this issue since HistoryCache will not be removed. but still https://github.com/eProsima/Fast-RTPS/issues/747#issuecomment-536466846 could be a problematic code.

**Comment by MiguelCompany** [comment]
@fujitatomoya The only problem would arise if we get into `check_acked_status` between the matching of a new reader and the reception of an acknack. This method is called on three places:

1. When receiving an acknack
2. When removing a matched reader
3. After asynchronously sending data

I will perform a deeper investigation to check how problematic the code could be.
