### ISSUE TITLE
Update PublisherAttributes

### ISSUE THREAD

**Issue by Karsten1987** [eProsima/Fast-RTPS#75]
I've seen this API does not longer publically exist. Is there any alternative way for it?

https://github.com/eProsima/Fast-RTPS/blob/24825bb0de6cc5fdf16949a350c40570f2b00f26/utils/outdatedTests/UpdateAttributesTest/main_UpdateAttributes.cpp#L128

**Comment by spiderkeys** [comment]
Still seems to be a public method here:

https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/publisher/PublisherImpl.h#L115

**Comment by Karsten1987** [comment]
AFAIK, it's in the implementation part, not accessible from the actual public API.

**Comment by spiderkeys** [comment]
Ah yea, my bad. Does seem to be missing in the includes/publisher header. Does seem like there is no way to modify them in the current API, post-creation.

**Comment by MiguelCompany** [comment]
This should have been fixed by #326
