### ISSUE TITLE
Unregister Type is not unregistering my type [6531]

### ISSUE THREAD

**Issue by ghostravenstorm** [eProsima/Fast-RTPS#761]
What exactly is Domain::unregisterType supposed to do? I get it "unregisters" a given type via name, but what does that mean? When I try to register it again in the same program, I get this error:
> [PARTICIPANT Error] Type with the same name already exists:MyType -> Function eprosima::fastrtps::ParticipantImpl::registerType

**Comment by ghostravenstorm** [comment]
Does `Domain::getRegisteredType` not do anything either?

```
isRegistered = eprosima::fastrtps::Domain::getRegisteredType(part, topicName.c_str(), (eprosima::fastrtps::TopicDataType**) type);

   if (isRegistered) {
      std::cout << topicName << " is already registered." << std::endl;
   } else {
      std::cout << topicName << " is not registered." << std::endl;
   }
```

Output:
```
/// First time registering then unregistering MyType
MyType is not registered.
MyType initialized.
MyType decommissioned.

/// Second time registering then unregistering MyType
Assessment is not registered.
Could not initialize Assessment.
[PARTICIPANT Error] Type with the same name already exists:MyType -> Function eprosima::fastrtps::ParticipantImpl::registerType
```

**Comment by ghostravenstorm** [comment]
```
   eprosima::fastrtps::ParticipantAttributes pa;
   pa.rtps.builtin.domainId = (uint32_t) 14;
   pa.rtps.setName("Test Module");

   auto* p = eprosima::fastrtps::Domain::createParticipant(pa);
   if (p == nullptr) {
      std::cout << "Unable to create FastRTPS domain participant." << std::endl;
      return 1;
   }

   bool isRegistered = false;

   auto* assessment = new AMM::AssessmentPubSubType();

   isRegistered = eprosima::fastrtps::Domain::getRegisteredType(
      p, "Assessment", (eprosima::fastrtps::TopicDataType**) assessment
   );

   if (isRegistered) {
      std::cout << "Assessment is already registered." << std::endl;
      return 1;
   } else {
      std::cout << "Assessment is not registered." << std::endl;
   }

   isRegistered = eprosima::fastrtps::Domain::registerType(
      p, (eprosima::fastrtps::TopicDataType *) assessment
   );

   if (isRegistered) {
      std::cout << "Assessment is registered." << std::endl;
   } else {
      std::cout << "Assessment is not registered." << std::endl;
   }

   isRegistered = eprosima::fastrtps::Domain::unregisterType(p, "Assessment");

   if (isRegistered) {
      std::cout << "Assessment is registered." << std::endl;
   } else {
      std::cout << "Assessment is not registered." << std::endl;
   }

   delete assessment;

   return 0;
```

Output:
```
Assessment is not registered.
Assessment is registered.
Assessment is registered.
```

**Comment by ghostravenstorm** [comment]
```
int ddsTest2 (eprosima::fastrtps::Participant* p, AMM::AssessmentPubSubType* a) {

   bool isRegistered = false;

   isRegistered = eprosima::fastrtps::Domain::getRegisteredType(
      p, "Assessment", (eprosima::fastrtps::TopicDataType**) a
   );

   if (isRegistered) {
      std::cout << "Assessment is already registered." << std::endl;
      return 1;
   } else {
      std::cout << "Assessment is not registered." << std::endl;
   }

   isRegistered = eprosima::fastrtps::Domain::registerType(
      p, (eprosima::fastrtps::TopicDataType *) a
   );

   if (isRegistered) {
      std::cout << "Assessment is registered." << std::endl;
   } else {
      std::cout << "Assessment is not registered." << std::endl;
   }

   bool isUnregistered = false;
   isUnregistered = eprosima::fastrtps::Domain::unregisterType(p, "Assessment");

   if (isUnregistered) {
      std::cout << "Assessment is unregistered." << std::endl;
   } else {
      std::cout << "Assessment is not unregistered." << std::endl;
   }

   isRegistered = eprosima::fastrtps::Domain::getRegisteredType(
      p, "Assessment", (eprosima::fastrtps::TopicDataType**) a
   );

   if (isRegistered) {
      std::cout << "Assessment is registered." << std::endl;
      return 1;
   } else {
      std::cout << "Assessment is not registered." << std::endl;
   }

   return 0;
}

int main () {

   eprosima::fastrtps::ParticipantAttributes pa;
   pa.rtps.builtin.domainId = (uint32_t) 14;
   pa.rtps.setName("Test Module");

   auto* p = eprosima::fastrtps::Domain::createParticipant(pa);
   if (p == nullptr) {
      std::cout << "Unable to create FastRTPS domain participant." << std::endl;
      return 1;
   }

   auto* a = new AMM::AssessmentPubSubType();

   ddsTest2(p, a);
   std::cout << "\n\n" <<std::endl;
   ddsTest2(p, a);

   return 0;
}
```

Output:
```
Assessment is not registered.
Assessment is registered.
Assessment is unregistered.
Assessment is not registered.


Assessment is not registered.
Assessment is not registered.2019-10-03 18:52:10.407
[PARTICIPANT Error] Assessment is unregistered.
Assessment is not registered.
Type with the same name already exists:AMM::Assessment -> Function eprosima::fastrtps::ParticipantImpl::registerType
```

I don't get it. Is `unregisterType` doing something to my `AMM::Assessment` object?

**Comment by ghostravenstorm** [comment]
Found these comments in the source code for `Domain.cpp`
I don't know Spanish, so I'm using Google Translate to understand what they're saying.

> //TODO El registro debería hacerse de manera que no tengamos un objeto del usuario sino que tengamos un objeto TopicDataTYpe propio para que no
> //haya problemas si el usuario lo destruye antes de tiempo.

Something to do with memory management on the back end I'm guessing, but this makes it sound like an issue that's bleeding over into user space. So I'm wondering if using `registerType` then immediately `unregisterType` is causing problems.

**Comment by ghostravenstorm** [comment]
Here's another discovery.
My types don't seem to be properly registered in the first place.

```
eprosima::fastrtps::ParticipantAttributes pa;
   pa.rtps.builtin.domainId = (uint32_t) 14;
   pa.rtps.setName("Test Module");

   auto* p = eprosima::fastrtps::Domain::createParticipant(pa);
   if (p == nullptr) {
      std::cout << "Unable to create FastRTPS domain participant." << std::endl;
      return 1;
   }

   AMM::AssessmentPubSubType a;

   bool isRegistered = false;

   isRegistered = eprosima::fastrtps::Domain::registerType(p, &a);

   if (isRegistered) {
      std::cout << "Assessment has been registered." << std::endl;
   } else {
      std::cout << "Assessment could not be registered." << std::endl;
   }

   isRegistered = eprosima::fastrtps::Domain::getRegisteredType(p, "Assessment", (eprosima::fastrtps::TopicDataType**) &a);

   if (isRegistered) {
      std::cout << "CHECK: Assessment is already registered." << std::endl;
      return 1;
   } else {
      std::cout << "CHECK: Assessment is not registered." << std::endl;
   }
```

Output
```
Assessment has been registered.
CHECK: Assessment is not registered.
```

**Comment by ghostravenstorm** [comment]
This is very strange to me.
When registering a type, you give a ref to the participant and the type.
But, when checking if it's already registered or trying to unregister, you give the participant and the name of the type - not a ref to the type itself like before.
So my question is, how is this setting the name when registering? How is the name I choose for my type and the name it knows it by upon registry the same?

**Comment by MiguelCompany** [comment]
> Am I using `getRegisteredType` correctly?

No, you are not. Method getRegisteredType receives a double pointer for a reason. It will return the pointer to the currently registered type.

On your `ddsTest2`, when you call `getRegisteredType` at the end, the contents of your data type are being overwritten. 

>    `isRegistered = eprosima::fastrtps::Domain::getRegisteredType(p, "Assessment", (eprosima::fastrtps::TopicDataType**) &a);`

This line will surely overwrite your stack, as getRegisteredType will return the pointer to the currently registered type using the pointer it receives on the second parameter.

The correct way would be to have a local variable `TopicDataType* reg_type` and call  `isRegistered = eprosima::fastrtps::Domain::getRegisteredType(p, "Assessment", &reg_type);`

> This is very strange to me.
> When registering a type, you give a ref to the participant and the type.
> But, when checking if it's already registered or trying to unregister, you give the participant and the name of the type - not a ref to the type itself like before.
> So my question is, how is this setting the name when registering? How is the name I choose for my type and the name it knows it by upon registry the same?

I agree this may be confusing. It may be a good idea to separate the type name from the data type. registerType would receive an additional parameter for the type name. This way the API would be consistent, and the user could use the same TopicDataType with different type names.

> `    //TODO El registro debería hacerse de manera que no tengamos un objeto del usuario sino que tengamos un objeto TopicDataTYpe propio para que no`
> `    //haya problemas si el usuario lo destruye antes de tiempo.`

This comment is just depicting that the pointer to the registered type should remain valid until it is unregistered. This means it is usually a bad idea to register a type created on the stack, unless it is declared in the main function of the application.

**Comment by ghostravenstorm** [comment]
I also discovered in code there is a `setName()` method on the pubsub types that has to be set or my types seem to get lost in the void.
```
AMM::AssessmentPubSubType assessmentType;
assessmentType.setName("Assessment");
```
I didn't see use of this documented in the user manual.

**Comment by MiguelCompany** [comment]
The default constructor of the PubSubType generated by fastrtpsgen calls setName

**Comment by MiguelCompany** [comment]
Closing this as all questions were answered.
