### ISSUE TITLE
UDPv4Transport address already in use when interface has more than one IP

### ISSUE THREAD

**Issue by blkdev2** [eProsima/Fast-RTPS#77]
I've been trying to run some of the ros2 examples with FastRTPS on OS X (10.11.6), all failed with the following exception:

`libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >: set_option: Address already in use`

This results from the call to setopt (IP_ADD_MEMBERSHIP) here:
https://github.com/eProsima/Fast-RTPS/blob/master/src/cpp/transport/UDPv4Transport.cpp#L172

For whatever reason, my system had an additional IP alias set up for loopback interface lo0. The first iteration through the loop it adds this interface to the group successfully with ip=127.0.0.1. The next iteration with the aliased IP causes the crash.

Issue should be easily reproduced by `ifconfig lo0 alias 127.0.0.2` and running any program that uses `Domain::createParticipant()`

**Comment by blkdev2** [comment]
Did a bit of digging and I'm pretty sure VMWare is the source of the IP loopback alias. So this probably won't affect many users but it's not a completely exotic system configuration.

If I had an elegant solution I'd contribute a patch. It may be the case, though, that this is a reasonable place to violate the fail-fast principle and just catch/log the exception. It should be a fatal error if _all_ addresses fail to join the multicast group, but if _some_ fail I imagine most users would prefer the program continue.

**Comment by k-okada** [comment]
I think I had a similar situation with droplet (https://cloud.digitalocean.com/droplets)
```
user@ubuntu-16:~/ros2_ws/src/eProsima/Fast-RTPS/examples/C++/ClientServerTest/hoge$ ./ClientServerTest  server
Starting 
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  set_option: Address already in use
Aborted
user@ubuntu-16:~/ros2_ws/src/eProsima/Fast-RTPS/examples/C++/ClientServerTest/hoge$ ifconfig
eth0      Link encap:Ethernet  HWaddr 82:9a:25:9d:c5:27  
          inet addr:104.131.157.73  Bcast:104.131.159.255  Mask:255.255.240.0
          inet6 addr: fe80::809a:25ff:fe9d:c527/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:12886 errors:0 dropped:0 overruns:0 frame:0
          TX packets:13055 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:93452469 (93.4 MB)  TX bytes:2127448 (2.1 MB)

eth1      Link encap:Ethernet  HWaddr a2:4d:52:0a:f6:63  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:639 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:114938 (114.9 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:21 errors:0 dropped:0 overruns:0 frame:0
          TX packets:21 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:1126 (1.1 KB)  TX bytes:1126 (1.1 KB)
```

**Comment by ruffsl** [comment]
@k-okada , did you find the issue that was causing `Address already in use` in Fast-RTPS with certain network configs?

**Comment by k-okada** [comment]
@ruffsl , no, but what I found is that we need to escape on some condition or catch error on `set_option`.

```
user@ubuntu-16:~/ros2_ws/src/eProsima/Fast-RTPS$ git diff
diff --git a/src/cpp/transport/UDPv4Transport.cpp b/src/cpp/transport/UDPv4Transport.cpp
index 6854dd6..888351c 100644
--- a/src/cpp/transport/UDPv4Transport.cpp
+++ b/src/cpp/transport/UDPv4Transport.cpp
@@ -169,7 +169,9 @@ bool UDPv4Transport::OpenInputChannel(const Locator_t& locator)
         for (const auto& infoIP : locNames)
         {
             auto ip = boost::asio::ip::address_v4::from_string(infoIP.name);
-            socket.set_option(ip::multicast::join_group(ip::address_v4::from_string(locator.to_IP4_stri
ng()), ip));
+           std::cerr << "ip " << infoIP.name << std::endl;
+           if ( infoIP.name != "10.12.0.5" && infoIP.name != "172.17.0.1" )
+           socket.set_option(ip::multicast::join_group(ip::address_v4::from_string(locator.to_IP4_strin
g()), ip));
         }
     }
```

**Comment by dhood** [comment]
This is still an issue. As another data point, I get this error on OS X if I have a VPN connection:

```
$ RMW_IMPLEMENTATION=rmw_fastrtps_cpp ros2 run demo_nodes_cpp talker
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: set_option: Address already in use
Abort trap: 6
```
 

Disconnecting from the VPN fixes it. This can easily be people's first experience with fastrtps/ROS 2, so it would be great to at least improve the error message for this.

For reference, the equivalent behaviour with opensplice gives:
 
```
$ RMW_IMPLEMENTATION=rmw_opensplice_cpp ros2 run demo_nodes_cpp talker
========================================================================================
Report      : WARNING
Date        : Fri Dec 08 10:40:08 PST 2017
Description : using network interface en0 (172.23.2.232) selected arbitrarily from: en0, tap0, tap0

Node        : dmp-2.local
Process     : talker <51561>
Thread      : ddsi2 10c862000
Internals   : 6.7.171127OSS/fcc005a2/fcc005a2/ddsi2/q_nwif.c/988/0/1512758408.733316000/70
[INFO] [talker]: Publishing: 'Hello World: 1'
[INFO] [talker]: Publishing: 'Hello World: 2'
 ```

**Comment by hebo910820** [comment]
Has anyone solved this problem?

**Comment by richiware** [comment]
We tried to reproduce your problem without success. In our environment we used ethernet and wireless. The common thing between you could be have an VPN connection. All of you have this error using an VPN connection or occurs with normal ethernet and wireless connections?

**Comment by blkdev2** [comment]
@richiware Did you try adding an alias to the loopback interface as I described? For me, I believe it was VMware Fusion that created the alias on my machine in the original case. But regardless of the reason, it seemed that the crash would occur whenever any network interface had more than one IP address.

**Comment by richiware** [comment]
Not, I didn't try that. I will test it. Thanks

**Comment by hordurj** [comment]
I get the same error running Ubuntu 16.04 under virtual box not running through VPN. I have several interfaces, I'm not sure which one Fast-RTPS is trying to use. Works fine with opensplice as dhood reported above.

**Comment by hordurj** [comment]
I looked into this a bit closer and I noticed that you are trying to join the multicast group multiple times on the same socket. So an error occurs when an interface has multiple ip addresses. On Linux if you try to setsockopt IP_ADD_MEMBERSHIP multiple times for the same address and port on the same interface it will return error EADDRINUSE.

This can be easily solved by just catching the exception and continuing, though that could hide some other failures.

Alternatively you could join the group once for each interface. I noticed in your code to get ip addresses (at least on Linux) you are calling getifaddrs which provides interface name. The interface name can be used to ensure you join the group once per each interface, e.g. something like the patch below. 
```
diff --git a/include/fastrtps/utils/IPFinder.h b/include/fastrtps/utils/IPFinder.h
index 3d50819..0a07753 100644
--- a/include/fastrtps/utils/IPFinder.h
+++ b/include/fastrtps/utils/IPFinder.h
@@ -55,6 +55,7 @@ public:
 		IPTYPE type;
 		uint32_t scope_id;
 		std::string name;
+                std::string dev;
 		Locator_t locator;
 	}info_IP;
 #endif
diff --git a/src/cpp/transport/UDPv4Transport.cpp b/src/cpp/transport/UDPv4Transport.cpp
index 8266c03..ccbfac4 100644
--- a/src/cpp/transport/UDPv4Transport.cpp
+++ b/src/cpp/transport/UDPv4Transport.cpp
@@ -207,7 +207,14 @@ bool UDPv4Transport::OpenInputChannel(const Locator_t& locator)
 
         std::vector<IPFinder::info_IP> locNames;
         GetIP4s(locNames, true);
-        for (const auto& infoIP : locNames)
+
+        std::vector<IPFinder::info_IP> interfaces;
+        std::sort(locNames.begin(), locNames.end(),
+            [] (const IPFinder::info_IP& a, const IPFinder::info_IP& b) -> bool {return a.dev < b.dev;});
+        std::unique_copy(locNames.begin(), locNames.end(),
+            std::back_inserter(interfaces),
+            [] (const IPFinder::info_IP& a, const IPFinder::info_IP& b) -> bool {return a.dev == b.dev;});
+        for (const auto& infoIP : interfaces)
         {
             auto ip = asio::ip::address_v4::from_string(infoIP.name);
 #if defined(ASIO_HAS_MOVE)
diff --git a/src/cpp/utils/IPFinder.cpp b/src/cpp/utils/IPFinder.cpp
index d675b19..0abe66f 100644
--- a/src/cpp/utils/IPFinder.cpp
+++ b/src/cpp/utils/IPFinder.cpp
@@ -152,6 +152,7 @@ bool IPFinder::getIPs(std::vector<info_IP>* vec_name, bool return_loopback)
             info_IP info;
             info.type = IP4;
             info.name = std::string(host);
+            info.dev = std::string(ifa->ifa_name);
             parseIP4(info);
 
             if (return_loopback || info.type != IP4_LOCAL)
@@ -170,6 +171,7 @@ bool IPFinder::getIPs(std::vector<info_IP>* vec_name, bool return_loopback)
             info_IP info;
             info.type = IP6;
             info.name = std::string(host);
+            info.dev = std::string(ifa->ifa_name);
             if(parseIP6(info))
             {
                 info.scope_id = so->sin6_scope_id;

**Comment by richiware** [comment]
Thanks @hordurj . I've pushed commit a7101e3353af3cc405c19cfd21de9ba5028e9929 based on your diff.

**Comment by MiguelCompany** [comment]
Solved long ago by using the code provided by the OP. Closing this issue
