### ISSUE TITLE
Segmentation Fault with null access to change

### ISSUE THREAD

**Issue by wjwwood** [eProsima/Fast-RTPS#78]
I encounter this periodically when using the ROS 2 `dynamic_bridge`program to send large messages (image messages) with Fast-RTPS:

```
Thread 12 "dynamic_bridge" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd77fe700 (LWP 18681)]
eprosima::fastrtps::rtps::ReaderProxy::set_change_to_status (this=0xc33c70, change=0x0, 
    status=status@entry=eprosima::fastrtps::rtps::UNDERWAY)
    at /home/william/ros2_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/writer/ReaderProxy.cpp:196
196	    if(change->sequenceNumber <= changesFromRLowMark_)
(gdb) bt
#0  eprosima::fastrtps::rtps::ReaderProxy::set_change_to_status (this=0xc33c70, change=0x0, 
    status=status@entry=eprosima::fastrtps::rtps::UNDERWAY)
    at /home/william/ros2_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/writer/ReaderProxy.cpp:196
#1  0x00007ffff2cf32ab in eprosima::fastrtps::rtps::StatefulWriter::send_any_unsent_changes (this=0xc0e120)
    at /home/william/ros2_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/writer/StatefulWriter.cpp:233
#2  0x00007ffff2cecea8 in eprosima::fastrtps::rtps::AsyncWriterThread::run ()
    at /home/william/ros2_ws/src/eProsima/Fast-RTPS/src/cpp/rtps/resources/AsyncWriterThread.cpp:126
#3  0x00007ffff5a51c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff79bd6ba in start_thread (arg=0x7fffd77fe700) at pthread_create.c:333
#5  0x00007ffff54c082d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

It looks like the `change` parameter to the `set_change_to_status` method is null. I can try to provide more details if it would help (like steps to reproduce).

**Comment by spiderkeys** [comment]
Out of curiosity, how large is "large" within the context of your application? We are working on a video streaming application that is sending frames that are between 30kB and 150kB (total bandwidth ~10Mbits/s) and am wondering if we should keep an eye out for a similar failure.

From what I read, FastRTPS should be capable of handling large data, given the proper Publisher/Writer QOS configuration. If there are any discrepancies, we would like to know.

From the docs: 
```c++
// Allow fragmentation
PublisherAttributes Wparam;
Wparam.qos.m_publishMode.kind = ASYNCHRONOUS_PUBLISH_MODE;

WriterAttributes Wparam;
Wparam.mode= ASYNCHRONOUS_WRITER;
```

**Comment by wjwwood** [comment]
The images were on the order of 300kb each at 30Hz, but we can adjust the resolution up or down so it can vary.

**Comment by JavierIH** [comment]
Hi, we have found what is causing this error and we are working on it. Thank you again for the feedback.
