### ISSUE TITLE
‘BEST_EFFORT_RELIABILITY_QOS’ is not a member of ‘eprosima::fastrtps’

### ISSUE THREAD

**Issue by ivanpauno** [eProsima/Fast-RTPS#785]
It seems that after https://github.com/eProsima/Fast-RTPS/pull/775, `BEST_EFFORT_RELIABILITY_QOS` is not more a member of `eprosima::fastrtps`, but of `eprosima::fastdds`.
I wonder if the old symbol will be added back, or if we have to update `ros2` code.

Some examples of failing builds:
- https://ci.ros2.org/job/ci_linux/8359/console#console-section-11
- https://ci.ros2.org/job/ci_linux-aarch64/4290/console#console-section-9
- https://ci.ros2.org/view/nightly/job/nightly_linux-armhf_repeated/259/consoleFull#console-section-264

Similar issues with other QoS related symbols.

**Comment by MiguelCompany** [comment]
@ivanpauno We are migrating files as part of the DDS API implementation. When migrating WriterQos, we forgot to keep the include of QosPolices.h, which defines the old enumerations and their values.

**Comment by ivanpauno** [comment]
> @ivanpauno We are migrating files as part of the DDS API implementation. When migrating WriterQos, we forgot to keep the include of QosPolices.h, which defines the old enumerations and their values. I just created #786 for this.

Sounds good, thanks for the quick response!
