### ISSUE TITLE
[question] Piggyback heartbeats

### ISSUE THREAD

**Issue by dhood** [eProsima/Fast-RTPS#79]
In [this comment](https://github.com/ros2/rmw_fastrtps/issues/81#issuecomment-281589897) you mentioned that piggyback heartbeats are on the roadmap for FastRTPS.

Are you able to comment on when this feature can be expected?

**Comment by richiware** [comment]
We are working on a new release. It will be out in a few weeks. After that we have scheduled to implement piggyback heartbeats.

**Comment by dhood** [comment]
Thank you for your response!

**Comment by richiware** [comment]
[release/1.5.0](https://github.com/eProsima/Fast-RTPS/commits/release/1.5.0) will contain the implementation of a piggyback heartbeat
