### ISSUE TITLE
Multiple definition of `eprosima::fastdds::dds::DATAREADER_QOS_DEFAULT'

### ISSUE THREAD

**Issue by ivanpauno** [eProsima/Fast-RTPS#790]
Linker error when compiling `Fast-RTPS` in a ROS 2 workspace (using `master` version of this repo).
I don't know if this is also happening in a standard `Fast-RTPS` build or not.

See:
https://ci.ros2.org/job/ci_linux/8385/consoleFull#console-section-258
https://github.com/ros2/ros2/pull/801

**Comment by MiguelCompany** [comment]
This has already been detected and is being fixed on #783.

**Comment by raquelalvarezbanos** [comment]
Closing, as it should be fixed now. Feel free to reopen if that is not the case.
