### ISSUE TITLE
TinyXML2 installed but not detected during build

### ISSUE THREAD

**Issue by cvilas** [eProsima/Fast-RTPS#824]
Fast-CDR and foonathan-memory was built and installed separately first.
asio and tinyXML were installed as `sudo apt install libasio-dev libtinyxml2-dev`

The above should take care of all third party dependencies for FastRTPS. However  on configuring build using `cmake` without the `-DTHIRDPARTY=ON` option, I get

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
TINYXML2_LIBRARY (ADVANCED)
linked by target "fastrtps" in directory /home/pi/projects/third_party/Fast-RTPS/src/cpp
```

**Comment by deitry** [comment]
@cvilas 
I encountered similar problem when cross-compiling this on armhf. Well, with `-DTHIRPDARTY=ON` I managed to build it successfully, but your issue is the first place I ever heared of such flag.

Is `-DTHIRPDARTY` documented somewhere?

**Comment by cvilas** [comment]
That flag was supported and documented in the README. Perhaps they don't
any more
