### ISSUE TITLE
[question] Crypto:AES-GCM-GMAC 

### ISSUE THREAD

**Issue by enrique-soriano** [eProsima/Fast-RTPS#86]
Hi, 

The Crypto:AES-GCM-GMAC documentation says:

*This built-in plugin provides authenticated encryption using AES in Galois Counter Mode (AES-GCM). It also provide additional reader-specific message authentication codes (MACs) using Galois MAC (AES-GMAC). This plugin needs the activation of the security plugin Auth:PKI-DH*

Are you using a GMAC to authenticate the encrypted messages? If so, it's redundant and inefficient. AES-GCM is an authenticated mode of operation: if the ciphertext integrity is compromised, the decryption fails.

Am I missing anything?

Thanks in advance.

**Comment by richiprosima** [comment]
The same shared secret is used to encrypt the message and all subscribers can decrypt the message using this shared secret. But several GMAC accompany the encrypted message, one GMAC for each subscriber. Each GMAC is calculated with a different shared secret between the publisher and the subscriber.

Then the shared secret for encryption could be compromised, but not the other shared secrets, and a subscriber can detect the message is not comming from the expected publisher.

Does it answer you?

**Comment by enrique-soriano** [comment]
Ok, it makes sense.

Is there any white paper describing the crypto protocol?

Thanks.

**Comment by richiprosima** [comment]
You can find information in this [link](http://www.omg.org/spec/DDS-SECURITY/)

**Comment by enrique-soriano** [comment]
Great, thanks.
