### ISSUE TITLE
Does serializedPayload.length include encapsulation

### ISSUE THREAD

**Issue by jespersmith** [eProsima/Fast-RTPS#87]
Before 1.3.1, serializedPayload.length did not seem to include the encapsulated length. As I do my own serialization (in pure java instead of C++ + JNI) I'm wondering if serializedPayload.length should be set to the length including or excluding encapsulation.

**Comment by JavierIH** [comment]
Exactly. In 1.4.0 serializedPayload.length includes the size of the encapsulation, since this is part of the serialized data.
