### ISSUE TITLE
Participant removing discovery

### ISSUE THREAD

**Issue by alekseymt74** [eProsima/Fast-RTPS#89]
As it was told in [#13](https://github.com/eProsima/Fast-RTPS/issues/13) it's impossible to detect remote peers that were abnormally terminated.
As I see in normal case ParticipantListener is notified from PDPSimpleListener::onNewCacheChangeAdded after calling to PDPSimple::removeRemoteParticipant.
In abnormal termination case only PDPSimple::removeRemoteParticipant called from RemoteParticipantLeaseDuration::event.
So, for test purposes I moved the piece of code which notifies ParticipantListener to PDPSimple::removeRemoteParticipant.
Now ParticipantListener is notified in both cases.
Is it correct? And if so can it be added to next release? Or I can make pull request with this changes..
P.S. It will be usefull to add new element like DROPPED_RTPSPARTICIPANT to DISCOVERY_STATUS which will be informative for the user.

Thanks

**Comment by richiprosima** [comment]
You're right. The event didn't call the user listener. In @b285f9b367 we added it and the element DROPPED_RTPSPARTICIPANT.
Thanks @alekseymt74

**Comment by richiware** [comment]
I will close this issue. If you detect something you can reopen it. Thanks for the reporting
