### ISSUE TITLE
Partitions not working anymore?

### ISSUE THREAD

**Issue by Karsten1987** [eProsima/Fast-RTPS#90]
I've noticed that my DDS Partition implementation as for the ROS2 namespacing does not work anymore after compiling against the latest FAST-RTPS master.

I tried running the `Filtering` examples, but I believe these don't work either anymore.

```
 ➭ ./FilteringExample publisher
Starting
Fast Publisher created, waiting for Subscribers.
Slow Publisher created, waiting for Subscribers.
```

```
 ➭ ./FilteringExample subscriber fast
Starting
Waiting for Data, press Enter to stop the Subscriber.
```

I believe with the giving code snippets, I started a `Fast Publisher` and a `Fast Subscriber`, but I don't see them getting matched which corresponds to the ROS2 behavior.

Can you/anybody confirm this? Maybe I am doing something wrong, but I would need that feature working again as it is an elementary design decision to implement namespacing in ROS2 based on DDS partitions.

thanks for the help.

**Comment by richiprosima** [comment]
Adding a security check reading partitions information breaks it. It's resolved in @fb9da06f606

Thanks @Karsten1987
