### ISSUE TITLE
HelloWorldExampleTCP one Publisher to two Subscribers

### ISSUE THREAD

**Issue by wennycooper** [eProsima/Fast-RTPS#911]
Hi,

I'm new to Fast-RTPS. I would like to use HelloWorldExampleTCP to run a publisher to publish messages to two subscribers. I started two subscribers node in pc1 and then start a publisher in pc0.

The expected result should be: both subscribers received messages sent from publisher. But the actual result is, only one subscriber received the messages.

![Screenshot from 2019-12-05 09-31-52](https://user-images.githubusercontent.com/7479445/70196563-1a056e80-1744-11ea-8cd8-06f82664c251.png)

Any comment will be appreciated.

Kevin Kuei

**Comment by richiware** [comment]
Could you test using the argument `-s 1000` in the publisher? I think the second subscriber doesn't have time to discover the publisher. Sending 1000 samples the publisher will be running more time.

**Comment by wennycooper** [comment]
hi @richiprosima,
You are right. It solved the problem. Thanks!
