### ISSUE TITLE
Subscriber failed to receive messages without knowing publisher's IP address

### ISSUE THREAD

**Issue by wennycooper** [eProsima/Fast-RTPS#913]
Hi, 
My subscriber can not receive any message from publisher across networks. 
Here is the configuration:

```
In PC0 (ip: 192.168.1.2)
$ HelloWorldExampleTCP publisher -a 192.168.1.2 -s 1000
```

```
In PC1 (ip: 192.168.2.2)
$ HelloWorldExampleTCP subscriber -a 192.168.1.2
```

```
In PC2 (ip: 192.168.2.20)
$ HelloWorldExampleTCP subscriber -a 192.168.2.2
```

In PC1, the subscriber specified publisher's ip as the peer can receive messages without any problem. 
In PC2, the subscriber specified PC1's ip as the peer but it can not receive any message.

Note that PC0 and PC1+PC2 are not on the same network. Multicast discovery won't work because router swallowed the multicast packets. 

Why PC2 points to PC1 instead of pointing to PC0?
My theory is, DDS is a distributed system and all the participants are responsible for managing metatraffic. So, PC1 knows PC0 and PC2 point to PC1 can learn about PC0. 

Is the theory correct? If NO, how can a subscriber to receive message without explicitly pointing to the publisher's ip?

**Comment by richiware** [comment]
DDS doesn't work as you expect. Each participant is responsible for distributing only its meta-traffic. For default, using UDP transport, its meta-traffic is distributed using multicast.

But TCP transport works differently. TCP transport creates a TCP connection between two participants. And that TCP connection has to be configured by the user. The user has to specify which participant is the server and which one the client. And for the client, the user has to set the remote IP where the server-role participant is located.

Maybe a solution that can fit for you is using our [Discovery Server](https://github.com/eProsima/Discovery-Server). Take a look.

**Comment by wennycooper** [comment]
Will do. Thank you!
