### ISSUE TITLE
Feature Request: Possibility to compile without the Sqlite3 plugin

### ISSUE THREAD

**Issue by alireza-hosseini** [eProsima/Fast-RTPS#921]
( This is not a bug report, so I'm not using the bug report template. ) 

In our project, we are using FastRTPS and another commercial library which internally contains the same `sqlite3.c` that is used in this project which obviously causes duplicate definition issues in case of linking both of these libraries to the same target. 
As a matter of fact and since `sqlite3` is only used in a plugin, would it be possible to add a `CMAKE` option (which is **enabled** by default) to be able to build `FastRTPS` without this plugin?

**Comment by richiware** [comment]
Thanks for the request. I can't assure you right now when this will be available. Do you think you are able to make the changes and create a Pull Request? All contributions are welcome. From the top of my head, the PR should consist of:

* Add a new CMAKE option `SQLITE3_SUPPORT` by default to ON.
* Depending on the CMake option create a #define in `config.h.in`
* Depending on the CMake option, not compile SQlite3PersistenceService.cpp and sqlite3.c
* Depending on the #define, not use SQLite3PersistenceService in the code.

**Comment by alireza-hosseini** [comment]
@richiware Thanks for your response, I made the requested changes and created a pull request (#922).
