### ISSUE TITLE
Failed to include <thr/xthreads.h> on Windows

### ISSUE THREAD

**Issue by hidmic** [eProsima/Fast-RTPS#927]
Precisely what the title says. Any attempt to build fails as a result.

## Expected Behavior

Builds should not fail.

## Current Behavior

Builds fail with lots of:

```console
../utils/TimedMutex.hpp(26,10): fatal error C1083: Cannot open include file: 'thr/xthreads.h': No such file or directory
```

## Steps to Reproduce

1. Follow [ROS 2 source install instructions for Windows](https://index.ros.org/doc/ros2/Installation/Eloquent/Windows-Development-Setup/).
2. Run `colcon build --packages-up-to fastrtps`

## System information

- Fast-RTPS version: `v1.9.x`  (though I'd expect it to fail on `master` too) 
- OS: Windows Server 2019
- ROS2: Eloquent

## Additional context

To build, I'm using latest Visual Studio 2019 (MSVC 14.24.28314) and CMake 3.16.1. Digging a bit, in this particular MSVC version the `thr/` subdirectory is gone. Changing `<thr/xthreads.h>` to `<xthreads.h>` fixes the problem.

Interestingly enough, there's not much information online about this particular header file. It'd almost seem it's an internal API header, which would explain why it changed without notice.

**Comment by richiware** [comment]
Would you make the changes through a pull request? It will be appreciated.

**Comment by hidmic** [comment]
Sure, I'll send a patch. Though I think it'd be good to find out whether this is an internal header (or why it changed location if it's not). If it turns out it is, I'm somewhat inclined to think Fast-RTPS ought not be using it in the first place. 

Also, I'm a bit wary about breaking existing environments if this gets backported to `v1.9.x`.

**Comment by seanyen** [comment]
> Though I think it'd be good to find out whether this is an internal header (or why it changed location if it's not). If it turns out it is, I'm somewhat inclined to think Fast-RTPS ought not be using it in the first place.

According to [this](https://developercommunity.visualstudio.com/content/problem/413586/-thrd-create-is-missing-from-xthreadsh.html), it seems to me that consuming `xthreads.h` should be avoided and we should be in favor of documented or standard interfaces.

**Comment by brawner** [comment]
It looks like this occurs with VS build tools v14.24. [ci.ros2.org is still running v14.23](https://ci.ros2.org/view/nightly/job/nightly_win_rel/1404/) so it hasn't encountered this issue yet. I've found two work arounds, either building with vs2017 tools, or modifying the vs2019 install to include "MSVC v142 - VS 2019 c++ x64/x86 build tools (v14.23)"

**Comment by richiware** [comment]
Does this [branch](https://github.com/eProsima/Fast-RTPS/tree/bugfix/xthreads-header) work for you? In this branch a public header is included instead of the private header. This public header includes internally the private header. At least in my VS.

**Comment by hidmic** [comment]
@richiware it does work, thanks!

**Comment by brawner** [comment]
Also fixes it for me!

**Comment by seanyen** [comment]
+1 for the verification. I can build it with the `Visual Studio 2019` on the Azure DevOps hosted [`windows-2019`](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md) image.

**Comment by dirk-thomas** [comment]
@hidmic Can this be closed?

**Comment by dirk-thomas** [comment]
@hidmic Friendly ping.

**Comment by hidmic** [comment]
Thanks for the ping, and apologies for the delay. Closing as it has been addressed by https://github.com/eProsima/Fast-RTPS/pull/932.

**Comment by AzmatArkin** [comment]
In Linux :  fatal error: HelloWorldPubSubTypes.h : No such file or directory
In Vs Code/ VC6.0 : fatal error C1083: cannot open include file "HelloWorldPubSubTypes.h"

it's doesn't work

**Comment by EduPonz** [comment]
Hi @AzmatArkin ,

I suggest you consider opening a new issue with a more detail description of what you're trying to do, how you do it, and what exactly does not work. I'm afraid we cannot help you with the amount of information you provide.
