### ISSUE TITLE
ParticipantAttributes::rtps.userData is rewritten on readers side

### ISSUE THREAD

**Issue by alekseymt74** [eProsima/Fast-RTPS#93]
ParameterList::readParameterListfromCDRMsg(..) rewrites user data (UserDataQosPolicy::dataVec) with uninitialized data. Looks like misprint in commit 3cefd4e on 21 Oct 2014 when CDRMessage::readData destination was redirected from 'octet* oc' to p->dataVec but copying from 'oc' to p->dataVec was left.

**Comment by JavierIH** [comment]
Yes, you are absolutely right. Thank you for reporting it.
