### ISSUE TITLE
Discovery Server issue - [RTCP_MSG_IN Error] Bad RTCP header identifier, closing connection [7223]

### ISSUE THREAD

**Issue by Jimmy316** [eProsima/Fast-RTPS#941]
When running using a discovery server with TCP option. When a subscriber reconnect we see the following message on the subscriber. [RTCP_MSG_IN Error] Bad RTCP header identifier, closing connection. 

Note we don't see this message when the subscriber connects the first time. We see this when the subscriber reconnects. To reproduce we are running the following

1. Discovery server running inside a docker container (172.17.0.2 for e.g). 
2. A publisher publishing 1024 * 1024 vector (1MB) of uint8_t. in one container.
3. A subscriber receiving this message on another container. 
4. Kill the subscriber and restart it  will sometimes run into this issue. 

We noticed if we reduce the payload of the message to less than 65514 we never hit this issue. We are wondering if the reconstruction of the packet is the issue here. Also not sure why we don't see this issue when running on non Discovery Server mode.

**Comment by Jimmy316** [comment]
Just wanted to add I am testing on Ubuntu 18.04 docker images. I am using Fast RTPS version 1.9.3.

**Comment by Jimmy316** [comment]
If I leave the subscriber running for sometime I see a similar issue.

**Comment by richiware** [comment]
I was able to reproduce your issue. We will work on it. Thanks for the report.

**Comment by Jimmy316** [comment]
Thanks for the help. We updated the send and receive buffer size to be slightly larger and were able to get around the issue. 
When I see this issue I see that there was some packet fragmentation. Let me know if there is anything I can contribute to help fix this issue. 

--
Jimmy

**Comment by Jimmy316** [comment]
Hi Miguel/Richiware 

Should I pull in Fast RTPS 1.9.3 to get this fix? 
Thanks 

--
Jimmy

**Comment by richiware** [comment]
You should pull 1.9.x. #948 fixes this issue in that branch. 1.9.x will be the next 1.9.4.

**Comment by wutianze** [comment]
Hi, I run into this issue in version 2.0.0. The message I sent was 102400 bytes. Please give me some advice on how to avoid this.
