### ISSUE TITLE
Memory consumption grows (case #2)

### ISSUE THREAD

**Issue by alekseymt74** [eProsima/Fast-RTPS#95]
In configuration 1 pub: 1 sub after some time of execution (depends on quantity/frequency of data packets ((maybe smth else..)) memory consumption grows on subscriber's side.
As I see ReaderHistory::m_cachedRecordLocation size begins to grow wich leads to memory consumption grow.

**Comment by richiprosima** [comment]
@26ddec38147b2a13f5f944bddefe1240b8025886 removes ReaderHistory::m_cachedRecordLocation. Now a reader uses other mechanisms to detect repetead samples as m_cachedRecordLocation did.
Thanks for your feedback.

**Comment by richiware** [comment]
I will close this issue. If you continue noticing memory growing, you can reopen it. Thanks for the reporting.
