### ISSUE TITLE
Publish OpenCV Image from FastRTPS to ROS2

### ISSUE THREAD

**Issue by HemaZ** [eProsima/Fast-RTPS#975]
Hello FastRTPS team,
I'm trying to publish video camera images from opencv using fastRTPS to ROS2 Node.
i've copied Image.idl from ROS2, built it like the HelloWorld example from fastRTPS. changed topicname to `rt/topicname` and added the DS_ namespace.
when i try to publish the image it shows on ROS2 network using `ros2 topic echo`
but after filling the data field of Image message with opencv MAT data. nothing shows.
I use the following function to convert OpenCV MAT to Image Message
`
void toImageMsg(sensor_msgs::msg::Image & ros_image, cv::Mat &image) 
{
  ros_image.height(image.rows);

  ros_image.width(image.cols);

  ros_image.encoding("bgr8");

  ros_image.step(image.cols * image.elemSize());

  size_t size = ros_image.step() * image.rows;

  ros_image.data().resize(size);

 memcpy(&ros_image.data()[0], image.data, size);
}
`

then `mp_publisher->write(&st);`

what I'm doing wrong?

the full project is here
https://github.com/HemaZ/FastRTPS-ROS2

thank you in advance

**Comment by richiware** [comment]
ROS2 not only uses its own naming for the *topic name*, but also for the *type name*. The generated type support by `fastrtpsgen` has a function `setName` which changes the name of the type. You can use it before register the type support in the participant. Or you can change it directly in the generated code.

Hope this helps you.

**Comment by HemaZ** [comment]
> ROS2 not only uses its own naming for the _topic name_, but also for the _type name_. The generated type support by `fastrtpsgen` has a function `setName` which changes the name of the type. You can use it before register the type support in the participant. Or you can change it directly in the generated code.
> 
> Hope this helps you.

i already made these changes and im able to echo the topic successfully using ros2 topic echo.
This before modifing the data field of the message
After modifying it using the function above it doesn't work

**Comment by richiware** [comment]
What do you mean with *modifing the data field of the message*? Can you paste a link to the specific lines of your repo?

**Comment by HemaZ** [comment]
> What do you mean with _modifing the data field of the message_? Can you paste a link to the specific lines of your repo?

This line and the one below
https://github.com/HemaZ/FastRTPS-ROS2/blob/12482fa5f23f670f5e6f835793a5d6a751bc0292/ImagePublisher.cxx#L148

**Comment by richiware** [comment]
It should be related with large data. Please, try this, follow the Fast-RTPS documentation about large data.

https://eprosima-fast-rtps.readthedocs.io/en/latest/advanced.html#sending-large-data

↪ 2020-01-27 lun 09:53, Ibrahim Essam <notifications@github.com>:

**Comment by HemaZ** [comment]
> It should be related with large data. Please, try this, follow the Fast-RTPS documentation about large data. https://eprosima-fast-rtps.readthedocs.io/en/latest/advanced.html#sending-large-data ↪ 2020-01-27 lun 09:53, Ibrahim Essam <notifications@github.com>:
> […](#)
> > What do you mean with _modifing the data field of the message_? Can you paste a link to the specific lines of your repo? This line and the one below https://github.com/HemaZ/FastRTPS-ROS2/blob/12482fa5f23f670f5e6f835793a5d6a751bc0292/ImagePublisher.cxx#L148 -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#975 (comment)](https://github.com/eProsima/Fast-RTPS/issues/975#issuecomment-578649257)

i've configured the publisher publish mode to ASYNCHRONOUS
`    Wparam.qos.m_publishMode.kind = ASYNCHRONOUS_PUBLISH_MODE; `
also the Socket Buffer Size
` PParam.rtps.sendSocketBufferSize = 212992;
   PParam.rtps.listenSocketBufferSize = 212992;`
but the problem is not solved yet. what im missing here?

**Comment by richiware** [comment]
If the `sequence` described in the IDL file doesn't have a maximum size, the default maximum size for the sequence is 
100 elements. To be able to send a larger sequence you need to configure publisher like:

```c++
publisher_attr_.historyMemoryPolicy = rtps::PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
```

and subscriber like:

```c++
subscriber_attr_.historyMemoryPolicy = rtps::PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
```
↪ 2020-01-27 lun 11:32, Ibrahim Essam <notifications@github.com>:

**Comment by HemaZ** [comment]
thank you it works as expected now. I will close this issuse and update my github repo for referenece if anyone would use it.
