### ISSUE TITLE
Syntax Error in Cmake Code

### ISSUE THREAD

**Issue by wijamw** [eProsima/Fast-RTPS#99]
### Then I got this error
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring Fast RTPS
-- Version: 1.4.0
-- To change de version modify the file configure.ac
-- Performing Test SUPPORTS_CXX11
-- Performing Test SUPPORTS_CXX11 - Success
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
CMake Error at CMakeLists.txt:181 (option):
  Syntax error in cmake code at

    /../Fast-RTPS/CMakeLists.txt:182

  when parsing string

    Global flag to cause add_library() to create shared libraries if on. \
      If set to true, this will cause all libraries to be built shared \
      unless the library was explicitly added as a static library.

  syntax error, unexpected cal_SYMBOL, expecting $end (141)

**Comment by tedostrem** [comment]
+1

Same problem exists in the CMakeList.txt of Fast-CDR submodule.
Removing all of the newlines from that expression in both of the CMakeList.txt files fixed it.

**Comment by tedostrem** [comment]
Related to building the project so I will just throw this in here hoping it will be helpful to someone since I can not find this in the documentation.

fastrtpsgen requires fastrtpsgen.jar which can be compiled using the official gradle docker container.

```
$ cd Fast-RTPS/fastrtpsgen
$ docker run --rm -v $(pwd)/../:/project -w /project --name gradle gradle:3.5-jdk7-alpine /bin/sh -c "cd /project/fastrtpsgen && gradle jar"
```

**Comment by JavierIH** [comment]
It seems that split a string in different lines only works on CMake versions >3.0. Thank you for the feedback.
