### ISSUE TITLE
1.9.x API broken in #965

### ISSUE THREAD

**Issue by ivanpauno** [eProsima/Fast-RTPS#998]
## Expected Behavior

API doesn't change when version patch changes.

## Current Behavior

It did change.

## Steps to Reproduce

When building ros2 from source, `rmw_fastrtps_shared_cpp` build fails:
https://ci.ros2.org/job/ci_linux/9238/consoleFull#console-section-274

## System information

- Fast-RTPS version:  6c255455ce5a24982ce30dba043a78708f7738b8
- OS:  Ubuntu 18.04
- Network interfaces: 
                      
- ROS2: 
         master

## Additional context

I think the problem was introduced in #965, though I haven't thoroughly checked.

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by ivanpauno** [comment]
@richiprosima @MiguelCompany qq: was this API change desired?

**Comment by MiguelCompany** [comment]
@ivanpauno You are right. It has been introduced by #965. It seems to have been overlooked when reviewing. I have just reverted it, and we will rework the changes to accommodate them without changing the API.

**Comment by ivanpauno** [comment]
Thanks for the fast feedback, will check again now!

**Comment by ivanpauno** [comment]
Closing, as the problem was solved.
